name: black

on:
  pull_request:
  push:

permissions: read-all

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install --user colorama watchdog levenshtein cxxfilt black==24.4.2
      - run: python3 -m black --check .
