.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.18.0 */

glabel D_803A9200
/* 1BB280 803A9200 */ .space 0x28

glabel D_803A9228
/* 1BB2A8 803A9228 */ .space 0x02

glabel D_803A922A
/* 1BB2AA 803A922A */ .space 0x02

glabel D_803A922C
/* 1BB2AC 803A922C */ .space 0x01

glabel D_803A922D
/* 1BB2AD 803A922D */ .space 0x01

glabel D_803A922E
/* 1BB2AE 803A922E */ .space 0x02

glabel D_803A9230
/* 1BB2B0 803A9230 */ .space 0x02

glabel D_803A9232
/* 1BB2B2 803A9232 */ .space 0x02

glabel D_803A9234
/* 1BB2B4 803A9234 */ .space 0x44

glabel D_803A9278
/* 1BB2F8 803A9278 */ .space 0x08

glabel D_803A9280
/* 1BB300 803A9280 */ .space 0x02

glabel D_803A9282
/* 1BB302 803A9282 */ .space 0x02

glabel D_803A9284
/* 1BB304 803A9284 */ .space 0x01

glabel D_803A9285
/* 1BB305 803A9285 */ .space 0x01

glabel D_803A9286
/* 1BB306 803A9286 */ .space 0x02

glabel D_803A9288
/* 1BB308 803A9288 */ .space 0x02

glabel D_803A928A
/* 1BB30A 803A928A */ .space 0x01

glabel D_803A928B
/* 1BB30B 803A928B */ .space 0xE5

glabel D_803A9370
/* 1BB3F0 803A9370 */ .space 0x02

glabel D_803A9372
/* 1BB3F2 803A9372 */ .space 0x0E

glabel D_803A9380
/* 1BB400 803A9380 */ .space 0x10

glabel D_803A9390
/* 1BB410 803A9390 */ .space 0x830

glabel D_803A9BC0
/* 1BBC40 803A9BC0 */ .space 0x4890

glabel D_803AE450
/* 1C04D0 803AE450 */ .space 0x20

glabel D_803AE470
/* 1C04F0 803AE470 */ .space 0x10

glabel D_803AE480
/* 1C0500 803AE480 */ .space 0x4880

glabel D_803B2D00
/* 1C4D80 803B2D00 */ .space 0x420

glabel D_803B3120
/* 1C51A0 803B3120 */ .space 0xC30

glabel D_803B3D50
/* 1C5DD0 803B3D50 */ .space 0x04

glabel D_803B3D54
/* 1C5DD4 803B3D54 */ .space 0x04

glabel D_803B3D58
/* 1C5DD8 803B3D58 */ .space 0x04

glabel D_803B3D5C
/* 1C5DDC 803B3D5C */ .space 0x04

glabel D_803B3D60
/* 1C5DE0 803B3D60 */ .space 0x04

glabel D_803B3D64
/* 1C5DE4 803B3D64 */ .space 0x04

glabel D_803B3D68
/* 1C5DE8 803B3D68 */ .space 0x04

glabel D_803B3D6C
/* 1C5DEC 803B3D6C */ .space 0x04

glabel D_803B3D70
/* 1C5DF0 803B3D70 */ .space 0x04

glabel D_803B3D74
/* 1C5DF4 803B3D74 */ .space 0x04

glabel D_803B3D78
/* 1C5DF8 803B3D78 */ .space 0x04

glabel D_803B3D7C
/* 1C5DFC 803B3D7C */ .space 0x04

glabel D_803B3D80
/* 1C5E00 803B3D80 */ .space 0x08

glabel D_803B3D88
/* 1C5E08 803B3D88 */ .space 0x40

glabel D_803B3DC8
/* 1C5E48 803B3DC8 */ .space 0x40

glabel D_803B3E08
/* 1C5E88 803B3E08 */ .space 0x04

glabel D_803B3E0C
/* 1C5E8C 803B3E0C */ .space 0x04

glabel D_803B3E10
/* 1C5E90 803B3E10 */ .space 0x04

glabel D_803B3E14
/* 1C5E94 803B3E14 */ .space 0x0C

glabel D_803B3E20
/* 1C5EA0 803B3E20 */ .space 0x04

glabel D_803B3E24
/* 1C5EA4 803B3E24 */ .space 0x04

glabel D_803B3E28
/* 1C5EA8 803B3E28 */ .space 0x04

glabel D_803B3E2C
/* 1C5EAC 803B3E2C */ .space 0x04

glabel D_803B3E30
/* 1C5EB0 803B3E30 */ .space 0x04

glabel D_803B3E34
/* 1C5EB4 803B3E34 */ .space 0x04

glabel D_803B3E38
/* 1C5EB8 803B3E38 */ .space 0x04

glabel D_803B3E3C
/* 1C5EBC 803B3E3C */ .space 0x04

glabel D_803B3E40
/* 1C5EC0 803B3E40 */ .space 0x04

glabel D_803B3E44
/* 1C5EC4 803B3E44 */ .space 0x04

glabel D_803B3E48
/* 1C5EC8 803B3E48 */ .space 0x04

glabel D_803B3E4C
/* 1C5ECC 803B3E4C */ .space 0x02

glabel D_803B3E4E
/* 1C5ECE 803B3E4E */ .space 0x02

glabel D_803B3E50
/* 1C5ED0 803B3E50 */ .space 0x04

glabel D_803B3E54
/* 1C5ED4 803B3E54 */ .space 0x04

glabel D_803B3E58
/* 1C5ED8 803B3E58 */ .space 0x04

glabel D_803B3E5C
/* 1C5EDC 803B3E5C */ .space 0x02

glabel D_803B3E5E
/* 1C5EDE 803B3E5E */ .space 0x02

glabel D_803B3E60
/* 1C5EE0 803B3E60 */ .space 0x02

glabel D_803B3E62
/* 1C5EE2 803B3E62 */ .space 0x06

glabel D_803B3E68
/* 1C5EE8 803B3E68 */ .space 0x40

glabel D_803B3EA8
/* 1C5F28 803B3EA8 */ .space 0x02

glabel D_803B3EAA
/* 1C5F2A 803B3EAA */ .space 0x02

glabel D_803B3EAC
/* 1C5F2C 803B3EAC */ .space 0x04

glabel D_803B3EB0
/* 1C5F30 803B3EB0 */ .space 0x04

glabel D_803B3EB4
/* 1C5F34 803B3EB4 */ .space 0x04

glabel D_803B3EB8
/* 1C5F38 803B3EB8 */ .space 0x04

glabel D_803B3EBC
/* 1C5F3C 803B3EBC */ .space 0x04
