.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.18.0 */

glabel D_80396B60
/* 1A8BE0 80396B60 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 1A8BE4 80396B64 AFB00010 */  sw         $s0, 0x10($sp)
/* 1A8BE8 80396B68 00808021 */  addu       $s0, $a0, $zero
/* 1A8BEC 80396B6C AFBF0014 */  sw         $ra, 0x14($sp)
/* 1A8BF0 80396B70 9603001C */  lhu        $v1, 0x1C($s0)
/* 1A8BF4 80396B74 24020001 */  addiu      $v0, $zero, 0x1
/* 1A8BF8 80396B78 10620010 */  beq        $v1, $v0, .L80396BBC_ovl8
/* 1A8BFC 80396B7C 28620002 */   slti      $v0, $v1, 0x2
/* 1A8C00 80396B80 50400005 */  beql       $v0, $zero, .L80396B98_ovl8
/* 1A8C04 80396B84 3402FFFF */   ori       $v0, $zero, 0xFFFF
/* 1A8C08 80396B88 10600007 */  beqz       $v1, .L80396BA8_ovl8
/* 1A8C0C 80396B8C 00001021 */   addu      $v0, $zero, $zero
/* 1A8C10 80396B90 080E5AF8 */  j          .L80396BE0_ovl8
/* 1A8C14 80396B94 00000000 */   nop
.L80396B98_ovl8:
/* 1A8C18 80396B98 1062000C */  beq        $v1, $v0, .L80396BCC_ovl8
/* 1A8C1C 80396B9C 00001021 */   addu      $v0, $zero, $zero
/* 1A8C20 80396BA0 080E5AF8 */  j          .L80396BE0_ovl8
/* 1A8C24 80396BA4 00000000 */   nop
.L80396BA8_ovl8:
/* 1A8C28 80396BA8 0C0E5AFD */  jal        func_80396BF4
/* 1A8C2C 80396BAC 00000000 */   nop
/* 1A8C30 80396BB0 24020001 */  addiu      $v0, $zero, 0x1
/* 1A8C34 80396BB4 080E5AF7 */  j          .L80396BDC_ovl8
/* 1A8C38 80396BB8 A602001C */   sh        $v0, 0x1C($s0)
.L80396BBC_ovl8:
/* 1A8C3C 80396BBC 0C0E5B2A */  jal        func_80396CA8
/* 1A8C40 80396BC0 00000000 */   nop
/* 1A8C44 80396BC4 080E5AF8 */  j          .L80396BE0_ovl8
/* 1A8C48 80396BC8 00001021 */   addu      $v0, $zero, $zero
.L80396BCC_ovl8:
/* 1A8C4C 80396BCC 0C0E5B14 */  jal        func_80396C50
/* 1A8C50 80396BD0 00000000 */   nop
/* 1A8C54 80396BD4 080E5AF8 */  j          .L80396BE0_ovl8
/* 1A8C58 80396BD8 24020001 */   addiu     $v0, $zero, 0x1
.L80396BDC_ovl8:
/* 1A8C5C 80396BDC 00001021 */  addu       $v0, $zero, $zero
.L80396BE0_ovl8:
/* 1A8C60 80396BE0 8FBF0014 */  lw         $ra, 0x14($sp)
/* 1A8C64 80396BE4 8FB00010 */  lw         $s0, 0x10($sp)
/* 1A8C68 80396BE8 27BD0018 */  addiu      $sp, $sp, 0x18
/* 1A8C6C 80396BEC 03E00008 */  jr         $ra
/* 1A8C70 80396BF0 00000000 */   nop
.size D_80396B60, . - D_80396B60

glabel func_80396BF4
/* 1A8C74 80396BF4 24030004 */  addiu      $v1, $zero, 0x4
/* 1A8C78 80396BF8 3C02803B */  lui        $v0, %hi(D_803B3E48)
/* 1A8C7C 80396BFC 24423E48 */  addiu      $v0, $v0, %lo(D_803B3E48)
.L80396C00_ovl8:
/* 1A8C80 80396C00 AC400000 */  sw         $zero, 0x0($v0)
/* 1A8C84 80396C04 2463FFFF */  addiu      $v1, $v1, -0x1
/* 1A8C88 80396C08 0461FFFD */  bgez       $v1, .L80396C00_ovl8
/* 1A8C8C 80396C0C 2442FFFC */   addiu     $v0, $v0, -0x4
/* 1A8C90 80396C10 240200E4 */  addiu      $v0, $zero, 0xE4
.L80396C14_ovl8:
/* 1A8C94 80396C14 3C01803B */  lui        $at, %hi(D_803A9280)
/* 1A8C98 80396C18 00220821 */  addu       $at, $at, $v0
/* 1A8C9C 80396C1C A0209280 */  sb         $zero, %lo(D_803A9280)($at)
/* 1A8CA0 80396C20 2442FFF4 */  addiu      $v0, $v0, -0xC
/* 1A8CA4 80396C24 0441FFFB */  bgez       $v0, .L80396C14_ovl8
/* 1A8CA8 80396C28 00000000 */   nop
/* 1A8CAC 80396C2C 3402FFFF */  ori        $v0, $zero, 0xFFFF
/* 1A8CB0 80396C30 3C01803B */  lui        $at, %hi(D_803A9278)
/* 1A8CB4 80396C34 A4209278 */  sh         $zero, %lo(D_803A9278)($at)
/* 1A8CB8 80396C38 3C01803B */  lui        $at, %hi(D_803A9370)
/* 1A8CBC 80396C3C A4209370 */  sh         $zero, %lo(D_803A9370)($at)
/* 1A8CC0 80396C40 3C01803B */  lui        $at, %hi(D_803A9372)
/* 1A8CC4 80396C44 A4229372 */  sh         $v0, %lo(D_803A9372)($at)
/* 1A8CC8 80396C48 03E00008 */  jr         $ra
/* 1A8CCC 80396C4C 00000000 */   nop
.size func_80396BF4, . - func_80396BF4

glabel func_80396C50
/* 1A8CD0 80396C50 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1A8CD4 80396C54 AFB10014 */  sw         $s1, 0x14($sp)
/* 1A8CD8 80396C58 00008821 */  addu       $s1, $zero, $zero
/* 1A8CDC 80396C5C AFB00010 */  sw         $s0, 0x10($sp)
/* 1A8CE0 80396C60 3C10803B */  lui        $s0, %hi(D_803B3E38)
/* 1A8CE4 80396C64 26103E38 */  addiu      $s0, $s0, %lo(D_803B3E38)
/* 1A8CE8 80396C68 AFBF0018 */  sw         $ra, 0x18($sp)
.L80396C6C_ovl8:
/* 1A8CEC 80396C6C 8E040000 */  lw         $a0, 0x0($s0)
/* 1A8CF0 80396C70 10800004 */  beqz       $a0, .L80396C84_ovl8
/* 1A8CF4 80396C74 26310001 */   addiu     $s1, $s1, 0x1
/* 1A8CF8 80396C78 0C025D58 */  jal        func_80097560
/* 1A8CFC 80396C7C 00000000 */   nop
/* 1A8D00 80396C80 AE000000 */  sw         $zero, 0x0($s0)
.L80396C84_ovl8:
/* 1A8D04 80396C84 2A220005 */  slti       $v0, $s1, 0x5
/* 1A8D08 80396C88 1440FFF8 */  bnez       $v0, .L80396C6C_ovl8
/* 1A8D0C 80396C8C 26100004 */   addiu     $s0, $s0, 0x4
/* 1A8D10 80396C90 8FBF0018 */  lw         $ra, 0x18($sp)
/* 1A8D14 80396C94 8FB10014 */  lw         $s1, 0x14($sp)
/* 1A8D18 80396C98 8FB00010 */  lw         $s0, 0x10($sp)
/* 1A8D1C 80396C9C 27BD0020 */  addiu      $sp, $sp, 0x20
/* 1A8D20 80396CA0 03E00008 */  jr         $ra
/* 1A8D24 80396CA4 00000000 */   nop
.size func_80396C50, . - func_80396C50

glabel func_80396CA8
/* 1A8D28 80396CA8 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 1A8D2C 80396CAC AFB50024 */  sw         $s5, 0x24($sp)
/* 1A8D30 80396CB0 3C15803B */  lui        $s5, %hi(D_803B3E38)
/* 1A8D34 80396CB4 26B53E38 */  addiu      $s5, $s5, %lo(D_803B3E38)
/* 1A8D38 80396CB8 AFB40020 */  sw         $s4, 0x20($sp)
/* 1A8D3C 80396CBC 3C14803B */  lui        $s4, %hi(D_803A9280)
/* 1A8D40 80396CC0 26949280 */  addiu      $s4, $s4, %lo(D_803A9280)
/* 1A8D44 80396CC4 AFB20018 */  sw         $s2, 0x18($sp)
/* 1A8D48 80396CC8 00009021 */  addu       $s2, $zero, $zero
/* 1A8D4C 80396CCC AFBF0028 */  sw         $ra, 0x28($sp)
/* 1A8D50 80396CD0 AFB3001C */  sw         $s3, 0x1C($sp)
/* 1A8D54 80396CD4 AFB10014 */  sw         $s1, 0x14($sp)
/* 1A8D58 80396CD8 AFB00010 */  sw         $s0, 0x10($sp)
.L80396CDC_ovl8:
/* 1A8D5C 80396CDC 92820000 */  lbu        $v0, 0x0($s4)
/* 1A8D60 80396CE0 50400062 */  beql       $v0, $zero, .L80396E6C_ovl8
/* 1A8D64 80396CE4 2694000C */   addiu     $s4, $s4, 0xC
/* 1A8D68 80396CE8 3C03803B */  lui        $v1, %hi(D_803A9282)
/* 1A8D6C 80396CEC 00721821 */  addu       $v1, $v1, $s2
/* 1A8D70 80396CF0 94639282 */  lhu        $v1, %lo(D_803A9282)($v1)
/* 1A8D74 80396CF4 3C02803B */  lui        $v0, %hi(D_803A9370)
/* 1A8D78 80396CF8 94429370 */  lhu        $v0, %lo(D_803A9370)($v0)
/* 1A8D7C 80396CFC 5462005B */  bnel       $v1, $v0, .L80396E6C_ovl8
/* 1A8D80 80396D00 2694000C */   addiu     $s4, $s4, 0xC
/* 1A8D84 80396D04 3C04803B */  lui        $a0, %hi(D_803A9280)
/* 1A8D88 80396D08 24849280 */  addiu      $a0, $a0, %lo(D_803A9280)
/* 1A8D8C 80396D0C 0C0E5BAF */  jal        func_80396EBC
/* 1A8D90 80396D10 02442021 */   addu      $a0, $s2, $a0
/* 1A8D94 80396D14 00021600 */  sll        $v0, $v0, 24
/* 1A8D98 80396D18 00028E03 */  sra        $s1, $v0, 24
/* 1A8D9C 80396D1C 2402FFFF */  addiu      $v0, $zero, -0x1
/* 1A8DA0 80396D20 1222004B */  beq        $s1, $v0, .L80396E50_ovl8
/* 1A8DA4 80396D24 00111880 */   sll       $v1, $s1, 2
/* 1A8DA8 80396D28 00759821 */  addu       $s3, $v1, $s5
/* 1A8DAC 80396D2C 8E640000 */  lw         $a0, 0x0($s3)
/* 1A8DB0 80396D30 1080000B */  beqz       $a0, .L80396D60_ovl8
/* 1A8DB4 80396D34 00118100 */   sll       $s0, $s1, 4
/* 1A8DB8 80396D38 3C05803B */  lui        $a1, %hi(D_803A9286)
/* 1A8DBC 80396D3C 00B22821 */  addu       $a1, $a1, $s2
/* 1A8DC0 80396D40 84A59286 */  lh         $a1, %lo(D_803A9286)($a1)
/* 1A8DC4 80396D44 3C06803B */  lui        $a2, %hi(D_803A9288)
/* 1A8DC8 80396D48 00D23021 */  addu       $a2, $a2, $s2
/* 1A8DCC 80396D4C 84C69288 */  lh         $a2, %lo(D_803A9288)($a2)
/* 1A8DD0 80396D50 0C0E5A47 */  jal        func_8039691C
/* 1A8DD4 80396D54 00003821 */   addu      $a3, $zero, $zero
/* 1A8DD8 80396D58 080E5B95 */  j          .L80396E54_ovl8
/* 1A8DDC 80396D5C A2800000 */   sb        $zero, 0x0($s4)
.L80396D60_ovl8:
/* 1A8DE0 80396D60 3C02803A */  lui        $v0, %hi(D_803A1580)
/* 1A8DE4 80396D64 00431021 */  addu       $v0, $v0, $v1
/* 1A8DE8 80396D68 94421580 */  lhu        $v0, %lo(D_803A1580)($v0)
/* 1A8DEC 80396D6C 3C01803B */  lui        $at, %hi(D_803A9228)
/* 1A8DF0 80396D70 00300821 */  addu       $at, $at, $s0
/* 1A8DF4 80396D74 A4229228 */  sh         $v0, %lo(D_803A9228)($at)
/* 1A8DF8 80396D78 3C02803A */  lui        $v0, %hi(D_803A1582)
/* 1A8DFC 80396D7C 00431021 */  addu       $v0, $v0, $v1
/* 1A8E00 80396D80 94421582 */  lhu        $v0, %lo(D_803A1582)($v0)
/* 1A8E04 80396D84 3C01803B */  lui        $at, %hi(D_803A922A)
/* 1A8E08 80396D88 00300821 */  addu       $at, $at, $s0
/* 1A8E0C 80396D8C A422922A */  sh         $v0, %lo(D_803A922A)($at)
/* 1A8E10 80396D90 3C02803B */  lui        $v0, %hi(D_803A9284)
/* 1A8E14 80396D94 00521021 */  addu       $v0, $v0, $s2
/* 1A8E18 80396D98 90429284 */  lbu        $v0, %lo(D_803A9284)($v0)
/* 1A8E1C 80396D9C 3C01803B */  lui        $at, %hi(D_803A922C)
/* 1A8E20 80396DA0 00300821 */  addu       $at, $at, $s0
/* 1A8E24 80396DA4 A022922C */  sb         $v0, %lo(D_803A922C)($at)
/* 1A8E28 80396DA8 3C02803B */  lui        $v0, %hi(D_803A928A)
/* 1A8E2C 80396DAC 00521021 */  addu       $v0, $v0, $s2
/* 1A8E30 80396DB0 9042928A */  lbu        $v0, %lo(D_803A928A)($v0)
/* 1A8E34 80396DB4 3C01803B */  lui        $at, %hi(D_803A922D)
/* 1A8E38 80396DB8 00300821 */  addu       $at, $at, $s0
/* 1A8E3C 80396DBC A022922D */  sb         $v0, %lo(D_803A922D)($at)
/* 1A8E40 80396DC0 3C02803B */  lui        $v0, %hi(D_803A9286)
/* 1A8E44 80396DC4 00521021 */  addu       $v0, $v0, $s2
/* 1A8E48 80396DC8 94429286 */  lhu        $v0, %lo(D_803A9286)($v0)
/* 1A8E4C 80396DCC 001188C0 */  sll        $s1, $s1, 3
/* 1A8E50 80396DD0 3C01803B */  lui        $at, %hi(D_803A922E)
/* 1A8E54 80396DD4 00300821 */  addu       $at, $at, $s0
/* 1A8E58 80396DD8 A422922E */  sh         $v0, %lo(D_803A922E)($at)
/* 1A8E5C 80396DDC 3C03803B */  lui        $v1, %hi(D_803A9288)
/* 1A8E60 80396DE0 00721821 */  addu       $v1, $v1, $s2
/* 1A8E64 80396DE4 94639288 */  lhu        $v1, %lo(D_803A9288)($v1)
/* 1A8E68 80396DE8 3C02803B */  lui        $v0, %hi(D_803A9200)
/* 1A8E6C 80396DEC 24429200 */  addiu      $v0, $v0, %lo(D_803A9200)
/* 1A8E70 80396DF0 02228821 */  addu       $s1, $s1, $v0
/* 1A8E74 80396DF4 3C01803B */  lui        $at, %hi(D_803A9232)
/* 1A8E78 80396DF8 00300821 */  addu       $at, $at, $s0
/* 1A8E7C 80396DFC A4209232 */  sh         $zero, %lo(D_803A9232)($at)
/* 1A8E80 80396E00 3C01803B */  lui        $at, %hi(D_803A9234)
/* 1A8E84 80396E04 00300821 */  addu       $at, $at, $s0
/* 1A8E88 80396E08 AC339234 */  sw         $s3, %lo(D_803A9234)($at)
/* 1A8E8C 80396E0C 3C01803B */  lui        $at, %hi(D_803A9230)
/* 1A8E90 80396E10 00300821 */  addu       $at, $at, $s0
/* 1A8E94 80396E14 A4239230 */  sh         $v1, %lo(D_803A9230)($at)
/* 1A8E98 80396E18 0C025C49 */  jal        func_80097124
/* 1A8E9C 80396E1C 02202021 */   addu      $a0, $s1, $zero
/* 1A8EA0 80396E20 02202021 */  addu       $a0, $s1, $zero
/* 1A8EA4 80396E24 3C05803B */  lui        $a1, %hi(D_803A9228)
/* 1A8EA8 80396E28 24A59228 */  addiu      $a1, $a1, %lo(D_803A9228)
/* 1A8EAC 80396E2C 0C025C4C */  jal        func_80097130
/* 1A8EB0 80396E30 02052821 */   addu      $a1, $s0, $a1
/* 1A8EB4 80396E34 3C048039 */  lui        $a0, %hi(D_80395500)
/* 1A8EB8 80396E38 24845500 */  addiu      $a0, $a0, %lo(D_80395500)
/* 1A8EBC 80396E3C 02202821 */  addu       $a1, $s1, $zero
/* 1A8EC0 80396E40 2406012C */  addiu      $a2, $zero, 0x12C
/* 1A8EC4 80396E44 0C025D06 */  jal        func_80097418
/* 1A8EC8 80396E48 24070001 */   addiu     $a3, $zero, 0x1
/* 1A8ECC 80396E4C AE620000 */  sw         $v0, 0x0($s3)
.L80396E50_ovl8:
/* 1A8ED0 80396E50 A2800000 */  sb         $zero, 0x0($s4)
.L80396E54_ovl8:
/* 1A8ED4 80396E54 3C02803B */  lui        $v0, %hi(D_803A9278)
/* 1A8ED8 80396E58 94429278 */  lhu        $v0, %lo(D_803A9278)($v0)
/* 1A8EDC 80396E5C 2442FFFF */  addiu      $v0, $v0, -0x1
/* 1A8EE0 80396E60 3C01803B */  lui        $at, %hi(D_803A9278)
/* 1A8EE4 80396E64 A4229278 */  sh         $v0, %lo(D_803A9278)($at)
/* 1A8EE8 80396E68 2694000C */  addiu      $s4, $s4, 0xC
.L80396E6C_ovl8:
/* 1A8EEC 80396E6C 3C02803B */  lui        $v0, %hi(D_803A9370)
/* 1A8EF0 80396E70 24429370 */  addiu      $v0, $v0, %lo(D_803A9370)
/* 1A8EF4 80396E74 0282102A */  slt        $v0, $s4, $v0
/* 1A8EF8 80396E78 1440FF98 */  bnez       $v0, .L80396CDC_ovl8
/* 1A8EFC 80396E7C 2652000C */   addiu     $s2, $s2, 0xC
/* 1A8F00 80396E80 3C02803B */  lui        $v0, %hi(D_803A9370)
/* 1A8F04 80396E84 94429370 */  lhu        $v0, %lo(D_803A9370)($v0)
/* 1A8F08 80396E88 24420001 */  addiu      $v0, $v0, 0x1
/* 1A8F0C 80396E8C 3C01803B */  lui        $at, %hi(D_803A9370)
/* 1A8F10 80396E90 A4229370 */  sh         $v0, %lo(D_803A9370)($at)
/* 1A8F14 80396E94 8FBF0028 */  lw         $ra, 0x28($sp)
/* 1A8F18 80396E98 8FB50024 */  lw         $s5, 0x24($sp)
/* 1A8F1C 80396E9C 8FB40020 */  lw         $s4, 0x20($sp)
/* 1A8F20 80396EA0 8FB3001C */  lw         $s3, 0x1C($sp)
/* 1A8F24 80396EA4 8FB20018 */  lw         $s2, 0x18($sp)
/* 1A8F28 80396EA8 8FB10014 */  lw         $s1, 0x14($sp)
/* 1A8F2C 80396EAC 8FB00010 */  lw         $s0, 0x10($sp)
/* 1A8F30 80396EB0 27BD0030 */  addiu      $sp, $sp, 0x30
/* 1A8F34 80396EB4 03E00008 */  jr         $ra
/* 1A8F38 80396EB8 00000000 */   nop
.size func_80396CA8, . - func_80396CA8

glabel func_80396EBC
/* 1A8F3C 80396EBC 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1A8F40 80396EC0 AFB20018 */  sw         $s2, 0x18($sp)
/* 1A8F44 80396EC4 00809021 */  addu       $s2, $a0, $zero
/* 1A8F48 80396EC8 AFBF001C */  sw         $ra, 0x1C($sp)
/* 1A8F4C 80396ECC AFB10014 */  sw         $s1, 0x14($sp)
/* 1A8F50 80396ED0 AFB00010 */  sw         $s0, 0x10($sp)
/* 1A8F54 80396ED4 92430005 */  lbu        $v1, 0x5($s2)
/* 1A8F58 80396ED8 28620002 */  slti       $v0, $v1, 0x2
/* 1A8F5C 80396EDC 14400024 */  bnez       $v0, .L80396F70_ovl8
/* 1A8F60 80396EE0 00031600 */   sll       $v0, $v1, 24
/* 1A8F64 80396EE4 24100002 */  addiu      $s0, $zero, 0x2
/* 1A8F68 80396EE8 3C11803B */  lui        $s1, %hi(D_803B3E40)
/* 1A8F6C 80396EEC 26313E40 */  addiu      $s1, $s1, %lo(D_803B3E40)
.L80396EF0_ovl8:
/* 1A8F70 80396EF0 8E240000 */  lw         $a0, 0x0($s1)
/* 1A8F74 80396EF4 0C0E5ACB */  jal        func_80396B2C
/* 1A8F78 80396EF8 00000000 */   nop
/* 1A8F7C 80396EFC 9243000A */  lbu        $v1, 0xA($s2)
/* 1A8F80 80396F00 54430006 */  bnel       $v0, $v1, .L80396F1C_ovl8
/* 1A8F84 80396F04 26100001 */   addiu     $s0, $s0, 0x1
/* 1A8F88 80396F08 9242000B */  lbu        $v0, 0xB($s2)
/* 1A8F8C 80396F0C 10400016 */  beqz       $v0, .L80396F68_ovl8
/* 1A8F90 80396F10 00101600 */   sll       $v0, $s0, 24
/* 1A8F94 80396F14 080E5BDD */  j          .L80396F74_ovl8
/* 1A8F98 80396F18 00021603 */   sra       $v0, $v0, 24
.L80396F1C_ovl8:
/* 1A8F9C 80396F1C 2A020005 */  slti       $v0, $s0, 0x5
/* 1A8FA0 80396F20 1440FFF3 */  bnez       $v0, .L80396EF0_ovl8
/* 1A8FA4 80396F24 26310004 */   addiu     $s1, $s1, 0x4
/* 1A8FA8 80396F28 3C02803B */  lui        $v0, %hi(D_803B3E40)
/* 1A8FAC 80396F2C 8C423E40 */  lw         $v0, %lo(D_803B3E40)($v0)
/* 1A8FB0 80396F30 10400010 */  beqz       $v0, .L80396F74_ovl8
/* 1A8FB4 80396F34 24020002 */   addiu     $v0, $zero, 0x2
/* 1A8FB8 80396F38 3C02803B */  lui        $v0, %hi(D_803B3E44)
/* 1A8FBC 80396F3C 8C423E44 */  lw         $v0, %lo(D_803B3E44)($v0)
/* 1A8FC0 80396F40 14400003 */  bnez       $v0, .L80396F50_ovl8
/* 1A8FC4 80396F44 00000000 */   nop
/* 1A8FC8 80396F48 080E5BDD */  j          .L80396F74_ovl8
/* 1A8FCC 80396F4C 24020003 */   addiu     $v0, $zero, 0x3
.L80396F50_ovl8:
/* 1A8FD0 80396F50 3C02803B */  lui        $v0, %hi(D_803B3E48)
/* 1A8FD4 80396F54 8C423E48 */  lw         $v0, %lo(D_803B3E48)($v0)
/* 1A8FD8 80396F58 0002102B */  sltu       $v0, $zero, $v0
/* 1A8FDC 80396F5C 00021023 */  negu       $v0, $v0
/* 1A8FE0 80396F60 080E5BDD */  j          .L80396F74_ovl8
/* 1A8FE4 80396F64 34420004 */   ori       $v0, $v0, 0x4
.L80396F68_ovl8:
/* 1A8FE8 80396F68 080E5BDD */  j          .L80396F74_ovl8
/* 1A8FEC 80396F6C 2402FFFF */   addiu     $v0, $zero, -0x1
.L80396F70_ovl8:
/* 1A8FF0 80396F70 00021603 */  sra        $v0, $v0, 24
.L80396F74_ovl8:
/* 1A8FF4 80396F74 8FBF001C */  lw         $ra, 0x1C($sp)
/* 1A8FF8 80396F78 8FB20018 */  lw         $s2, 0x18($sp)
/* 1A8FFC 80396F7C 8FB10014 */  lw         $s1, 0x14($sp)
/* 1A9000 80396F80 8FB00010 */  lw         $s0, 0x10($sp)
/* 1A9004 80396F84 27BD0020 */  addiu      $sp, $sp, 0x20
/* 1A9008 80396F88 03E00008 */  jr         $ra
/* 1A900C 80396F8C 00000000 */   nop
.size func_80396EBC, . - func_80396EBC

glabel func_80396F90
/* 1A9010 80396F90 00005021 */  addu       $t2, $zero, $zero
/* 1A9014 80396F94 93AD0017 */  lbu        $t5, 0x17($sp)
/* 1A9018 80396F98 3C02803B */  lui        $v0, %hi(D_803A9372)
/* 1A901C 80396F9C 94429372 */  lhu        $v0, %lo(D_803A9372)($v0)
/* 1A9020 80396FA0 97AE0012 */  lhu        $t6, 0x12($sp)
/* 1A9024 80396FA4 93AC001B */  lbu        $t4, 0x1B($sp)
/* 1A9028 80396FA8 01A21007 */  srav       $v0, $v0, $t5
/* 1A902C 80396FAC 30420001 */  andi       $v0, $v0, 0x1
/* 1A9030 80396FB0 10400062 */  beqz       $v0, .L8039713C_ovl8
/* 1A9034 80396FB4 2409FFFF */   addiu     $t1, $zero, -0x1
/* 1A9038 80396FB8 00004021 */  addu       $t0, $zero, $zero
/* 1A903C 80396FBC 240B0001 */  addiu      $t3, $zero, 0x1
/* 1A9040 80396FC0 00001821 */  addu       $v1, $zero, $zero
.L80396FC4_ovl8:
/* 1A9044 80396FC4 3C02803B */  lui        $v0, %hi(D_803A9280)
/* 1A9048 80396FC8 00431021 */  addu       $v0, $v0, $v1
/* 1A904C 80396FCC 90429280 */  lbu        $v0, %lo(D_803A9280)($v0)
/* 1A9050 80396FD0 50400008 */  beql       $v0, $zero, .L80396FF4_ovl8
/* 1A9054 80396FD4 01004821 */   addu      $t1, $t0, $zero
/* 1A9058 80396FD8 3C02803B */  lui        $v0, %hi(D_803A928B)
/* 1A905C 80396FDC 00431021 */  addu       $v0, $v0, $v1
/* 1A9060 80396FE0 9042928B */  lbu        $v0, %lo(D_803A928B)($v0)
/* 1A9064 80396FE4 504B0003 */  beql       $v0, $t3, .L80396FF4_ovl8
/* 1A9068 80396FE8 240A0001 */   addiu     $t2, $zero, 0x1
/* 1A906C 80396FEC 080E5BFE */  j          .L80396FF8_ovl8
/* 1A9070 80396FF0 25080001 */   addiu     $t0, $t0, 0x1
.L80396FF4_ovl8:
/* 1A9074 80396FF4 25080001 */  addiu      $t0, $t0, 0x1
.L80396FF8_ovl8:
/* 1A9078 80396FF8 29020014 */  slti       $v0, $t0, 0x14
/* 1A907C 80396FFC 1440FFF1 */  bnez       $v0, .L80396FC4_ovl8
/* 1A9080 80397000 2463000C */   addiu     $v1, $v1, 0xC
/* 1A9084 80397004 2402FFFF */  addiu      $v0, $zero, -0x1
/* 1A9088 80397008 1122004C */  beq        $t1, $v0, .L8039713C_ovl8
/* 1A908C 8039700C 2D820001 */   sltiu     $v0, $t4, 0x1
/* 1A9090 80397010 01421024 */  and        $v0, $t2, $v0
/* 1A9094 80397014 14400049 */  bnez       $v0, .L8039713C_ovl8
/* 1A9098 80397018 3082FFFF */   andi      $v0, $a0, 0xFFFF
/* 1A909C 8039701C 3C014040 */  lui        $at, (0x40400000 >> 16)
/* 1A90A0 80397020 44810000 */  mtc1       $at, $f0
/* 1A90A4 80397024 00000000 */  nop
/* 1A90A8 80397028 44821000 */  mtc1       $v0, $f2
/* 1A90AC 8039702C 00000000 */  nop
/* 1A90B0 80397030 468010A0 */  cvt.s.w    $f2, $f2
/* 1A90B4 80397034 46001082 */  mul.s      $f2, $f2, $f0
/* 1A90B8 80397038 00091840 */  sll        $v1, $t1, 1
/* 1A90BC 8039703C 00691821 */  addu       $v1, $v1, $t1
/* 1A90C0 80397040 00031880 */  sll        $v1, $v1, 2
/* 1A90C4 80397044 24020001 */  addiu      $v0, $zero, 0x1
/* 1A90C8 80397048 3C01803B */  lui        $at, %hi(D_803A9280)
/* 1A90CC 8039704C 00230821 */  addu       $at, $at, $v1
/* 1A90D0 80397050 A0229280 */  sb         $v0, %lo(D_803A9280)($at)
/* 1A90D4 80397054 3C018015 */  lui        $at, %hi(D_80149F90)
/* 1A90D8 80397058 C4209F90 */  lwc1       $f0, %lo(D_80149F90)($at)
/* 1A90DC 8039705C 46800020 */  cvt.s.w    $f0, $f0
/* 1A90E0 80397060 46001083 */  div.s      $f2, $f2, $f0
/* 1A90E4 80397064 3C02803B */  lui        $v0, %hi(D_803A9370)
/* 1A90E8 80397068 94429370 */  lhu        $v0, %lo(D_803A9370)($v0)
/* 1A90EC 8039706C 44820000 */  mtc1       $v0, $f0
/* 1A90F0 80397070 00000000 */  nop
/* 1A90F4 80397074 46800020 */  cvt.s.w    $f0, $f0
/* 1A90F8 80397078 46020080 */  add.s      $f2, $f0, $f2
/* 1A90FC 8039707C 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1A9100 80397080 44810000 */  mtc1       $at, $f0
/* 1A9104 80397084 00000000 */  nop
/* 1A9108 80397088 4602003E */  c.le.s     $f0, $f2
/* 1A910C 8039708C 00000000 */  nop
/* 1A9110 80397090 00000000 */  nop
/* 1A9114 80397094 45010006 */  bc1t       .L803970B0_ovl8
/* 1A9118 80397098 00604021 */   addu      $t0, $v1, $zero
/* 1A911C 8039709C 4600100D */  trunc.w.s  $f0, $f2
/* 1A9120 803970A0 44040000 */  mfc1       $a0, $f0
/* 1A9124 803970A4 00000000 */  nop
/* 1A9128 803970A8 080E5C33 */  j          .L803970CC_ovl8
/* 1A912C 803970AC 00091040 */   sll       $v0, $t1, 1
.L803970B0_ovl8:
/* 1A9130 803970B0 46001001 */  sub.s      $f0, $f2, $f0
/* 1A9134 803970B4 4600008D */  trunc.w.s  $f2, $f0
/* 1A9138 803970B8 44041000 */  mfc1       $a0, $f2
/* 1A913C 803970BC 00000000 */  nop
/* 1A9140 803970C0 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1A9144 803970C4 00822025 */  or         $a0, $a0, $v0
/* 1A9148 803970C8 00091040 */  sll        $v0, $t1, 1
.L803970CC_ovl8:
/* 1A914C 803970CC 00491021 */  addu       $v0, $v0, $t1
/* 1A9150 803970D0 00021080 */  sll        $v0, $v0, 2
/* 1A9154 803970D4 3C01803B */  lui        $at, %hi(D_803A9284)
/* 1A9158 803970D8 00220821 */  addu       $at, $at, $v0
/* 1A915C 803970DC A0259284 */  sb         $a1, %lo(D_803A9284)($at)
/* 1A9160 803970E0 3C01803B */  lui        $at, %hi(D_803A9285)
/* 1A9164 803970E4 00220821 */  addu       $at, $at, $v0
/* 1A9168 803970E8 A0269285 */  sb         $a2, %lo(D_803A9285)($at)
/* 1A916C 803970EC 3C01803B */  lui        $at, %hi(D_803A928A)
/* 1A9170 803970F0 00220821 */  addu       $at, $at, $v0
/* 1A9174 803970F4 A02D928A */  sb         $t5, %lo(D_803A928A)($at)
/* 1A9178 803970F8 3C01803B */  lui        $at, %hi(D_803A928B)
/* 1A917C 803970FC 00220821 */  addu       $at, $at, $v0
/* 1A9180 80397100 A02C928B */  sb         $t4, %lo(D_803A928B)($at)
/* 1A9184 80397104 3C03803B */  lui        $v1, %hi(D_803A9278)
/* 1A9188 80397108 94639278 */  lhu        $v1, %lo(D_803A9278)($v1)
/* 1A918C 8039710C 3C01803B */  lui        $at, %hi(D_803A9282)
/* 1A9190 80397110 00280821 */  addu       $at, $at, $t0
/* 1A9194 80397114 A4249282 */  sh         $a0, %lo(D_803A9282)($at)
/* 1A9198 80397118 3C01803B */  lui        $at, %hi(D_803A9286)
/* 1A919C 8039711C 00220821 */  addu       $at, $at, $v0
/* 1A91A0 80397120 A4279286 */  sh         $a3, %lo(D_803A9286)($at)
/* 1A91A4 80397124 3C01803B */  lui        $at, %hi(D_803A9288)
/* 1A91A8 80397128 00220821 */  addu       $at, $at, $v0
/* 1A91AC 8039712C A42E9288 */  sh         $t6, %lo(D_803A9288)($at)
/* 1A91B0 80397130 24630001 */  addiu      $v1, $v1, 0x1
/* 1A91B4 80397134 3C01803B */  lui        $at, %hi(D_803A9278)
/* 1A91B8 80397138 A4239278 */  sh         $v1, %lo(D_803A9278)($at)
.L8039713C_ovl8:
/* 1A91BC 8039713C 03E00008 */  jr         $ra
/* 1A91C0 80397140 00000000 */   nop
.size func_80396F90, . - func_80396F90

glabel func_80397144
/* 1A91C4 80397144 3C02803B */  lui        $v0, %hi(D_803A9372)
/* 1A91C8 80397148 94429372 */  lhu        $v0, %lo(D_803A9372)($v0)
/* 1A91CC 8039714C 00042027 */  nor        $a0, $zero, $a0
/* 1A91D0 80397150 00441024 */  and        $v0, $v0, $a0
/* 1A91D4 80397154 3C01803B */  lui        $at, %hi(D_803A9372)
/* 1A91D8 80397158 A4229372 */  sh         $v0, %lo(D_803A9372)($at)
/* 1A91DC 8039715C 03E00008 */  jr         $ra
/* 1A91E0 80397160 00000000 */   nop
.size func_80397144, . - func_80397144

glabel func_80397164
/* 1A91E4 80397164 3C02803B */  lui        $v0, %hi(D_803A9372)
/* 1A91E8 80397168 94429372 */  lhu        $v0, %lo(D_803A9372)($v0)
/* 1A91EC 8039716C 00441025 */  or         $v0, $v0, $a0
/* 1A91F0 80397170 3C01803B */  lui        $at, %hi(D_803A9372)
/* 1A91F4 80397174 A4229372 */  sh         $v0, %lo(D_803A9372)($at)
/* 1A91F8 80397178 03E00008 */  jr         $ra
/* 1A91FC 8039717C 00000000 */   nop
.size func_80397164, . - func_80397164

glabel func_80397180
/* 1A9200 80397180 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 1A9204 80397184 AFBF0010 */  sw         $ra, 0x10($sp)
/* 1A9208 80397188 3C048039 */  lui        $a0, %hi(D_80397230)
/* 1A920C 8039718C 24847230 */  addiu      $a0, $a0, %lo(D_80397230)
/* 1A9210 80397190 0C025D6B */  jal        func_800975AC
/* 1A9214 80397194 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9218 80397198 3C04803A */  lui        $a0, %hi(D_803981A0)
/* 1A921C 8039719C 248481A0 */  addiu      $a0, $a0, %lo(D_803981A0)
/* 1A9220 803971A0 0C025D6B */  jal        func_800975AC
/* 1A9224 803971A4 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9228 803971A8 3C04803A */  lui        $a0, %hi(D_803987C0)
/* 1A922C 803971AC 248487C0 */  addiu      $a0, $a0, %lo(D_803987C0)
/* 1A9230 803971B0 0C025D6B */  jal        func_800975AC
/* 1A9234 803971B4 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9238 803971B8 3C04803A */  lui        $a0, %hi(D_80399408)
/* 1A923C 803971BC 24849408 */  addiu      $a0, $a0, %lo(D_80399408)
/* 1A9240 803971C0 0C025D6B */  jal        func_800975AC
/* 1A9244 803971C4 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9248 803971C8 3C04803A */  lui        $a0, %hi(D_80399D30)
/* 1A924C 803971CC 24849D30 */  addiu      $a0, $a0, %lo(D_80399D30)
/* 1A9250 803971D0 0C025D6B */  jal        func_800975AC
/* 1A9254 803971D4 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9258 803971D8 3C04803A */  lui        $a0, %hi(D_8039A840)
/* 1A925C 803971DC 2484A840 */  addiu      $a0, $a0, %lo(D_8039A840)
/* 1A9260 803971E0 0C025D6B */  jal        func_800975AC
/* 1A9264 803971E4 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9268 803971E8 3C04803A */  lui        $a0, %hi(D_8039B330)
/* 1A926C 803971EC 2484B330 */  addiu      $a0, $a0, %lo(D_8039B330)
/* 1A9270 803971F0 0C025D6B */  jal        func_800975AC
/* 1A9274 803971F4 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9278 803971F8 3C04803A */  lui        $a0, %hi(D_8039BE40)
/* 1A927C 803971FC 2484BE40 */  addiu      $a0, $a0, %lo(D_8039BE40)
/* 1A9280 80397200 0C025D6B */  jal        func_800975AC
/* 1A9284 80397204 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9288 80397208 3C04803A */  lui        $a0, %hi(D_8039C390)
/* 1A928C 8039720C 2484C390 */  addiu      $a0, $a0, %lo(D_8039C390)
/* 1A9290 80397210 0C025D6B */  jal        func_800975AC
/* 1A9294 80397214 24050001 */   addiu     $a1, $zero, 0x1
/* 1A9298 80397218 8FBF0010 */  lw         $ra, 0x10($sp)
/* 1A929C 8039721C 27BD0018 */  addiu      $sp, $sp, 0x18
/* 1A92A0 80397220 03E00008 */  jr         $ra
/* 1A92A4 80397224 00000000 */   nop
/* 1A92A8 80397228 00000000 */  nop
/* 1A92AC 8039722C 00000000 */  nop
.size func_80397180, . - func_80397180
