.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.18.0 */

glabel func_80398730
/* 1AA7B0 80398730 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1AA7B4 80398734 3C03803B */  lui        $v1, %hi(D_803A9380)
/* 1AA7B8 80398738 24639380 */  addiu      $v1, $v1, %lo(D_803A9380)
/* 1AA7BC 8039873C 3C02803A */  lui        $v0, %hi(D_803A1768)
/* 1AA7C0 80398740 24421768 */  addiu      $v0, $v0, %lo(D_803A1768)
/* 1AA7C4 80398744 AFB10014 */  sw         $s1, 0x14($sp)
/* 1AA7C8 80398748 24110001 */  addiu      $s1, $zero, 0x1
/* 1AA7CC 8039874C AFB20018 */  sw         $s2, 0x18($sp)
/* 1AA7D0 80398750 24720004 */  addiu      $s2, $v1, 0x4
/* 1AA7D4 80398754 AFB00010 */  sw         $s0, 0x10($sp)
/* 1AA7D8 80398758 3C10803B */  lui        $s0, %hi(D_803A9BC0)
/* 1AA7DC 8039875C 26109BC0 */  addiu      $s0, $s0, %lo(D_803A9BC0)
/* 1AA7E0 80398760 AFBF001C */  sw         $ra, 0x1C($sp)
/* 1AA7E4 80398764 AC620000 */  sw         $v0, 0x0($v1)
.L80398768_ovl8:
/* 1AA7E8 80398768 02002021 */  addu       $a0, $s0, $zero
/* 1AA7EC 8039876C 3C05001E */  lui        $a1, %hi(Image_ROM_START)
/* 1AA7F0 80398770 24A59000 */  addiu      $a1, $a1, %lo(Image_ROM_START)
/* 1AA7F4 80398774 3C06800D */  lui        $a2, %hi(D_800D6AD0)
/* 1AA7F8 80398778 24C66AD0 */  addiu      $a2, $a2, %lo(D_800D6AD0)
/* 1AA7FC 8039877C 0C0264C3 */  jal        func_8009930C
/* 1AA800 80398780 2627085A */   addiu     $a3, $s1, 0x85A
/* 1AA804 80398784 AE500000 */  sw         $s0, 0x0($s2)
/* 1AA808 80398788 26520004 */  addiu      $s2, $s2, 0x4
/* 1AA80C 8039878C 26310001 */  addiu      $s1, $s1, 0x1
/* 1AA810 80398790 2A22000A */  slti       $v0, $s1, 0xA
/* 1AA814 80398794 1440FFF4 */  bnez       $v0, .L80398768_ovl8
/* 1AA818 80398798 26100810 */   addiu     $s0, $s0, 0x810
/* 1AA81C 8039879C 8FBF001C */  lw         $ra, 0x1C($sp)
/* 1AA820 803987A0 8FB20018 */  lw         $s2, 0x18($sp)
/* 1AA824 803987A4 8FB10014 */  lw         $s1, 0x14($sp)
/* 1AA828 803987A8 8FB00010 */  lw         $s0, 0x10($sp)
/* 1AA82C 803987AC 27BD0020 */  addiu      $sp, $sp, 0x20
/* 1AA830 803987B0 03E00008 */  jr         $ra
/* 1AA834 803987B4 00000000 */   nop
.size func_80398730, . - func_80398730

glabel func_803987B8
/* 1AA838 803987B8 03E00008 */  jr         $ra
/* 1AA83C 803987BC 00000000 */   nop
.size func_803987B8, . - func_803987B8

glabel D_803987C0
/* 1AA840 803987C0 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1AA844 803987C4 AFB00010 */  sw         $s0, 0x10($sp)
/* 1AA848 803987C8 00808021 */  addu       $s0, $a0, $zero
/* 1AA84C 803987CC AFBF001C */  sw         $ra, 0x1C($sp)
/* 1AA850 803987D0 AFB20018 */  sw         $s2, 0x18($sp)
/* 1AA854 803987D4 AFB10014 */  sw         $s1, 0x14($sp)
/* 1AA858 803987D8 9603001C */  lhu        $v1, 0x1C($s0)
/* 1AA85C 803987DC 24120001 */  addiu      $s2, $zero, 0x1
/* 1AA860 803987E0 10720033 */  beq        $v1, $s2, .L803988B0_ovl8
/* 1AA864 803987E4 28620002 */   slti      $v0, $v1, 0x2
/* 1AA868 803987E8 50400005 */  beql       $v0, $zero, .L80398800_ovl8
/* 1AA86C 803987EC 3402FFFF */   ori       $v0, $zero, 0xFFFF
/* 1AA870 803987F0 10600007 */  beqz       $v1, .L80398810_ovl8
/* 1AA874 803987F4 00000000 */   nop
/* 1AA878 803987F8 080E6253 */  j          .L8039894C_ovl8
/* 1AA87C 803987FC 00000000 */   nop
.L80398800_ovl8:
/* 1AA880 80398800 10620033 */  beq        $v1, $v0, .L803988D0_ovl8
/* 1AA884 80398804 00000000 */   nop
/* 1AA888 80398808 080E6253 */  j          .L8039894C_ovl8
/* 1AA88C 8039880C 00000000 */   nop
.L80398810_ovl8:
/* 1AA890 80398810 3C03803B */  lui        $v1, %hi(D_803B3E34)
/* 1AA894 80398814 8C633E34 */  lw         $v1, %lo(D_803B3E34)($v1)
/* 1AA898 80398818 00031100 */  sll        $v0, $v1, 4
/* 1AA89C 8039881C 00431023 */  subu       $v0, $v0, $v1
/* 1AA8A0 80398820 8E03000C */  lw         $v1, 0xC($s0)
/* 1AA8A4 80398824 000210C0 */  sll        $v0, $v0, 3
/* 1AA8A8 80398828 10720010 */  beq        $v1, $s2, .L8039886C_ovl8
/* 1AA8AC 8039882C 24510060 */   addiu     $s1, $v0, 0x60
/* 1AA8B0 80398830 28620002 */  slti       $v0, $v1, 0x2
/* 1AA8B4 80398834 50400005 */  beql       $v0, $zero, .L8039884C_ovl8
/* 1AA8B8 80398838 24020002 */   addiu     $v0, $zero, 0x2
/* 1AA8BC 8039883C 10600007 */  beqz       $v1, .L8039885C_ovl8
/* 1AA8C0 80398840 00000000 */   nop
/* 1AA8C4 80398844 080E6225 */  j          .L80398894_ovl8
/* 1AA8C8 80398848 00000000 */   nop
.L8039884C_ovl8:
/* 1AA8CC 8039884C 1062000B */  beq        $v1, $v0, .L8039887C_ovl8
/* 1AA8D0 80398850 00000000 */   nop
/* 1AA8D4 80398854 080E6225 */  j          .L80398894_ovl8
/* 1AA8D8 80398858 00000000 */   nop
.L8039885C_ovl8:
/* 1AA8DC 8039885C 0C032663 */  jal        func_800C998C
/* 1AA8E0 80398860 02202021 */   addu      $a0, $s1, $zero
/* 1AA8E4 80398864 080E6222 */  j          .L80398888_ovl8
/* 1AA8E8 80398868 AE020014 */   sw        $v0, 0x14($s0)
.L8039886C_ovl8:
/* 1AA8EC 8039886C 0C025E63 */  jal        func_8009798C
/* 1AA8F0 80398870 02202021 */   addu      $a0, $s1, $zero
/* 1AA8F4 80398874 080E6222 */  j          .L80398888_ovl8
/* 1AA8F8 80398878 AE020014 */   sw        $v0, 0x14($s0)
.L8039887C_ovl8:
/* 1AA8FC 8039887C 0C026127 */  jal        func_8009849C
/* 1AA900 80398880 02202021 */   addu      $a0, $s1, $zero
/* 1AA904 80398884 AE020014 */  sw         $v0, 0x14($s0)
.L80398888_ovl8:
/* 1AA908 80398888 00402021 */  addu       $a0, $v0, $zero
/* 1AA90C 8039888C 0C030134 */  jal        bzero
/* 1AA910 80398890 02202821 */   addu      $a1, $s1, $zero
.L80398894_ovl8:
/* 1AA914 80398894 8E040014 */  lw         $a0, 0x14($s0)
/* 1AA918 80398898 0C0E62E5 */  jal        func_80398B94
/* 1AA91C 8039889C 00000000 */   nop
/* 1AA920 803988A0 00001021 */  addu       $v0, $zero, $zero
/* 1AA924 803988A4 24030001 */  addiu      $v1, $zero, 0x1
/* 1AA928 803988A8 080E6255 */  j          .L80398954_ovl8
/* 1AA92C 803988AC A603001C */   sh        $v1, 0x1C($s0)
.L803988B0_ovl8:
/* 1AA930 803988B0 8E040014 */  lw         $a0, 0x14($s0)
/* 1AA934 803988B4 0C0E634C */  jal        func_80398D30
/* 1AA938 803988B8 00000000 */   nop
/* 1AA93C 803988BC 10400002 */  beqz       $v0, .L803988C8_ovl8
/* 1AA940 803988C0 3402FFFF */   ori       $v0, $zero, 0xFFFF
/* 1AA944 803988C4 A602001C */  sh         $v0, 0x1C($s0)
.L803988C8_ovl8:
/* 1AA948 803988C8 080E6255 */  j          .L80398954_ovl8
/* 1AA94C 803988CC 00001021 */   addu      $v0, $zero, $zero
.L803988D0_ovl8:
/* 1AA950 803988D0 8E040014 */  lw         $a0, 0x14($s0)
/* 1AA954 803988D4 0C0E634A */  jal        func_80398D28
/* 1AA958 803988D8 00000000 */   nop
/* 1AA95C 803988DC 8E03000C */  lw         $v1, 0xC($s0)
/* 1AA960 803988E0 10720010 */  beq        $v1, $s2, .L80398924_ovl8
/* 1AA964 803988E4 28620002 */   slti      $v0, $v1, 0x2
/* 1AA968 803988E8 50400005 */  beql       $v0, $zero, .L80398900_ovl8
/* 1AA96C 803988EC 24020002 */   addiu     $v0, $zero, 0x2
/* 1AA970 803988F0 10600007 */  beqz       $v1, .L80398910_ovl8
/* 1AA974 803988F4 24020001 */   addiu     $v0, $zero, 0x1
/* 1AA978 803988F8 080E6255 */  j          .L80398954_ovl8
/* 1AA97C 803988FC 00000000 */   nop
.L80398900_ovl8:
/* 1AA980 80398900 1062000D */  beq        $v1, $v0, .L80398938_ovl8
/* 1AA984 80398904 24020001 */   addiu     $v0, $zero, 0x1
/* 1AA988 80398908 080E6255 */  j          .L80398954_ovl8
/* 1AA98C 8039890C 00000000 */   nop
.L80398910_ovl8:
/* 1AA990 80398910 8E040014 */  lw         $a0, 0x14($s0)
/* 1AA994 80398914 0C0326A1 */  jal        func_800C9A84
/* 1AA998 80398918 00000000 */   nop
/* 1AA99C 8039891C 080E6255 */  j          .L80398954_ovl8
/* 1AA9A0 80398920 24020001 */   addiu     $v0, $zero, 0x1
.L80398924_ovl8:
/* 1AA9A4 80398924 8E040014 */  lw         $a0, 0x14($s0)
/* 1AA9A8 80398928 0C025EC3 */  jal        func_80097B0C
/* 1AA9AC 8039892C 00000000 */   nop
/* 1AA9B0 80398930 080E6255 */  j          .L80398954_ovl8
/* 1AA9B4 80398934 24020001 */   addiu     $v0, $zero, 0x1
.L80398938_ovl8:
/* 1AA9B8 80398938 8E040014 */  lw         $a0, 0x14($s0)
/* 1AA9BC 8039893C 0C026187 */  jal        func_8009861C
/* 1AA9C0 80398940 00000000 */   nop
/* 1AA9C4 80398944 080E6255 */  j          .L80398954_ovl8
/* 1AA9C8 80398948 24020001 */   addiu     $v0, $zero, 0x1
.L8039894C_ovl8:
/* 1AA9CC 8039894C 0C032934 */  jal        func_800CA4D0
/* 1AA9D0 80398950 00000000 */   nop
.L80398954_ovl8:
/* 1AA9D4 80398954 8FBF001C */  lw         $ra, 0x1C($sp)
/* 1AA9D8 80398958 8FB20018 */  lw         $s2, 0x18($sp)
/* 1AA9DC 8039895C 8FB10014 */  lw         $s1, 0x14($sp)
/* 1AA9E0 80398960 8FB00010 */  lw         $s0, 0x10($sp)
/* 1AA9E4 80398964 27BD0020 */  addiu      $sp, $sp, 0x20
/* 1AA9E8 80398968 03E00008 */  jr         $ra
/* 1AA9EC 8039896C 00000000 */   nop
.size D_803987C0, . - D_803987C0

glabel func_80398970
/* 1AA9F0 80398970 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1AA9F4 80398974 AFB10014 */  sw         $s1, 0x14($sp)
/* 1AA9F8 80398978 00808821 */  addu       $s1, $a0, $zero
/* 1AA9FC 8039897C AFBF0018 */  sw         $ra, 0x18($sp)
/* 1AAA00 80398980 AFB00010 */  sw         $s0, 0x10($sp)
/* 1AAA04 80398984 F7B40020 */  sdc1       $f20, 0x20($sp)
/* 1AAA08 80398988 C6340044 */  lwc1       $f20, 0x44($s1)
/* 1AAA0C 8039898C 00A08021 */  addu       $s0, $a1, $zero
/* 1AAA10 80398990 2404000A */  addiu      $a0, $zero, 0xA
/* 1AAA14 80398994 AE000040 */  sw         $zero, 0x40($s0)
/* 1AAA18 80398998 AE000044 */  sw         $zero, 0x44($s0)
/* 1AAA1C 8039899C 0C02591A */  jal        func_80096468
/* 1AAA20 803989A0 AE000048 */   sw        $zero, 0x48($s0)
/* 1AAA24 803989A4 2442000A */  addiu      $v0, $v0, 0xA
/* 1AAA28 803989A8 A602006C */  sh         $v0, 0x6C($s0)
/* 1AAA2C 803989AC 8602006C */  lh         $v0, 0x6C($s0)
/* 1AAA30 803989B0 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 1AAA34 803989B4 44811000 */  mtc1       $at, $f2
/* 1AAA38 803989B8 00000000 */  nop
/* 1AAA3C 803989BC 44820000 */  mtc1       $v0, $f0
/* 1AAA40 803989C0 00000000 */  nop
/* 1AAA44 803989C4 46800020 */  cvt.s.w    $f0, $f0
/* 1AAA48 803989C8 46001083 */  div.s      $f2, $f2, $f0
/* 1AAA4C 803989CC 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1AAA50 803989D0 44810000 */  mtc1       $at, $f0
/* 1AAA54 803989D4 00000000 */  nop
/* 1AAA58 803989D8 4614003E */  c.le.s     $f0, $f20
/* 1AAA5C 803989DC 00000000 */  nop
/* 1AAA60 803989E0 00000000 */  nop
/* 1AAA64 803989E4 AE000064 */  sw         $zero, 0x64($s0)
/* 1AAA68 803989E8 45010006 */  bc1t       .L80398A04_ovl8
/* 1AAA6C 803989EC E6020068 */   swc1      $f2, 0x68($s0)
/* 1AAA70 803989F0 4600A00D */  trunc.w.s  $f0, $f20
/* 1AAA74 803989F4 44040000 */  mfc1       $a0, $f0
/* 1AAA78 803989F8 00000000 */  nop
/* 1AAA7C 803989FC 080E6287 */  j          .L80398A1C_ovl8
/* 1AAA80 80398A00 00000000 */   nop
.L80398A04_ovl8:
/* 1AAA84 80398A04 4600A001 */  sub.s      $f0, $f20, $f0
/* 1AAA88 80398A08 4600008D */  trunc.w.s  $f2, $f0
/* 1AAA8C 80398A0C 44041000 */  mfc1       $a0, $f2
/* 1AAA90 80398A10 00000000 */  nop
/* 1AAA94 80398A14 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1AAA98 80398A18 00822025 */  or         $a0, $a0, $v0
.L80398A1C_ovl8:
/* 1AAA9C 80398A1C 0C02591A */  jal        func_80096468
/* 1AAAA0 80398A20 3084FFFF */   andi      $a0, $a0, 0xFFFF
/* 1AAAA4 80398A24 0C02592F */  jal        func_800964BC
/* 1AAAA8 80398A28 3044FFFF */   andi      $a0, $v0, 0xFFFF
/* 1AAAAC 80398A2C 3C0142C8 */  lui        $at, (0x42C80000 >> 16)
/* 1AAAB0 80398A30 44811000 */  mtc1       $at, $f2
/* 1AAAB4 80398A34 00000000 */  nop
/* 1AAAB8 80398A38 44820000 */  mtc1       $v0, $f0
/* 1AAABC 80398A3C 00000000 */  nop
/* 1AAAC0 80398A40 46800020 */  cvt.s.w    $f0, $f0
/* 1AAAC4 80398A44 46020003 */  div.s      $f0, $f0, $f2
/* 1AAAC8 80398A48 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1AAACC 80398A4C 44811000 */  mtc1       $at, $f2
/* 1AAAD0 80398A50 00000000 */  nop
/* 1AAAD4 80398A54 4614103E */  c.le.s     $f2, $f20
/* 1AAAD8 80398A58 00000000 */  nop
/* 1AAADC 80398A5C 00000000 */  nop
/* 1AAAE0 80398A60 45010006 */  bc1t       .L80398A7C_ovl8
/* 1AAAE4 80398A64 E600004C */   swc1      $f0, 0x4C($s0)
/* 1AAAE8 80398A68 4600A00D */  trunc.w.s  $f0, $f20
/* 1AAAEC 80398A6C 44040000 */  mfc1       $a0, $f0
/* 1AAAF0 80398A70 00000000 */  nop
/* 1AAAF4 80398A74 080E62A5 */  j          .L80398A94_ovl8
/* 1AAAF8 80398A78 00000000 */   nop
.L80398A7C_ovl8:
/* 1AAAFC 80398A7C 4602A001 */  sub.s      $f0, $f20, $f2
/* 1AAB00 80398A80 4600008D */  trunc.w.s  $f2, $f0
/* 1AAB04 80398A84 44041000 */  mfc1       $a0, $f2
/* 1AAB08 80398A88 00000000 */  nop
/* 1AAB0C 80398A8C 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1AAB10 80398A90 00822025 */  or         $a0, $a0, $v0
.L80398A94_ovl8:
/* 1AAB14 80398A94 0C02591A */  jal        func_80096468
/* 1AAB18 80398A98 3084FFFF */   andi      $a0, $a0, 0xFFFF
/* 1AAB1C 80398A9C 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 1AAB20 80398AA0 44810000 */  mtc1       $at, $f0
/* 1AAB24 80398AA4 00000000 */  nop
/* 1AAB28 80398AA8 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 1AAB2C 80398AAC 44821000 */  mtc1       $v0, $f2
/* 1AAB30 80398AB0 00000000 */  nop
/* 1AAB34 80398AB4 468010A0 */  cvt.s.w    $f2, $f2
/* 1AAB38 80398AB8 46001083 */  div.s      $f2, $f2, $f0
/* 1AAB3C 80398ABC 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1AAB40 80398AC0 44810000 */  mtc1       $at, $f0
/* 1AAB44 80398AC4 00000000 */  nop
/* 1AAB48 80398AC8 4614003E */  c.le.s     $f0, $f20
/* 1AAB4C 80398ACC 00000000 */  nop
/* 1AAB50 80398AD0 00000000 */  nop
/* 1AAB54 80398AD4 45010006 */  bc1t       .L80398AF0_ovl8
/* 1AAB58 80398AD8 E6020050 */   swc1      $f2, 0x50($s0)
/* 1AAB5C 80398ADC 4600A00D */  trunc.w.s  $f0, $f20
/* 1AAB60 80398AE0 44040000 */  mfc1       $a0, $f0
/* 1AAB64 80398AE4 00000000 */  nop
/* 1AAB68 80398AE8 080E62C2 */  j          .L80398B08_ovl8
/* 1AAB6C 80398AEC 00000000 */   nop
.L80398AF0_ovl8:
/* 1AAB70 80398AF0 4600A001 */  sub.s      $f0, $f20, $f0
/* 1AAB74 80398AF4 4600008D */  trunc.w.s  $f2, $f0
/* 1AAB78 80398AF8 44041000 */  mfc1       $a0, $f2
/* 1AAB7C 80398AFC 00000000 */  nop
/* 1AAB80 80398B00 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1AAB84 80398B04 00822025 */  or         $a0, $a0, $v0
.L80398B08_ovl8:
/* 1AAB88 80398B08 0C02591A */  jal        func_80096468
/* 1AAB8C 80398B0C 3084FFFF */   andi      $a0, $a0, 0xFFFF
/* 1AAB90 80398B10 0C02592F */  jal        func_800964BC
/* 1AAB94 80398B14 3044FFFF */   andi      $a0, $v0, 0xFFFF
/* 1AAB98 80398B18 8603006C */  lh         $v1, 0x6C($s0)
/* 1AAB9C 80398B1C C6020050 */  lwc1       $f2, 0x50($s0)
/* 1AABA0 80398B20 44830000 */  mtc1       $v1, $f0
/* 1AABA4 80398B24 00000000 */  nop
/* 1AABA8 80398B28 46800020 */  cvt.s.w    $f0, $f0
/* 1AABAC 80398B2C 46001083 */  div.s      $f2, $f2, $f0
/* 1AABB0 80398B30 3C0142C8 */  lui        $at, (0x42C80000 >> 16)
/* 1AABB4 80398B34 44812000 */  mtc1       $at, $f4
/* 1AABB8 80398B38 00000000 */  nop
/* 1AABBC 80398B3C 44820000 */  mtc1       $v0, $f0
/* 1AABC0 80398B40 00000000 */  nop
/* 1AABC4 80398B44 46800020 */  cvt.s.w    $f0, $f0
/* 1AABC8 80398B48 46040003 */  div.s      $f0, $f0, $f4
/* 1AABCC 80398B4C 8602006C */  lh         $v0, 0x6C($s0)
/* 1AABD0 80398B50 46001087 */  neg.s      $f2, $f2
/* 1AABD4 80398B54 E6000054 */  swc1       $f0, 0x54($s0)
/* 1AABD8 80398B58 E6020058 */  swc1       $f2, 0x58($s0)
/* 1AABDC 80398B5C C6220040 */  lwc1       $f2, 0x40($s1)
/* 1AABE0 80398B60 44820000 */  mtc1       $v0, $f0
/* 1AABE4 80398B64 00000000 */  nop
/* 1AABE8 80398B68 46800020 */  cvt.s.w    $f0, $f0
/* 1AABEC 80398B6C 46001003 */  div.s      $f0, $f2, $f0
/* 1AABF0 80398B70 E602005C */  swc1       $f2, 0x5C($s0)
/* 1AABF4 80398B74 E6000060 */  swc1       $f0, 0x60($s0)
/* 1AABF8 80398B78 8FBF0018 */  lw         $ra, 0x18($sp)
/* 1AABFC 80398B7C 8FB10014 */  lw         $s1, 0x14($sp)
/* 1AAC00 80398B80 8FB00010 */  lw         $s0, 0x10($sp)
/* 1AAC04 80398B84 D7B40020 */  ldc1       $f20, 0x20($sp)
/* 1AAC08 80398B88 27BD0028 */  addiu      $sp, $sp, 0x28
/* 1AAC0C 80398B8C 03E00008 */  jr         $ra
/* 1AAC10 80398B90 00000000 */   nop
.size func_80398970, . - func_80398970

glabel func_80398B94
/* 1AAC14 80398B94 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 1AAC18 80398B98 44811000 */  mtc1       $at, $f2
/* 1AAC1C 80398B9C 00000000 */  nop
/* 1AAC20 80398BA0 3C01803B */  lui        $at, %hi(D_803B3EBC)
/* 1AAC24 80398BA4 C4243EBC */  lwc1       $f4, %lo(D_803B3EBC)($at)
/* 1AAC28 80398BA8 3C01803B */  lui        $at, %hi(D_803B3EB0)
/* 1AAC2C 80398BAC C4263EB0 */  lwc1       $f6, %lo(D_803B3EB0)($at)
/* 1AAC30 80398BB0 3C01803B */  lui        $at, %hi(D_803B3E2C)
/* 1AAC34 80398BB4 C4283E2C */  lwc1       $f8, %lo(D_803B3E2C)($at)
/* 1AAC38 80398BB8 44800000 */  mtc1       $zero, $f0
/* 1AAC3C 80398BBC 00000000 */  nop
/* 1AAC40 80398BC0 27BDFF88 */  addiu      $sp, $sp, -0x78
/* 1AAC44 80398BC4 AFB20070 */  sw         $s2, 0x70($sp)
/* 1AAC48 80398BC8 00809021 */  addu       $s2, $a0, $zero
/* 1AAC4C 80398BCC 44050000 */  mfc1       $a1, $f0
/* 1AAC50 80398BD0 00000000 */  nop
/* 1AAC54 80398BD4 AFBF0074 */  sw         $ra, 0x74($sp)
/* 1AAC58 80398BD8 AFB1006C */  sw         $s1, 0x6C($sp)
/* 1AAC5C 80398BDC AFB00068 */  sw         $s0, 0x68($sp)
/* 1AAC60 80398BE0 00A03021 */  addu       $a2, $a1, $zero
/* 1AAC64 80398BE4 00A03821 */  addu       $a3, $a1, $zero
/* 1AAC68 80398BE8 E7A20010 */  swc1       $f2, 0x10($sp)
/* 1AAC6C 80398BEC E7A40014 */  swc1       $f4, 0x14($sp)
/* 1AAC70 80398BF0 E7A60018 */  swc1       $f6, 0x18($sp)
/* 1AAC74 80398BF4 0C02FD0E */  jal        guPosition
/* 1AAC78 80398BF8 E7A8001C */   swc1      $f8, 0x1C($sp)
/* 1AAC7C 80398BFC 3C02803B */  lui        $v0, %hi(D_803B3E28)
/* 1AAC80 80398C00 8C423E28 */  lw         $v0, %lo(D_803B3E28)($v0)
/* 1AAC84 80398C04 3C04803B */  lui        $a0, %hi(D_803B3E20)
/* 1AAC88 80398C08 8C843E20 */  lw         $a0, %lo(D_803B3E20)($a0)
/* 1AAC8C 80398C0C 3C03803B */  lui        $v1, %hi(D_803B3E5C)
/* 1AAC90 80398C10 8C633E5C */  lw         $v1, %lo(D_803B3E5C)($v1)
/* 1AAC94 80398C14 3C06803B */  lui        $a2, %hi(D_803B3EA8)
/* 1AAC98 80398C18 8CC63EA8 */  lw         $a2, %lo(D_803B3EA8)($a2)
/* 1AAC9C 80398C1C 00000000 */  nop
/* 1AACA0 80398C20 00640018 */  mult       $v1, $a0
/* 1AACA4 80398C24 00001812 */  mflo       $v1
/* 1AACA8 80398C28 00000000 */  nop
/* 1AACAC 80398C2C 00000000 */  nop
/* 1AACB0 80398C30 A242004A */  sb         $v0, 0x4A($s2)
/* 1AACB4 80398C34 3C05803B */  lui        $a1, %hi(D_803B3E34)
/* 1AACB8 80398C38 8CA53E34 */  lw         $a1, %lo(D_803B3E34)($a1)
/* 1AACBC 80398C3C 3C07803B */  lui        $a3, %hi(D_803B3EAC)
/* 1AACC0 80398C40 8CE73EAC */  lw         $a3, %lo(D_803B3EAC)($a3)
/* 1AACC4 80398C44 26420060 */  addiu      $v0, $s2, 0x60
/* 1AACC8 80398C48 44840000 */  mtc1       $a0, $f0
/* 1AACCC 80398C4C 00000000 */  nop
/* 1AACD0 80398C50 46800020 */  cvt.s.w    $f0, $f0
/* 1AACD4 80398C54 AE420054 */  sw         $v0, 0x54($s2)
/* 1AACD8 80398C58 24020001 */  addiu      $v0, $zero, 0x1
/* 1AACDC 80398C5C E6400040 */  swc1       $f0, 0x40($s2)
/* 1AACE0 80398C60 A6460048 */  sh         $a2, 0x48($s2)
/* 1AACE4 80398C64 AE450050 */  sw         $a1, 0x50($s2)
/* 1AACE8 80398C68 44830000 */  mtc1       $v1, $f0
/* 1AACEC 80398C6C 00000000 */  nop
/* 1AACF0 80398C70 46800020 */  cvt.s.w    $f0, $f0
/* 1AACF4 80398C74 10E20012 */  beq        $a3, $v0, .L80398CC0_ovl8
/* 1AACF8 80398C78 E6400044 */   swc1      $f0, 0x44($s2)
/* 1AACFC 80398C7C 28E20002 */  slti       $v0, $a3, 0x2
/* 1AAD00 80398C80 1440000F */  bnez       $v0, .L80398CC0_ovl8
/* 1AAD04 80398C84 24020002 */   addiu     $v0, $zero, 0x2
/* 1AAD08 80398C88 10E20005 */  beq        $a3, $v0, .L80398CA0_ovl8
/* 1AAD0C 80398C8C 24020003 */   addiu     $v0, $zero, 0x3
/* 1AAD10 80398C90 10E20007 */  beq        $a3, $v0, .L80398CB0_ovl8
/* 1AAD14 80398C94 00000000 */   nop
/* 1AAD18 80398C98 080E6330 */  j          .L80398CC0_ovl8
/* 1AAD1C 80398C9C 00000000 */   nop
.L80398CA0_ovl8:
/* 1AAD20 80398CA0 3C02803A */  lui        $v0, %hi(D_803A1758)
/* 1AAD24 80398CA4 24421758 */  addiu      $v0, $v0, %lo(D_803A1758)
/* 1AAD28 80398CA8 080E6333 */  j          .L80398CCC_ovl8
/* 1AAD2C 80398CAC AE42004C */   sw        $v0, 0x4C($s2)
.L80398CB0_ovl8:
/* 1AAD30 80398CB0 3C02803A */  lui        $v0, %hi(D_803A1758)
/* 1AAD34 80398CB4 24421758 */  addiu      $v0, $v0, %lo(D_803A1758)
/* 1AAD38 80398CB8 080E6333 */  j          .L80398CCC_ovl8
/* 1AAD3C 80398CBC AE42004C */   sw        $v0, 0x4C($s2)
.L80398CC0_ovl8:
/* 1AAD40 80398CC0 3C02803A */  lui        $v0, %hi(D_803A1738)
/* 1AAD44 80398CC4 24421738 */  addiu      $v0, $v0, %lo(D_803A1738)
/* 1AAD48 80398CC8 AE42004C */  sw         $v0, 0x4C($s2)
.L80398CCC_ovl8:
/* 1AAD4C 80398CCC 8E420050 */  lw         $v0, 0x50($s2)
/* 1AAD50 80398CD0 8E500054 */  lw         $s0, 0x54($s2)
/* 1AAD54 80398CD4 1840000D */  blez       $v0, .L80398D0C_ovl8
/* 1AAD58 80398CD8 00008821 */   addu      $s1, $zero, $zero
.L80398CDC_ovl8:
/* 1AAD5C 80398CDC 02402021 */  addu       $a0, $s2, $zero
/* 1AAD60 80398CE0 0C0E625C */  jal        func_80398970
/* 1AAD64 80398CE4 02002821 */   addu      $a1, $s0, $zero
/* 1AAD68 80398CE8 3C04803B */  lui        $a0, %hi(D_803B3E4E)
/* 1AAD6C 80398CEC 94843E4E */  lhu        $a0, %lo(D_803B3E4E)($a0)
/* 1AAD70 80398CF0 0C02591A */  jal        func_80096468
/* 1AAD74 80398CF4 26310001 */   addiu     $s1, $s1, 0x1
/* 1AAD78 80398CF8 A602006E */  sh         $v0, 0x6E($s0)
/* 1AAD7C 80398CFC 8E420050 */  lw         $v0, 0x50($s2)
/* 1AAD80 80398D00 0222102A */  slt        $v0, $s1, $v0
/* 1AAD84 80398D04 1440FFF5 */  bnez       $v0, .L80398CDC_ovl8
/* 1AAD88 80398D08 26100078 */   addiu     $s0, $s0, 0x78
.L80398D0C_ovl8:
/* 1AAD8C 80398D0C 8FBF0074 */  lw         $ra, 0x74($sp)
/* 1AAD90 80398D10 8FB20070 */  lw         $s2, 0x70($sp)
/* 1AAD94 80398D14 8FB1006C */  lw         $s1, 0x6C($sp)
/* 1AAD98 80398D18 8FB00068 */  lw         $s0, 0x68($sp)
/* 1AAD9C 80398D1C 27BD0078 */  addiu      $sp, $sp, 0x78
/* 1AADA0 80398D20 03E00008 */  jr         $ra
/* 1AADA4 80398D24 00000000 */   nop
.size func_80398B94, . - func_80398B94

glabel func_80398D28
/* 1AADA8 80398D28 03E00008 */  jr         $ra
/* 1AADAC 80398D2C 00000000 */   nop
.size func_80398D28, . - func_80398D28

glabel func_80398D30
/* 1AADB0 80398D30 27BDFFB0 */  addiu      $sp, $sp, -0x50
/* 1AADB4 80398D34 AFB20040 */  sw         $s2, 0x40($sp)
/* 1AADB8 80398D38 00809021 */  addu       $s2, $a0, $zero
/* 1AADBC 80398D3C AFBF004C */  sw         $ra, 0x4C($sp)
/* 1AADC0 80398D40 AFB40048 */  sw         $s4, 0x48($sp)
/* 1AADC4 80398D44 AFB30044 */  sw         $s3, 0x44($sp)
/* 1AADC8 80398D48 AFB1003C */  sw         $s1, 0x3C($sp)
/* 1AADCC 80398D4C AFB00038 */  sw         $s0, 0x38($sp)
/* 1AADD0 80398D50 86420048 */  lh         $v0, 0x48($s2)
/* 1AADD4 80398D54 10400154 */  beqz       $v0, .L803992A8_ovl8
/* 1AADD8 80398D58 00401821 */   addu      $v1, $v0, $zero
/* 1AADDC 80398D5C 2462FFFF */  addiu      $v0, $v1, -0x1
/* 1AADE0 80398D60 3C0AD9FD */  lui        $t2, (0xD9FDFFFF >> 16)
/* 1AADE4 80398D64 354AFFFF */  ori        $t2, $t2, (0xD9FDFFFF & 0xFFFF)
/* 1AADE8 80398D68 3C0BD9FF */  lui        $t3, (0xD9FFFFFF >> 16)
/* 1AADEC 80398D6C 356BFFFF */  ori        $t3, $t3, (0xD9FFFFFF & 0xFFFF)
/* 1AADF0 80398D70 3C080020 */  lui        $t0, (0x200405 >> 16)
/* 1AADF4 80398D74 35080405 */  ori        $t0, $t0, (0x200405 & 0xFFFF)
/* 1AADF8 80398D78 3C05E300 */  lui        $a1, (0xE3001201 >> 16)
/* 1AADFC 80398D7C 34A51201 */  ori        $a1, $a1, (0xE3001201 & 0xFFFF)
/* 1AAE00 80398D80 3C09E200 */  lui        $t1, (0xE200001C >> 16)
/* 1AAE04 80398D84 3529001C */  ori        $t1, $t1, (0xE200001C & 0xFFFF)
/* 1AAE08 80398D88 3C060050 */  lui        $a2, (0x504B50 >> 16)
/* 1AAE0C 80398D8C 34C64B50 */  ori        $a2, $a2, (0x504B50 & 0xFFFF)
/* 1AAE10 80398D90 3C04FC11 */  lui        $a0, (0xFC119623 >> 16)
/* 1AAE14 80398D94 34849623 */  ori        $a0, $a0, (0xFC119623 & 0xFFFF)
/* 1AAE18 80398D98 3C03FF2F */  lui        $v1, (0xFF2FFFFF >> 16)
/* 1AAE1C 80398D9C 3463FFFF */  ori        $v1, $v1, (0xFF2FFFFF & 0xFFFF)
/* 1AAE20 80398DA0 3C07E300 */  lui        $a3, (0xE3001001 >> 16)
/* 1AAE24 80398DA4 34E71001 */  ori        $a3, $a3, (0xE3001001 & 0xFFFF)
/* 1AAE28 80398DA8 3C0CF500 */  lui        $t4, (0xF5000100 >> 16)
/* 1AAE2C 80398DAC 3C0E8015 */  lui        $t6, %hi(gDisplayListHead)
/* 1AAE30 80398DB0 8DCE9F94 */  lw         $t6, %lo(gDisplayListHead)($t6)
/* 1AAE34 80398DB4 358C0100 */  ori        $t4, $t4, (0xF5000100 & 0xFFFF)
/* 1AAE38 80398DB8 3C0D0703 */  lui        $t5, (0x703C000 >> 16)
/* 1AAE3C 80398DBC A6420048 */  sh         $v0, 0x48($s2)
/* 1AAE40 80398DC0 3C02DE00 */  lui        $v0, (0xDE000000 >> 16)
/* 1AAE44 80398DC4 ADC20000 */  sw         $v0, 0x0($t6)
/* 1AAE48 80398DC8 3C02800D */  lui        $v0, %hi(D_800D3D70)
/* 1AAE4C 80398DCC 24423D70 */  addiu      $v0, $v0, %lo(D_800D3D70)
/* 1AAE50 80398DD0 ADC20004 */  sw         $v0, 0x4($t6)
/* 1AAE54 80398DD4 24022000 */  addiu      $v0, $zero, 0x2000
/* 1AAE58 80398DD8 ADC90020 */  sw         $t1, 0x20($t6)
/* 1AAE5C 80398DDC 3C09E700 */  lui        $t1, (0xE7000000 >> 16)
/* 1AAE60 80398DE0 ADC2001C */  sw         $v0, 0x1C($t6)
/* 1AAE64 80398DE4 34028000 */  ori        $v0, $zero, 0x8000
/* 1AAE68 80398DE8 ADC2003C */  sw         $v0, 0x3C($t6)
/* 1AAE6C 80398DEC 3C02FD10 */  lui        $v0, (0xFD100000 >> 16)
/* 1AAE70 80398DF0 ADCA0008 */  sw         $t2, 0x8($t6)
/* 1AAE74 80398DF4 ADC0000C */  sw         $zero, 0xC($t6)
/* 1AAE78 80398DF8 ADCB0010 */  sw         $t3, 0x10($t6)
/* 1AAE7C 80398DFC ADC80014 */  sw         $t0, 0x14($t6)
/* 1AAE80 80398E00 ADC50018 */  sw         $a1, 0x18($t6)
/* 1AAE84 80398E04 ADC60024 */  sw         $a2, 0x24($t6)
/* 1AAE88 80398E08 ADC40028 */  sw         $a0, 0x28($t6)
/* 1AAE8C 80398E0C ADC3002C */  sw         $v1, 0x2C($t6)
/* 1AAE90 80398E10 ADC90030 */  sw         $t1, 0x30($t6)
/* 1AAE94 80398E14 ADC00034 */  sw         $zero, 0x34($t6)
/* 1AAE98 80398E18 ADC70038 */  sw         $a3, 0x38($t6)
/* 1AAE9C 80398E1C ADC20040 */  sw         $v0, 0x40($t6)
/* 1AAEA0 80398E20 8E43004C */  lw         $v1, 0x4C($s2)
/* 1AAEA4 80398E24 35ADC000 */  ori        $t5, $t5, (0x703C000 & 0xFFFF)
/* 1AAEA8 80398E28 25C20008 */  addiu      $v0, $t6, 0x8
/* 1AAEAC 80398E2C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAEB0 80398E30 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAEB4 80398E34 25C20010 */  addiu      $v0, $t6, 0x10
/* 1AAEB8 80398E38 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAEBC 80398E3C AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAEC0 80398E40 25C20018 */  addiu      $v0, $t6, 0x18
/* 1AAEC4 80398E44 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAEC8 80398E48 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAECC 80398E4C 25C20020 */  addiu      $v0, $t6, 0x20
/* 1AAED0 80398E50 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAED4 80398E54 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAED8 80398E58 25C20028 */  addiu      $v0, $t6, 0x28
/* 1AAEDC 80398E5C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAEE0 80398E60 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAEE4 80398E64 25C20030 */  addiu      $v0, $t6, 0x30
/* 1AAEE8 80398E68 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAEEC 80398E6C AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAEF0 80398E70 25C20038 */  addiu      $v0, $t6, 0x38
/* 1AAEF4 80398E74 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAEF8 80398E78 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAEFC 80398E7C 25C20040 */  addiu      $v0, $t6, 0x40
/* 1AAF00 80398E80 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAF04 80398E84 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAF08 80398E88 25C20048 */  addiu      $v0, $t6, 0x48
/* 1AAF0C 80398E8C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAF10 80398E90 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAF14 80398E94 25C20050 */  addiu      $v0, $t6, 0x50
/* 1AAF18 80398E98 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAF1C 80398E9C AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAF20 80398EA0 3C02E800 */  lui        $v0, (0xE8000000 >> 16)
/* 1AAF24 80398EA4 ADC20048 */  sw         $v0, 0x48($t6)
/* 1AAF28 80398EA8 25C20058 */  addiu      $v0, $t6, 0x58
/* 1AAF2C 80398EAC 3C0AE600 */  lui        $t2, (0xE6000000 >> 16)
/* 1AAF30 80398EB0 ADC0004C */  sw         $zero, 0x4C($t6)
/* 1AAF34 80398EB4 ADC30044 */  sw         $v1, 0x44($t6)
/* 1AAF38 80398EB8 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAF3C 80398EBC AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAF40 80398EC0 3C020700 */  lui        $v0, (0x7000000 >> 16)
/* 1AAF44 80398EC4 ADC20054 */  sw         $v0, 0x54($t6)
/* 1AAF48 80398EC8 25C20060 */  addiu      $v0, $t6, 0x60
/* 1AAF4C 80398ECC 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAF50 80398ED0 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAF54 80398ED4 25C20068 */  addiu      $v0, $t6, 0x68
/* 1AAF58 80398ED8 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAF5C 80398EDC AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAF60 80398EE0 3C02F000 */  lui        $v0, (0xF0000000 >> 16)
/* 1AAF64 80398EE4 ADC20060 */  sw         $v0, 0x60($t6)
/* 1AAF68 80398EE8 25C20070 */  addiu      $v0, $t6, 0x70
/* 1AAF6C 80398EEC ADCC0050 */  sw         $t4, 0x50($t6)
/* 1AAF70 80398EF0 ADCA0058 */  sw         $t2, 0x58($t6)
/* 1AAF74 80398EF4 ADC0005C */  sw         $zero, 0x5C($t6)
/* 1AAF78 80398EF8 ADCD0064 */  sw         $t5, 0x64($t6)
/* 1AAF7C 80398EFC 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAF80 80398F00 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAF84 80398F04 ADC90068 */  sw         $t1, 0x68($t6)
/* 1AAF88 80398F08 ADC0006C */  sw         $zero, 0x6C($t6)
/* 1AAF8C 80398F0C 9243004A */  lbu        $v1, 0x4A($s2)
/* 1AAF90 80398F10 24020007 */  addiu      $v0, $zero, 0x7
/* 1AAF94 80398F14 14620034 */  bne        $v1, $v0, .L80398FE8_ovl8
/* 1AAF98 80398F18 3C030701 */   lui       $v1, (0x7018060 >> 16)
/* 1AAF9C 80398F1C 34638060 */  ori        $v1, $v1, (0x7018060 & 0xFFFF)
/* 1AAFA0 80398F20 3C04073F */  lui        $a0, (0x73FF200 >> 16)
/* 1AAFA4 80398F24 3484F200 */  ori        $a0, $a0, (0x73FF200 & 0xFFFF)
/* 1AAFA8 80398F28 3C06F540 */  lui        $a2, (0xF5400800 >> 16)
/* 1AAFAC 80398F2C 34C60800 */  ori        $a2, $a2, (0xF5400800 & 0xFFFF)
/* 1AAFB0 80398F30 3C050001 */  lui        $a1, (0x18060 >> 16)
/* 1AAFB4 80398F34 34A58060 */  ori        $a1, $a1, (0x18060 & 0xFFFF)
/* 1AAFB8 80398F38 3C07000F */  lui        $a3, (0xFC0FC >> 16)
/* 1AAFBC 80398F3C 3C08803B */  lui        $t0, %hi(D_803A9390)
/* 1AAFC0 80398F40 8D089390 */  lw         $t0, %lo(D_803A9390)($t0)
/* 1AAFC4 80398F44 34E7C0FC */  ori        $a3, $a3, (0xFC0FC & 0xFFFF)
/* 1AAFC8 80398F48 25C20078 */  addiu      $v0, $t6, 0x78
/* 1AAFCC 80398F4C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAFD0 80398F50 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAFD4 80398F54 3C02FD50 */  lui        $v0, (0xFD500000 >> 16)
/* 1AAFD8 80398F58 ADC20070 */  sw         $v0, 0x70($t6)
/* 1AAFDC 80398F5C 25C20080 */  addiu      $v0, $t6, 0x80
/* 1AAFE0 80398F60 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAFE4 80398F64 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAFE8 80398F68 3C02F550 */  lui        $v0, (0xF5500000 >> 16)
/* 1AAFEC 80398F6C ADC20078 */  sw         $v0, 0x78($t6)
/* 1AAFF0 80398F70 25C20088 */  addiu      $v0, $t6, 0x88
/* 1AAFF4 80398F74 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AAFF8 80398F78 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AAFFC 80398F7C 25C20090 */  addiu      $v0, $t6, 0x90
/* 1AB000 80398F80 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB004 80398F84 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB008 80398F88 3C02F300 */  lui        $v0, (0xF3000000 >> 16)
/* 1AB00C 80398F8C ADC20088 */  sw         $v0, 0x88($t6)
/* 1AB010 80398F90 25C20098 */  addiu      $v0, $t6, 0x98
/* 1AB014 80398F94 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB018 80398F98 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB01C 80398F9C 25C200A0 */  addiu      $v0, $t6, 0xA0
/* 1AB020 80398FA0 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB024 80398FA4 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB028 80398FA8 25C200A8 */  addiu      $v0, $t6, 0xA8
/* 1AB02C 80398FAC 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB030 80398FB0 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB034 80398FB4 3C02F200 */  lui        $v0, (0xF2000000 >> 16)
/* 1AB038 80398FB8 ADC3007C */  sw         $v1, 0x7C($t6)
/* 1AB03C 80398FBC ADCA0080 */  sw         $t2, 0x80($t6)
/* 1AB040 80398FC0 ADC00084 */  sw         $zero, 0x84($t6)
/* 1AB044 80398FC4 ADC4008C */  sw         $a0, 0x8C($t6)
/* 1AB048 80398FC8 ADC90090 */  sw         $t1, 0x90($t6)
/* 1AB04C 80398FCC ADC00094 */  sw         $zero, 0x94($t6)
/* 1AB050 80398FD0 ADC60098 */  sw         $a2, 0x98($t6)
/* 1AB054 80398FD4 ADC5009C */  sw         $a1, 0x9C($t6)
/* 1AB058 80398FD8 ADC200A0 */  sw         $v0, 0xA0($t6)
/* 1AB05C 80398FDC ADC700A4 */  sw         $a3, 0xA4($t6)
/* 1AB060 80398FE0 25040010 */  addiu      $a0, $t0, 0x10
/* 1AB064 80398FE4 ADC40074 */  sw         $a0, 0x74($t6)
.L80398FE8_ovl8:
/* 1AB068 80398FE8 3C028015 */  lui        $v0, %hi(gDisplayListHead)
/* 1AB06C 80398FEC 8C429F94 */  lw         $v0, %lo(gDisplayListHead)($v0)
/* 1AB070 80398FF0 3C03DA38 */  lui        $v1, (0xDA380003 >> 16)
/* 1AB074 80398FF4 34630003 */  ori        $v1, $v1, (0xDA380003 & 0xFFFF)
/* 1AB078 80398FF8 AC430000 */  sw         $v1, 0x0($v0)
/* 1AB07C 80398FFC AC520004 */  sw         $s2, 0x4($v0)
/* 1AB080 80399000 8E510054 */  lw         $s1, 0x54($s2)
/* 1AB084 80399004 8E430050 */  lw         $v1, 0x50($s2)
/* 1AB088 80399008 24420008 */  addiu      $v0, $v0, 0x8
/* 1AB08C 8039900C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB090 80399010 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB094 80399014 186000A2 */  blez       $v1, .L803992A0_ovl8
/* 1AB098 80399018 00009821 */   addu      $s3, $zero, $zero
/* 1AB09C 8039901C 3C148015 */  lui        $s4, %hi(D_8014A07C)
/* 1AB0A0 80399020 2694A07C */  addiu      $s4, $s4, %lo(D_8014A07C)
/* 1AB0A4 80399024 2630006C */  addiu      $s0, $s1, 0x6C
.L80399028_ovl8:
/* 1AB0A8 80399028 86020002 */  lh         $v0, 0x2($s0)
/* 1AB0AC 8039902C 10400004 */  beqz       $v0, .L80399040_ovl8
/* 1AB0B0 80399030 00401821 */   addu      $v1, $v0, $zero
/* 1AB0B4 80399034 2462FFFF */  addiu      $v0, $v1, -0x1
/* 1AB0B8 80399038 080E64A2 */  j          .L80399288_ovl8
/* 1AB0BC 8039903C A6020002 */   sh        $v0, 0x2($s0)
.L80399040_ovl8:
/* 1AB0C0 80399040 86020000 */  lh         $v0, 0x0($s0)
/* 1AB0C4 80399044 1440000A */  bnez       $v0, .L80399070_ovl8
/* 1AB0C8 80399048 02202021 */   addu      $a0, $s1, $zero
/* 1AB0CC 8039904C 86420048 */  lh         $v0, 0x48($s2)
/* 1AB0D0 80399050 28420015 */  slti       $v0, $v0, 0x15
/* 1AB0D4 80399054 5440008D */  bnel       $v0, $zero, .L8039928C_ovl8
/* 1AB0D8 80399058 26730001 */   addiu     $s3, $s3, 0x1
/* 1AB0DC 8039905C 02402021 */  addu       $a0, $s2, $zero
/* 1AB0E0 80399060 0C0E625C */  jal        func_80398970
/* 1AB0E4 80399064 02202821 */   addu      $a1, $s1, $zero
/* 1AB0E8 80399068 080E64A3 */  j          .L8039928C_ovl8
/* 1AB0EC 8039906C 26730001 */   addiu     $s3, $s3, 0x1
.L80399070_ovl8:
/* 1AB0F0 80399070 C600FFF0 */  lwc1       $f0, -0x10($s0)
/* 1AB0F4 80399074 8E850000 */  lw         $a1, 0x0($s4)
/* 1AB0F8 80399078 E7A00010 */  swc1       $f0, 0x10($sp)
/* 1AB0FC 8039907C C600FFD4 */  lwc1       $f0, -0x2C($s0)
/* 1AB100 80399080 E7A00014 */  swc1       $f0, 0x14($sp)
/* 1AB104 80399084 C600FFD8 */  lwc1       $f0, -0x28($s0)
/* 1AB108 80399088 E7A00018 */  swc1       $f0, 0x18($sp)
/* 1AB10C 8039908C C600FFDC */  lwc1       $f0, -0x24($s0)
/* 1AB110 80399090 8E860004 */  lw         $a2, 0x4($s4)
/* 1AB114 80399094 8E870008 */  lw         $a3, 0x8($s4)
/* 1AB118 80399098 0C02FD0E */  jal        guPosition
/* 1AB11C 8039909C E7A0001C */   swc1      $f0, 0x1C($sp)
/* 1AB120 803990A0 3C098015 */  lui        $t1, %hi(gDisplayListHead)
/* 1AB124 803990A4 8D299F94 */  lw         $t1, %lo(gDisplayListHead)($t1)
/* 1AB128 803990A8 3C02DA38 */  lui        $v0, (0xDA380000 >> 16)
/* 1AB12C 803990AC AD220000 */  sw         $v0, 0x0($t1)
/* 1AB130 803990B0 3C02FA00 */  lui        $v0, (0xFA000000 >> 16)
/* 1AB134 803990B4 AD310004 */  sw         $s1, 0x4($t1)
/* 1AB138 803990B8 AD220008 */  sw         $v0, 0x8($t1)
/* 1AB13C 803990BC 86030000 */  lh         $v1, 0x0($s0)
/* 1AB140 803990C0 25220008 */  addiu      $v0, $t1, 0x8
/* 1AB144 803990C4 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB148 803990C8 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB14C 803990CC 25220010 */  addiu      $v0, $t1, 0x10
/* 1AB150 803990D0 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB154 803990D4 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB158 803990D8 2402FF00 */  addiu      $v0, $zero, -0x100
/* 1AB15C 803990DC 000318C0 */  sll        $v1, $v1, 3
/* 1AB160 803990E0 00621825 */  or         $v1, $v1, $v0
/* 1AB164 803990E4 AD23000C */  sw         $v1, 0xC($t1)
/* 1AB168 803990E8 9243004A */  lbu        $v1, 0x4A($s2)
/* 1AB16C 803990EC 24020007 */  addiu      $v0, $zero, 0x7
/* 1AB170 803990F0 1062003C */  beq        $v1, $v0, .L803991E4_ovl8
/* 1AB174 803990F4 3C030701 */   lui       $v1, (0x7018060 >> 16)
/* 1AB178 803990F8 34638060 */  ori        $v1, $v1, (0x7018060 & 0xFFFF)
/* 1AB17C 803990FC 3C05073F */  lui        $a1, (0x73FF200 >> 16)
/* 1AB180 80399100 34A5F200 */  ori        $a1, $a1, (0x73FF200 & 0xFFFF)
/* 1AB184 80399104 3C08F540 */  lui        $t0, (0xF5400800 >> 16)
/* 1AB188 80399108 35080800 */  ori        $t0, $t0, (0xF5400800 & 0xFFFF)
/* 1AB18C 8039910C 3C060001 */  lui        $a2, (0x18060 >> 16)
/* 1AB190 80399110 C600FFF8 */  lwc1       $f0, -0x8($s0)
/* 1AB194 80399114 34C68060 */  ori        $a2, $a2, (0x18060 & 0xFFFF)
/* 1AB198 80399118 3C07000F */  lui        $a3, (0xFC0FC >> 16)
/* 1AB19C 8039911C 4600008D */  trunc.w.s  $f2, $f0
/* 1AB1A0 80399120 44021000 */  mfc1       $v0, $f2
/* 1AB1A4 80399124 00000000 */  nop
/* 1AB1A8 80399128 00021080 */  sll        $v0, $v0, 2
/* 1AB1AC 8039912C 3C04803B */  lui        $a0, %hi(D_803A9380)
/* 1AB1B0 80399130 00822021 */  addu       $a0, $a0, $v0
/* 1AB1B4 80399134 8C849380 */  lw         $a0, %lo(D_803A9380)($a0)
/* 1AB1B8 80399138 34E7C0FC */  ori        $a3, $a3, (0xFC0FC & 0xFFFF)
/* 1AB1BC 8039913C 25220018 */  addiu      $v0, $t1, 0x18
/* 1AB1C0 80399140 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB1C4 80399144 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB1C8 80399148 25220020 */  addiu      $v0, $t1, 0x20
/* 1AB1CC 8039914C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB1D0 80399150 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB1D4 80399154 25220028 */  addiu      $v0, $t1, 0x28
/* 1AB1D8 80399158 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB1DC 8039915C AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB1E0 80399160 25220030 */  addiu      $v0, $t1, 0x30
/* 1AB1E4 80399164 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB1E8 80399168 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB1EC 8039916C 25220038 */  addiu      $v0, $t1, 0x38
/* 1AB1F0 80399170 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB1F4 80399174 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB1F8 80399178 25220040 */  addiu      $v0, $t1, 0x40
/* 1AB1FC 8039917C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB200 80399180 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB204 80399184 25220048 */  addiu      $v0, $t1, 0x48
/* 1AB208 80399188 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB20C 8039918C AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB210 80399190 3C02FD50 */  lui        $v0, (0xFD500000 >> 16)
/* 1AB214 80399194 AD220010 */  sw         $v0, 0x10($t1)
/* 1AB218 80399198 3C02F550 */  lui        $v0, (0xF5500000 >> 16)
/* 1AB21C 8039919C AD220018 */  sw         $v0, 0x18($t1)
/* 1AB220 803991A0 3C02E600 */  lui        $v0, (0xE6000000 >> 16)
/* 1AB224 803991A4 AD220020 */  sw         $v0, 0x20($t1)
/* 1AB228 803991A8 3C02F300 */  lui        $v0, (0xF3000000 >> 16)
/* 1AB22C 803991AC AD220028 */  sw         $v0, 0x28($t1)
/* 1AB230 803991B0 3C02E700 */  lui        $v0, (0xE7000000 >> 16)
/* 1AB234 803991B4 AD220030 */  sw         $v0, 0x30($t1)
/* 1AB238 803991B8 3C02F200 */  lui        $v0, (0xF2000000 >> 16)
/* 1AB23C 803991BC AD23001C */  sw         $v1, 0x1C($t1)
/* 1AB240 803991C0 AD200024 */  sw         $zero, 0x24($t1)
/* 1AB244 803991C4 AD25002C */  sw         $a1, 0x2C($t1)
/* 1AB248 803991C8 AD200034 */  sw         $zero, 0x34($t1)
/* 1AB24C 803991CC AD280038 */  sw         $t0, 0x38($t1)
/* 1AB250 803991D0 AD26003C */  sw         $a2, 0x3C($t1)
/* 1AB254 803991D4 AD220040 */  sw         $v0, 0x40($t1)
/* 1AB258 803991D8 AD270044 */  sw         $a3, 0x44($t1)
/* 1AB25C 803991DC 24840010 */  addiu      $a0, $a0, 0x10
/* 1AB260 803991E0 AD240014 */  sw         $a0, 0x14($t1)
.L803991E4_ovl8:
/* 1AB264 803991E4 3C038015 */  lui        $v1, %hi(gDisplayListHead)
/* 1AB268 803991E8 8C639F94 */  lw         $v1, %lo(gDisplayListHead)($v1)
/* 1AB26C 803991EC 3C01803B */  lui        $at, %hi(D_803B3E58)
/* 1AB270 803991F0 C4203E58 */  lwc1       $f0, %lo(D_803B3E58)($at)
/* 1AB274 803991F4 3C02DE00 */  lui        $v0, (0xDE000000 >> 16)
/* 1AB278 803991F8 AC620000 */  sw         $v0, 0x0($v1)
/* 1AB27C 803991FC 3C02803A */  lui        $v0, %hi(D_803A1FB8)
/* 1AB280 80399200 24421FB8 */  addiu      $v0, $v0, %lo(D_803A1FB8)
/* 1AB284 80399204 AC620004 */  sw         $v0, 0x4($v1)
/* 1AB288 80399208 C606FFD4 */  lwc1       $f6, -0x2C($s0)
/* 1AB28C 8039920C C60AFFE4 */  lwc1       $f10, -0x1C($s0)
/* 1AB290 80399210 46003180 */  add.s      $f6, $f6, $f0
/* 1AB294 80399214 C602FFEC */  lwc1       $f2, -0x14($s0)
/* 1AB298 80399218 C60EFFD8 */  lwc1       $f14, -0x28($s0)
/* 1AB29C 8039921C C610FFE0 */  lwc1       $f16, -0x20($s0)
/* 1AB2A0 80399220 46025280 */  add.s      $f10, $f10, $f2
/* 1AB2A4 80399224 C600FFE4 */  lwc1       $f0, -0x1C($s0)
/* 1AB2A8 80399228 C60CFFDC */  lwc1       $f12, -0x24($s0)
/* 1AB2AC 8039922C C604FFF0 */  lwc1       $f4, -0x10($s0)
/* 1AB2B0 80399230 46007380 */  add.s      $f14, $f14, $f0
/* 1AB2B4 80399234 C600FFE8 */  lwc1       $f0, -0x18($s0)
/* 1AB2B8 80399238 C608FFF4 */  lwc1       $f8, -0xC($s0)
/* 1AB2BC 8039923C 96020000 */  lhu        $v0, 0x0($s0)
/* 1AB2C0 80399240 46006300 */  add.s      $f12, $f12, $f0
/* 1AB2C4 80399244 C602FFFC */  lwc1       $f2, -0x4($s0)
/* 1AB2C8 80399248 C600FFF8 */  lwc1       $f0, -0x8($s0)
/* 1AB2CC 8039924C 24630008 */  addiu      $v1, $v1, 0x8
/* 1AB2D0 80399250 46082100 */  add.s      $f4, $f4, $f8
/* 1AB2D4 80399254 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB2D8 80399258 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1AB2DC 8039925C 2442FFFF */  addiu      $v0, $v0, -0x1
/* 1AB2E0 80399260 E606FFD4 */  swc1       $f6, -0x2C($s0)
/* 1AB2E4 80399264 46103180 */  add.s      $f6, $f6, $f16
/* 1AB2E8 80399268 A6020000 */  sh         $v0, 0x0($s0)
/* 1AB2EC 8039926C E60AFFE4 */  swc1       $f10, -0x1C($s0)
/* 1AB2F0 80399270 E604FFF0 */  swc1       $f4, -0x10($s0)
/* 1AB2F4 80399274 46020000 */  add.s      $f0, $f0, $f2
/* 1AB2F8 80399278 E60EFFD8 */  swc1       $f14, -0x28($s0)
/* 1AB2FC 8039927C E606FFD4 */  swc1       $f6, -0x2C($s0)
/* 1AB300 80399280 E60CFFDC */  swc1       $f12, -0x24($s0)
/* 1AB304 80399284 E600FFF8 */  swc1       $f0, -0x8($s0)
.L80399288_ovl8:
/* 1AB308 80399288 26730001 */  addiu      $s3, $s3, 0x1
.L8039928C_ovl8:
/* 1AB30C 8039928C 8E420050 */  lw         $v0, 0x50($s2)
/* 1AB310 80399290 26100078 */  addiu      $s0, $s0, 0x78
/* 1AB314 80399294 0262102A */  slt        $v0, $s3, $v0
/* 1AB318 80399298 1440FF63 */  bnez       $v0, .L80399028_ovl8
/* 1AB31C 8039929C 26310078 */   addiu     $s1, $s1, 0x78
.L803992A0_ovl8:
/* 1AB320 803992A0 080E64AB */  j          .L803992AC_ovl8
/* 1AB324 803992A4 00001021 */   addu      $v0, $zero, $zero
.L803992A8_ovl8:
/* 1AB328 803992A8 24020001 */  addiu      $v0, $zero, 0x1
.L803992AC_ovl8:
/* 1AB32C 803992AC 8FBF004C */  lw         $ra, 0x4C($sp)
/* 1AB330 803992B0 8FB40048 */  lw         $s4, 0x48($sp)
/* 1AB334 803992B4 8FB30044 */  lw         $s3, 0x44($sp)
/* 1AB338 803992B8 8FB20040 */  lw         $s2, 0x40($sp)
/* 1AB33C 803992BC 8FB1003C */  lw         $s1, 0x3C($sp)
/* 1AB340 803992C0 8FB00038 */  lw         $s0, 0x38($sp)
/* 1AB344 803992C4 27BD0050 */  addiu      $sp, $sp, 0x50
/* 1AB348 803992C8 03E00008 */  jr         $ra
/* 1AB34C 803992CC 00000000 */   nop
.size func_80398D30, . - func_80398D30

glabel func_803992D0
/* 1AB350 803992D0 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 1AB354 803992D4 8FA20028 */  lw         $v0, 0x28($sp)
/* 1AB358 803992D8 8FA3002C */  lw         $v1, 0x2C($sp)
/* 1AB35C 803992DC 8FA80030 */  lw         $t0, 0x30($sp)
/* 1AB360 803992E0 97A90036 */  lhu        $t1, 0x36($sp)
/* 1AB364 803992E4 00042400 */  sll        $a0, $a0, 16
/* 1AB368 803992E8 00042403 */  sra        $a0, $a0, 16
/* 1AB36C 803992EC 00052C00 */  sll        $a1, $a1, 16
/* 1AB370 803992F0 00052C03 */  sra        $a1, $a1, 16
/* 1AB374 803992F4 00063400 */  sll        $a2, $a2, 16
/* 1AB378 803992F8 00063403 */  sra        $a2, $a2, 16
/* 1AB37C 803992FC 00073C00 */  sll        $a3, $a3, 16
/* 1AB380 80399300 00073C03 */  sra        $a3, $a3, 16
/* 1AB384 80399304 3C01803B */  lui        $at, %hi(D_803B3E28)
/* 1AB388 80399308 AC243E28 */  sw         $a0, %lo(D_803B3E28)($at)
/* 1AB38C 8039930C 3C04803A */  lui        $a0, %hi(D_803987C0)
/* 1AB390 80399310 248487C0 */  addiu      $a0, $a0, %lo(D_803987C0)
/* 1AB394 80399314 3C01803B */  lui        $at, %hi(D_803B3E34)
/* 1AB398 80399318 AC253E34 */  sw         $a1, %lo(D_803B3E34)($at)
/* 1AB39C 8039931C 24050001 */  addiu      $a1, $zero, 0x1
/* 1AB3A0 80399320 3C01803B */  lui        $at, %hi(D_803B3E20)
/* 1AB3A4 80399324 AC273E20 */  sw         $a3, %lo(D_803B3E20)($at)
/* 1AB3A8 80399328 24070001 */  addiu      $a3, $zero, 0x1
/* 1AB3AC 8039932C AFBF0010 */  sw         $ra, 0x10($sp)
/* 1AB3B0 80399330 3C01803B */  lui        $at, %hi(D_803B3EA8)
/* 1AB3B4 80399334 AC263EA8 */  sw         $a2, %lo(D_803B3EA8)($at)
/* 1AB3B8 80399338 00021400 */  sll        $v0, $v0, 16
/* 1AB3BC 8039933C 00021403 */  sra        $v0, $v0, 16
/* 1AB3C0 80399340 00031C00 */  sll        $v1, $v1, 16
/* 1AB3C4 80399344 00031C03 */  sra        $v1, $v1, 16
/* 1AB3C8 80399348 00084400 */  sll        $t0, $t0, 16
/* 1AB3CC 8039934C 00084403 */  sra        $t0, $t0, 16
/* 1AB3D0 80399350 3C01803B */  lui        $at, %hi(D_803B3E5C)
/* 1AB3D4 80399354 AC223E5C */  sw         $v0, %lo(D_803B3E5C)($at)
/* 1AB3D8 80399358 3C01803B */  lui        $at, %hi(D_803B3E4C)
/* 1AB3DC 8039935C AC233E4C */  sw         $v1, %lo(D_803B3E4C)($at)
/* 1AB3E0 80399360 3C01803B */  lui        $at, %hi(D_803B3EAC)
/* 1AB3E4 80399364 AC283EAC */  sw         $t0, %lo(D_803B3EAC)($at)
/* 1AB3E8 80399368 0C025D06 */  jal        func_80097418
/* 1AB3EC 8039936C 01203021 */   addu      $a2, $t1, $zero
/* 1AB3F0 80399370 8FBF0010 */  lw         $ra, 0x10($sp)
/* 1AB3F4 80399374 27BD0018 */  addiu      $sp, $sp, 0x18
/* 1AB3F8 80399378 03E00008 */  jr         $ra
/* 1AB3FC 8039937C 00000000 */   nop
.size func_803992D0, . - func_803992D0

glabel func_80399380
/* 1AB400 80399380 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1AB404 80399384 3C04803B */  lui        $a0, %hi(D_803AE450)
/* 1AB408 80399388 2484E450 */  addiu      $a0, $a0, %lo(D_803AE450)
/* 1AB40C 8039938C 3C050061 */  lui        $a1, %hi(Palettes_ROM_START)
/* 1AB410 80399390 24A5CB80 */  addiu      $a1, $a1, %lo(Palettes_ROM_START)
/* 1AB414 80399394 3C06800E */  lui        $a2, %hi(D_800DD820)
/* 1AB418 80399398 24C6D820 */  addiu      $a2, $a2, %lo(D_800DD820)
/* 1AB41C 8039939C 24070079 */  addiu      $a3, $zero, 0x79
/* 1AB420 803993A0 AFBF0018 */  sw         $ra, 0x18($sp)
/* 1AB424 803993A4 AFB10014 */  sw         $s1, 0x14($sp)
/* 1AB428 803993A8 0C0264C3 */  jal        func_8009930C
/* 1AB42C 803993AC AFB00010 */   sw        $s0, 0x10($sp)
/* 1AB430 803993B0 00008021 */  addu       $s0, $zero, $zero
/* 1AB434 803993B4 3C11803B */  lui        $s1, %hi(D_803AE470)
/* 1AB438 803993B8 2631E470 */  addiu      $s1, $s1, %lo(D_803AE470)
.L803993BC_ovl8:
/* 1AB43C 803993BC 02202021 */  addu       $a0, $s1, $zero
/* 1AB440 803993C0 3C05001E */  lui        $a1, %hi(Image_ROM_START)
/* 1AB444 803993C4 24A59000 */  addiu      $a1, $a1, %lo(Image_ROM_START)
/* 1AB448 803993C8 3C06800D */  lui        $a2, %hi(D_800D6AD0)
/* 1AB44C 803993CC 24C66AD0 */  addiu      $a2, $a2, %lo(D_800D6AD0)
/* 1AB450 803993D0 0C0264C3 */  jal        func_8009930C
/* 1AB454 803993D4 260700F9 */   addiu     $a3, $s0, 0xF9
/* 1AB458 803993D8 26100001 */  addiu      $s0, $s0, 0x1
/* 1AB45C 803993DC 2A020009 */  slti       $v0, $s0, 0x9
/* 1AB460 803993E0 1440FFF6 */  bnez       $v0, .L803993BC_ovl8
/* 1AB464 803993E4 26310810 */   addiu     $s1, $s1, 0x810
/* 1AB468 803993E8 8FBF0018 */  lw         $ra, 0x18($sp)
/* 1AB46C 803993EC 8FB10014 */  lw         $s1, 0x14($sp)
/* 1AB470 803993F0 8FB00010 */  lw         $s0, 0x10($sp)
/* 1AB474 803993F4 27BD0020 */  addiu      $sp, $sp, 0x20
/* 1AB478 803993F8 03E00008 */  jr         $ra
/* 1AB47C 803993FC 00000000 */   nop
.size func_80399380, . - func_80399380

glabel func_80399400
/* 1AB480 80399400 03E00008 */  jr         $ra
/* 1AB484 80399404 00000000 */   nop
.size func_80399400, . - func_80399400

glabel D_80399408
/* 1AB488 80399408 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1AB48C 8039940C AFB00010 */  sw         $s0, 0x10($sp)
/* 1AB490 80399410 00808021 */  addu       $s0, $a0, $zero
/* 1AB494 80399414 AFBF0018 */  sw         $ra, 0x18($sp)
/* 1AB498 80399418 AFB10014 */  sw         $s1, 0x14($sp)
/* 1AB49C 8039941C 9603001C */  lhu        $v1, 0x1C($s0)
/* 1AB4A0 80399420 24110001 */  addiu      $s1, $zero, 0x1
/* 1AB4A4 80399424 1071002D */  beq        $v1, $s1, .L803994DC_ovl8
/* 1AB4A8 80399428 28620002 */   slti      $v0, $v1, 0x2
/* 1AB4AC 8039942C 50400005 */  beql       $v0, $zero, .L80399444_ovl8
/* 1AB4B0 80399430 3402FFFF */   ori       $v0, $zero, 0xFFFF
/* 1AB4B4 80399434 10600007 */  beqz       $v1, .L80399454_ovl8
/* 1AB4B8 80399438 00000000 */   nop
/* 1AB4BC 8039943C 080E655E */  j          .L80399578_ovl8
/* 1AB4C0 80399440 00000000 */   nop
.L80399444_ovl8:
/* 1AB4C4 80399444 1062002D */  beq        $v1, $v0, .L803994FC_ovl8
/* 1AB4C8 80399448 00000000 */   nop
/* 1AB4CC 8039944C 080E655E */  j          .L80399578_ovl8
/* 1AB4D0 80399450 00000000 */   nop
.L80399454_ovl8:
/* 1AB4D4 80399454 8E03000C */  lw         $v1, 0xC($s0)
/* 1AB4D8 80399458 1071000F */  beq        $v1, $s1, .L80399498_ovl8
/* 1AB4DC 8039945C 28620002 */   slti      $v0, $v1, 0x2
/* 1AB4E0 80399460 50400005 */  beql       $v0, $zero, .L80399478_ovl8
/* 1AB4E4 80399464 24020002 */   addiu     $v0, $zero, 0x2
/* 1AB4E8 80399468 10600007 */  beqz       $v1, .L80399488_ovl8
/* 1AB4EC 8039946C 00000000 */   nop
/* 1AB4F0 80399470 080E6530 */  j          .L803994C0_ovl8
/* 1AB4F4 80399474 00000000 */   nop
.L80399478_ovl8:
/* 1AB4F8 80399478 1062000B */  beq        $v1, $v0, .L803994A8_ovl8
/* 1AB4FC 8039947C 00000000 */   nop
/* 1AB500 80399480 080E6530 */  j          .L803994C0_ovl8
/* 1AB504 80399484 00000000 */   nop
.L80399488_ovl8:
/* 1AB508 80399488 0C032663 */  jal        func_800C998C
/* 1AB50C 8039948C 240400C0 */   addiu     $a0, $zero, 0xC0
/* 1AB510 80399490 080E652D */  j          .L803994B4_ovl8
/* 1AB514 80399494 AE020014 */   sw        $v0, 0x14($s0)
.L80399498_ovl8:
/* 1AB518 80399498 0C025E63 */  jal        func_8009798C
/* 1AB51C 8039949C 240400C0 */   addiu     $a0, $zero, 0xC0
/* 1AB520 803994A0 080E652D */  j          .L803994B4_ovl8
/* 1AB524 803994A4 AE020014 */   sw        $v0, 0x14($s0)
.L803994A8_ovl8:
/* 1AB528 803994A8 0C026127 */  jal        func_8009849C
/* 1AB52C 803994AC 240400C0 */   addiu     $a0, $zero, 0xC0
/* 1AB530 803994B0 AE020014 */  sw         $v0, 0x14($s0)
.L803994B4_ovl8:
/* 1AB534 803994B4 00402021 */  addu       $a0, $v0, $zero
/* 1AB538 803994B8 0C030134 */  jal        bzero
/* 1AB53C 803994BC 240500C0 */   addiu     $a1, $zero, 0xC0
.L803994C0_ovl8:
/* 1AB540 803994C0 8E040014 */  lw         $a0, 0x14($s0)
/* 1AB544 803994C4 0C0E6566 */  jal        func_80399598
/* 1AB548 803994C8 00000000 */   nop
/* 1AB54C 803994CC 00001021 */  addu       $v0, $zero, $zero
/* 1AB550 803994D0 24030001 */  addiu      $v1, $zero, 0x1
/* 1AB554 803994D4 080E6560 */  j          .L80399580_ovl8
/* 1AB558 803994D8 A603001C */   sh        $v1, 0x1C($s0)
.L803994DC_ovl8:
/* 1AB55C 803994DC 8E040014 */  lw         $a0, 0x14($s0)
/* 1AB560 803994E0 0C0E6609 */  jal        func_80399824
/* 1AB564 803994E4 00000000 */   nop
/* 1AB568 803994E8 10400002 */  beqz       $v0, .L803994F4_ovl8
/* 1AB56C 803994EC 3402FFFF */   ori       $v0, $zero, 0xFFFF
/* 1AB570 803994F0 A602001C */  sh         $v0, 0x1C($s0)
.L803994F4_ovl8:
/* 1AB574 803994F4 080E6560 */  j          .L80399580_ovl8
/* 1AB578 803994F8 00001021 */   addu      $v0, $zero, $zero
.L803994FC_ovl8:
/* 1AB57C 803994FC 8E040014 */  lw         $a0, 0x14($s0)
/* 1AB580 80399500 0C0E6607 */  jal        func_8039981C
/* 1AB584 80399504 00000000 */   nop
/* 1AB588 80399508 8E03000C */  lw         $v1, 0xC($s0)
/* 1AB58C 8039950C 10710010 */  beq        $v1, $s1, .L80399550_ovl8
/* 1AB590 80399510 28620002 */   slti      $v0, $v1, 0x2
/* 1AB594 80399514 50400005 */  beql       $v0, $zero, .L8039952C_ovl8
/* 1AB598 80399518 24020002 */   addiu     $v0, $zero, 0x2
/* 1AB59C 8039951C 10600007 */  beqz       $v1, .L8039953C_ovl8
/* 1AB5A0 80399520 24020001 */   addiu     $v0, $zero, 0x1
/* 1AB5A4 80399524 080E6560 */  j          .L80399580_ovl8
/* 1AB5A8 80399528 00000000 */   nop
.L8039952C_ovl8:
/* 1AB5AC 8039952C 1062000D */  beq        $v1, $v0, .L80399564_ovl8
/* 1AB5B0 80399530 24020001 */   addiu     $v0, $zero, 0x1
/* 1AB5B4 80399534 080E6560 */  j          .L80399580_ovl8
/* 1AB5B8 80399538 00000000 */   nop
.L8039953C_ovl8:
/* 1AB5BC 8039953C 8E040014 */  lw         $a0, 0x14($s0)
/* 1AB5C0 80399540 0C0326A1 */  jal        func_800C9A84
/* 1AB5C4 80399544 00000000 */   nop
/* 1AB5C8 80399548 080E6560 */  j          .L80399580_ovl8
/* 1AB5CC 8039954C 24020001 */   addiu     $v0, $zero, 0x1
.L80399550_ovl8:
/* 1AB5D0 80399550 8E040014 */  lw         $a0, 0x14($s0)
/* 1AB5D4 80399554 0C025EC3 */  jal        func_80097B0C
/* 1AB5D8 80399558 00000000 */   nop
/* 1AB5DC 8039955C 080E6560 */  j          .L80399580_ovl8
/* 1AB5E0 80399560 24020001 */   addiu     $v0, $zero, 0x1
.L80399564_ovl8:
/* 1AB5E4 80399564 8E040014 */  lw         $a0, 0x14($s0)
/* 1AB5E8 80399568 0C026187 */  jal        func_8009861C
/* 1AB5EC 8039956C 00000000 */   nop
/* 1AB5F0 80399570 080E6560 */  j          .L80399580_ovl8
/* 1AB5F4 80399574 24020001 */   addiu     $v0, $zero, 0x1
.L80399578_ovl8:
/* 1AB5F8 80399578 0C032934 */  jal        func_800CA4D0
/* 1AB5FC 8039957C 00000000 */   nop
.L80399580_ovl8:
/* 1AB600 80399580 8FBF0018 */  lw         $ra, 0x18($sp)
/* 1AB604 80399584 8FB10014 */  lw         $s1, 0x14($sp)
/* 1AB608 80399588 8FB00010 */  lw         $s0, 0x10($sp)
/* 1AB60C 8039958C 27BD0020 */  addiu      $sp, $sp, 0x20
/* 1AB610 80399590 03E00008 */  jr         $ra
/* 1AB614 80399594 00000000 */   nop
.size D_80399408, . - D_80399408

glabel func_80399598
/* 1AB618 80399598 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 1AB61C 8039959C AFB00010 */  sw         $s0, 0x10($sp)
/* 1AB620 803995A0 00808021 */  addu       $s0, $a0, $zero
/* 1AB624 803995A4 AFBF0014 */  sw         $ra, 0x14($sp)
/* 1AB628 803995A8 0C02591A */  jal        func_80096468
/* 1AB62C 803995AC 24040168 */   addiu     $a0, $zero, 0x168
/* 1AB630 803995B0 26040040 */  addiu      $a0, $s0, 0x40
/* 1AB634 803995B4 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 1AB638 803995B8 44800000 */  mtc1       $zero, $f0
/* 1AB63C 803995BC 00000000 */  nop
/* 1AB640 803995C0 44824000 */  mtc1       $v0, $f8
/* 1AB644 803995C4 00000000 */  nop
/* 1AB648 803995C8 46804220 */  cvt.s.w    $f8, $f8
/* 1AB64C 803995CC 44050000 */  mfc1       $a1, $f0
/* 1AB650 803995D0 00000000 */  nop
/* 1AB654 803995D4 44074000 */  mfc1       $a3, $f8
/* 1AB658 803995D8 00000000 */  nop
/* 1AB65C 803995DC 0C02FECA */  jal        guRotateRPY
/* 1AB660 803995E0 00A03021 */   addu      $a2, $a1, $zero
/* 1AB664 803995E4 3C01803B */  lui        $at, %hi(D_803B3EBC)
/* 1AB668 803995E8 C4203EBC */  lwc1       $f0, %lo(D_803B3EBC)($at)
/* 1AB66C 803995EC 3C04803B */  lui        $a0, %hi(D_803B3E5E)
/* 1AB670 803995F0 94843E5E */  lhu        $a0, %lo(D_803B3E5E)($a0)
/* 1AB674 803995F4 3C01803B */  lui        $at, %hi(D_803B3EB0)
/* 1AB678 803995F8 C4223EB0 */  lwc1       $f2, %lo(D_803B3EB0)($at)
/* 1AB67C 803995FC 3C01803B */  lui        $at, %hi(D_803B3E2C)
/* 1AB680 80399600 C4243E2C */  lwc1       $f4, %lo(D_803B3E2C)($at)
/* 1AB684 80399604 E6000080 */  swc1       $f0, 0x80($s0)
/* 1AB688 80399608 E6020084 */  swc1       $f2, 0x84($s0)
/* 1AB68C 8039960C 0C02591A */  jal        func_80096468
/* 1AB690 80399610 E6040088 */   swc1      $f4, 0x88($s0)
/* 1AB694 80399614 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 1AB698 80399618 44811000 */  mtc1       $at, $f2
/* 1AB69C 8039961C 00000000 */  nop
/* 1AB6A0 80399620 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 1AB6A4 80399624 44820000 */  mtc1       $v0, $f0
/* 1AB6A8 80399628 00000000 */  nop
/* 1AB6AC 8039962C 46800020 */  cvt.s.w    $f0, $f0
/* 1AB6B0 80399630 46020083 */  div.s      $f2, $f0, $f2
/* 1AB6B4 80399634 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1AB6B8 80399638 44810000 */  mtc1       $at, $f0
/* 1AB6BC 8039963C 00000000 */  nop
/* 1AB6C0 80399640 4602003E */  c.le.s     $f0, $f2
/* 1AB6C4 80399644 00000000 */  nop
/* 1AB6C8 80399648 00000000 */  nop
/* 1AB6CC 8039964C 45030006 */  bc1tl      .L80399668_ovl8
/* 1AB6D0 80399650 46001001 */   sub.s     $f0, $f2, $f0
/* 1AB6D4 80399654 4600100D */  trunc.w.s  $f0, $f2
/* 1AB6D8 80399658 44040000 */  mfc1       $a0, $f0
/* 1AB6DC 8039965C 00000000 */  nop
/* 1AB6E0 80399660 080E659F */  j          .L8039967C_ovl8
/* 1AB6E4 80399664 00000000 */   nop
.L80399668_ovl8:
/* 1AB6E8 80399668 4600008D */  trunc.w.s  $f2, $f0
/* 1AB6EC 8039966C 44041000 */  mfc1       $a0, $f2
/* 1AB6F0 80399670 00000000 */  nop
/* 1AB6F4 80399674 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1AB6F8 80399678 00822025 */  or         $a0, $a0, $v0
.L8039967C_ovl8:
/* 1AB6FC 8039967C 0C02592F */  jal        func_800964BC
/* 1AB700 80399680 00000000 */   nop
/* 1AB704 80399684 3C04803B */  lui        $a0, %hi(D_803B3E5E)
/* 1AB708 80399688 94843E5E */  lhu        $a0, %lo(D_803B3E5E)($a0)
/* 1AB70C 8039968C 44820000 */  mtc1       $v0, $f0
/* 1AB710 80399690 00000000 */  nop
/* 1AB714 80399694 46800020 */  cvt.s.w    $f0, $f0
/* 1AB718 80399698 0C02591A */  jal        func_80096468
/* 1AB71C 8039969C E600008C */   swc1      $f0, 0x8C($s0)
/* 1AB720 803996A0 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 1AB724 803996A4 44811000 */  mtc1       $at, $f2
/* 1AB728 803996A8 00000000 */  nop
/* 1AB72C 803996AC 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 1AB730 803996B0 44820000 */  mtc1       $v0, $f0
/* 1AB734 803996B4 00000000 */  nop
/* 1AB738 803996B8 46800020 */  cvt.s.w    $f0, $f0
/* 1AB73C 803996BC 46020083 */  div.s      $f2, $f0, $f2
/* 1AB740 803996C0 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1AB744 803996C4 44810000 */  mtc1       $at, $f0
/* 1AB748 803996C8 00000000 */  nop
/* 1AB74C 803996CC 4602003E */  c.le.s     $f0, $f2
/* 1AB750 803996D0 00000000 */  nop
/* 1AB754 803996D4 00000000 */  nop
/* 1AB758 803996D8 45030006 */  bc1tl      .L803996F4_ovl8
/* 1AB75C 803996DC 46001001 */   sub.s     $f0, $f2, $f0
/* 1AB760 803996E0 4600100D */  trunc.w.s  $f0, $f2
/* 1AB764 803996E4 44040000 */  mfc1       $a0, $f0
/* 1AB768 803996E8 00000000 */  nop
/* 1AB76C 803996EC 080E65C2 */  j          .L80399708_ovl8
/* 1AB770 803996F0 00000000 */   nop
.L803996F4_ovl8:
/* 1AB774 803996F4 4600008D */  trunc.w.s  $f2, $f0
/* 1AB778 803996F8 44041000 */  mfc1       $a0, $f2
/* 1AB77C 803996FC 00000000 */  nop
/* 1AB780 80399700 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1AB784 80399704 00822025 */  or         $a0, $a0, $v0
.L80399708_ovl8:
/* 1AB788 80399708 0C02592F */  jal        func_800964BC
/* 1AB78C 8039970C 00000000 */   nop
/* 1AB790 80399710 3C04803B */  lui        $a0, %hi(D_803B3E5E)
/* 1AB794 80399714 94843E5E */  lhu        $a0, %lo(D_803B3E5E)($a0)
/* 1AB798 80399718 44820000 */  mtc1       $v0, $f0
/* 1AB79C 8039971C 00000000 */  nop
/* 1AB7A0 80399720 46800020 */  cvt.s.w    $f0, $f0
/* 1AB7A4 80399724 0C02591A */  jal        func_80096468
/* 1AB7A8 80399728 E6000090 */   swc1      $f0, 0x90($s0)
/* 1AB7AC 8039972C 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 1AB7B0 80399730 44811000 */  mtc1       $at, $f2
/* 1AB7B4 80399734 00000000 */  nop
/* 1AB7B8 80399738 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 1AB7BC 8039973C 44820000 */  mtc1       $v0, $f0
/* 1AB7C0 80399740 00000000 */  nop
/* 1AB7C4 80399744 46800020 */  cvt.s.w    $f0, $f0
/* 1AB7C8 80399748 46020083 */  div.s      $f2, $f0, $f2
/* 1AB7CC 8039974C 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1AB7D0 80399750 44810000 */  mtc1       $at, $f0
/* 1AB7D4 80399754 00000000 */  nop
/* 1AB7D8 80399758 4602003E */  c.le.s     $f0, $f2
/* 1AB7DC 8039975C 00000000 */  nop
/* 1AB7E0 80399760 00000000 */  nop
/* 1AB7E4 80399764 45030006 */  bc1tl      .L80399780_ovl8
/* 1AB7E8 80399768 46001001 */   sub.s     $f0, $f2, $f0
/* 1AB7EC 8039976C 4600100D */  trunc.w.s  $f0, $f2
/* 1AB7F0 80399770 44040000 */  mfc1       $a0, $f0
/* 1AB7F4 80399774 00000000 */  nop
/* 1AB7F8 80399778 080E65E5 */  j          .L80399794_ovl8
/* 1AB7FC 8039977C 00000000 */   nop
.L80399780_ovl8:
/* 1AB800 80399780 4600008D */  trunc.w.s  $f2, $f0
/* 1AB804 80399784 44041000 */  mfc1       $a0, $f2
/* 1AB808 80399788 00000000 */  nop
/* 1AB80C 8039978C 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1AB810 80399790 00822025 */  or         $a0, $a0, $v0
.L80399794_ovl8:
/* 1AB814 80399794 0C02592F */  jal        func_800964BC
/* 1AB818 80399798 00000000 */   nop
/* 1AB81C 8039979C 3C03803B */  lui        $v1, %hi(D_803B3EA8)
/* 1AB820 803997A0 8C633EA8 */  lw         $v1, %lo(D_803B3EA8)($v1)
/* 1AB824 803997A4 3C014110 */  lui        $at, (0x41100000 >> 16)
/* 1AB828 803997A8 44812000 */  mtc1       $at, $f4
/* 1AB82C 803997AC 00000000 */  nop
/* 1AB830 803997B0 44831000 */  mtc1       $v1, $f2
/* 1AB834 803997B4 00000000 */  nop
/* 1AB838 803997B8 468010A0 */  cvt.s.w    $f2, $f2
/* 1AB83C 803997BC 46022103 */  div.s      $f4, $f4, $f2
/* 1AB840 803997C0 3C01437F */  lui        $at, (0x437F0000 >> 16)
/* 1AB844 803997C4 44813000 */  mtc1       $at, $f6
/* 1AB848 803997C8 00000000 */  nop
/* 1AB84C 803997CC 46023083 */  div.s      $f2, $f6, $f2
/* 1AB850 803997D0 44820000 */  mtc1       $v0, $f0
/* 1AB854 803997D4 00000000 */  nop
/* 1AB858 803997D8 46800020 */  cvt.s.w    $f0, $f0
/* 1AB85C 803997DC E6000094 */  swc1       $f0, 0x94($s0)
/* 1AB860 803997E0 3C01803B */  lui        $at, %hi(D_803B3E20)
/* 1AB864 803997E4 C4203E20 */  lwc1       $f0, %lo(D_803B3E20)($at)
/* 1AB868 803997E8 46800020 */  cvt.s.w    $f0, $f0
/* 1AB86C 803997EC E6000098 */  swc1       $f0, 0x98($s0)
/* 1AB870 803997F0 AE00009C */  sw         $zero, 0x9C($s0)
/* 1AB874 803997F4 AE0000A0 */  sw         $zero, 0xA0($s0)
/* 1AB878 803997F8 A60300A8 */  sh         $v1, 0xA8($s0)
/* 1AB87C 803997FC E60600AC */  swc1       $f6, 0xAC($s0)
/* 1AB880 80399800 E60400A4 */  swc1       $f4, 0xA4($s0)
/* 1AB884 80399804 E60200B0 */  swc1       $f2, 0xB0($s0)
/* 1AB888 80399808 8FBF0014 */  lw         $ra, 0x14($sp)
/* 1AB88C 8039980C 8FB00010 */  lw         $s0, 0x10($sp)
/* 1AB890 80399810 27BD0018 */  addiu      $sp, $sp, 0x18
/* 1AB894 80399814 03E00008 */  jr         $ra
/* 1AB898 80399818 00000000 */   nop
.size func_80399598, . - func_80399598

glabel func_8039981C
/* 1AB89C 8039981C 03E00008 */  jr         $ra
/* 1AB8A0 80399820 00000000 */   nop
.size func_8039981C, . - func_8039981C

glabel func_80399824
/* 1AB8A4 80399824 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 1AB8A8 80399828 AFB00028 */  sw         $s0, 0x28($sp)
/* 1AB8AC 8039982C 00808021 */  addu       $s0, $a0, $zero
/* 1AB8B0 80399830 AFBF002C */  sw         $ra, 0x2C($sp)
/* 1AB8B4 80399834 860200A8 */  lh         $v0, 0xA8($s0)
/* 1AB8B8 80399838 1040011C */  beqz       $v0, .L80399CAC_ovl8
/* 1AB8BC 8039983C 00401821 */   addu      $v1, $v0, $zero
/* 1AB8C0 80399840 2463FFFF */  addiu      $v1, $v1, -0x1
/* 1AB8C4 80399844 3C0AD9FD */  lui        $t2, (0xD9FDFFFF >> 16)
/* 1AB8C8 80399848 354AFFFF */  ori        $t2, $t2, (0xD9FDFFFF & 0xFFFF)
/* 1AB8CC 8039984C 3C0BD9FF */  lui        $t3, (0xD9FFFFFF >> 16)
/* 1AB8D0 80399850 356BFFFF */  ori        $t3, $t3, (0xD9FFFFFF & 0xFFFF)
/* 1AB8D4 80399854 3C080020 */  lui        $t0, (0x200405 >> 16)
/* 1AB8D8 80399858 35080405 */  ori        $t0, $t0, (0x200405 & 0xFFFF)
/* 1AB8DC 8039985C 3C06E300 */  lui        $a2, (0xE3001201 >> 16)
/* 1AB8E0 80399860 34C61201 */  ori        $a2, $a2, (0xE3001201 & 0xFFFF)
/* 1AB8E4 80399864 3C09E200 */  lui        $t1, (0xE200001C >> 16)
/* 1AB8E8 80399868 3529001C */  ori        $t1, $t1, (0xE200001C & 0xFFFF)
/* 1AB8EC 8039986C 3C070050 */  lui        $a3, (0x504B50 >> 16)
/* 1AB8F0 80399870 34E74B50 */  ori        $a3, $a3, (0x504B50 & 0xFFFF)
/* 1AB8F4 80399874 3C05FC11 */  lui        $a1, (0xFC119623 >> 16)
/* 1AB8F8 80399878 34A59623 */  ori        $a1, $a1, (0xFC119623 & 0xFFFF)
/* 1AB8FC 8039987C 3C028015 */  lui        $v0, %hi(gDisplayListHead)
/* 1AB900 80399880 8C429F94 */  lw         $v0, %lo(gDisplayListHead)($v0)
/* 1AB904 80399884 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 1AB908 80399888 44810000 */  mtc1       $at, $f0
/* 1AB90C 8039988C 00000000 */  nop
/* 1AB910 80399890 3C04FF2F */  lui        $a0, (0xFF2FFFFF >> 16)
/* 1AB914 80399894 3484FFFF */  ori        $a0, $a0, (0xFF2FFFFF & 0xFFFF)
/* 1AB918 80399898 A60300A8 */  sh         $v1, 0xA8($s0)
/* 1AB91C 8039989C 3C03DE00 */  lui        $v1, (0xDE000000 >> 16)
/* 1AB920 803998A0 AC430000 */  sw         $v1, 0x0($v0)
/* 1AB924 803998A4 3C03800D */  lui        $v1, %hi(D_800D3D70)
/* 1AB928 803998A8 24633D70 */  addiu      $v1, $v1, %lo(D_800D3D70)
/* 1AB92C 803998AC AC430004 */  sw         $v1, 0x4($v0)
/* 1AB930 803998B0 24032000 */  addiu      $v1, $zero, 0x2000
/* 1AB934 803998B4 AC43001C */  sw         $v1, 0x1C($v0)
/* 1AB938 803998B8 3C03FA00 */  lui        $v1, (0xFA000000 >> 16)
/* 1AB93C 803998BC AC4A0008 */  sw         $t2, 0x8($v0)
/* 1AB940 803998C0 AC40000C */  sw         $zero, 0xC($v0)
/* 1AB944 803998C4 AC4B0010 */  sw         $t3, 0x10($v0)
/* 1AB948 803998C8 AC480014 */  sw         $t0, 0x14($v0)
/* 1AB94C 803998CC AC460018 */  sw         $a2, 0x18($v0)
/* 1AB950 803998D0 AC490020 */  sw         $t1, 0x20($v0)
/* 1AB954 803998D4 AC470024 */  sw         $a3, 0x24($v0)
/* 1AB958 803998D8 AC450028 */  sw         $a1, 0x28($v0)
/* 1AB95C 803998DC AC44002C */  sw         $a0, 0x2C($v0)
/* 1AB960 803998E0 AC430030 */  sw         $v1, 0x30($v0)
/* 1AB964 803998E4 C60200AC */  lwc1       $f2, 0xAC($s0)
/* 1AB968 803998E8 24430008 */  addiu      $v1, $v0, 0x8
/* 1AB96C 803998EC 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB970 803998F0 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1AB974 803998F4 24430010 */  addiu      $v1, $v0, 0x10
/* 1AB978 803998F8 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB97C 803998FC AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1AB980 80399900 24430018 */  addiu      $v1, $v0, 0x18
/* 1AB984 80399904 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB988 80399908 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1AB98C 8039990C 24430020 */  addiu      $v1, $v0, 0x20
/* 1AB990 80399910 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB994 80399914 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1AB998 80399918 24430028 */  addiu      $v1, $v0, 0x28
/* 1AB99C 8039991C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB9A0 80399920 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1AB9A4 80399924 24430030 */  addiu      $v1, $v0, 0x30
/* 1AB9A8 80399928 24420038 */  addiu      $v0, $v0, 0x38
/* 1AB9AC 8039992C 4602003E */  c.le.s     $f0, $f2
/* 1AB9B0 80399930 00000000 */  nop
/* 1AB9B4 80399934 00000000 */  nop
/* 1AB9B8 80399938 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB9BC 8039993C AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1AB9C0 80399940 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1AB9C4 80399944 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1AB9C8 80399948 45030006 */  bc1tl      .L80399964_ovl8
/* 1AB9CC 8039994C 46001001 */   sub.s     $f0, $f2, $f0
/* 1AB9D0 80399950 4600100D */  trunc.w.s  $f0, $f2
/* 1AB9D4 80399954 44040000 */  mfc1       $a0, $f0
/* 1AB9D8 80399958 00000000 */  nop
/* 1AB9DC 8039995C 080E665F */  j          .L8039997C_ovl8
/* 1AB9E0 80399960 2402FF00 */   addiu     $v0, $zero, -0x100
.L80399964_ovl8:
/* 1AB9E4 80399964 4600008D */  trunc.w.s  $f2, $f0
/* 1AB9E8 80399968 44041000 */  mfc1       $a0, $f2
/* 1AB9EC 8039996C 00000000 */  nop
/* 1AB9F0 80399970 3C028000 */  lui        $v0, (0x80000000 >> 16)
/* 1AB9F4 80399974 00822025 */  or         $a0, $a0, $v0
/* 1AB9F8 80399978 2402FF00 */  addiu      $v0, $zero, -0x100
.L8039997C_ovl8:
/* 1AB9FC 8039997C 00821025 */  or         $v0, $a0, $v0
/* 1ABA00 80399980 AC620004 */  sw         $v0, 0x4($v1)
/* 1ABA04 80399984 C60200AC */  lwc1       $f2, 0xAC($s0)
/* 1ABA08 80399988 C60000B0 */  lwc1       $f0, 0xB0($s0)
/* 1ABA0C 8039998C 46001081 */  sub.s      $f2, $f2, $f0
/* 1ABA10 80399990 3C01437F */  lui        $at, (0x437F0000 >> 16)
/* 1ABA14 80399994 44810000 */  mtc1       $at, $f0
/* 1ABA18 80399998 00000000 */  nop
/* 1ABA1C 8039999C 4602003C */  c.lt.s     $f0, $f2
/* 1ABA20 803999A0 00000000 */  nop
/* 1ABA24 803999A4 00000000 */  nop
/* 1ABA28 803999A8 45010008 */  bc1t       .L803999CC_ovl8
/* 1ABA2C 803999AC E60200AC */   swc1      $f2, 0xAC($s0)
/* 1ABA30 803999B0 44800000 */  mtc1       $zero, $f0
/* 1ABA34 803999B4 00000000 */  nop
/* 1ABA38 803999B8 4600103C */  c.lt.s     $f2, $f0
/* 1ABA3C 803999BC 00000000 */  nop
/* 1ABA40 803999C0 00000000 */  nop
/* 1ABA44 803999C4 45000003 */  bc1f       .L803999D4_ovl8
/* 1ABA48 803999C8 3C02E300 */   lui       $v0, (0xE3001001 >> 16)
.L803999CC_ovl8:
/* 1ABA4C 803999CC E60000AC */  swc1       $f0, 0xAC($s0)
/* 1ABA50 803999D0 3C02E300 */  lui        $v0, (0xE3001001 >> 16)
.L803999D4_ovl8:
/* 1ABA54 803999D4 34421001 */  ori        $v0, $v0, (0xE3001001 & 0xFFFF)
/* 1ABA58 803999D8 3C04F500 */  lui        $a0, (0xF5000100 >> 16)
/* 1ABA5C 803999DC 34840100 */  ori        $a0, $a0, (0xF5000100 & 0xFFFF)
/* 1ABA60 803999E0 3C070703 */  lui        $a3, (0x703C000 >> 16)
/* 1ABA64 803999E4 34E7C000 */  ori        $a3, $a3, (0x703C000 & 0xFFFF)
/* 1ABA68 803999E8 3C080701 */  lui        $t0, (0x7018060 >> 16)
/* 1ABA6C 803999EC 35088060 */  ori        $t0, $t0, (0x7018060 & 0xFFFF)
/* 1ABA70 803999F0 3C09073F */  lui        $t1, (0x73FF200 >> 16)
/* 1ABA74 803999F4 3529F200 */  ori        $t1, $t1, (0x73FF200 & 0xFFFF)
/* 1ABA78 803999F8 3C0CF540 */  lui        $t4, (0xF5400800 >> 16)
/* 1ABA7C 803999FC 358C0800 */  ori        $t4, $t4, (0xF5400800 & 0xFFFF)
/* 1ABA80 80399A00 3C0A0001 */  lui        $t2, (0x18060 >> 16)
/* 1ABA84 80399A04 354A8060 */  ori        $t2, $t2, (0x18060 & 0xFFFF)
/* 1ABA88 80399A08 3C038015 */  lui        $v1, %hi(gDisplayListHead)
/* 1ABA8C 80399A0C 8C639F94 */  lw         $v1, %lo(gDisplayListHead)($v1)
/* 1ABA90 80399A10 3C0B000F */  lui        $t3, (0xFC0FC >> 16)
/* 1ABA94 80399A14 3C05E700 */  lui        $a1, (0xE7000000 >> 16)
/* 1ABA98 80399A18 3C06E600 */  lui        $a2, (0xE6000000 >> 16)
/* 1ABA9C 80399A1C AC620008 */  sw         $v0, 0x8($v1)
/* 1ABAA0 80399A20 34028000 */  ori        $v0, $zero, 0x8000
/* 1ABAA4 80399A24 AC62000C */  sw         $v0, 0xC($v1)
/* 1ABAA8 80399A28 3C02FD10 */  lui        $v0, (0xFD100000 >> 16)
/* 1ABAAC 80399A2C AC620010 */  sw         $v0, 0x10($v1)
/* 1ABAB0 80399A30 3C02803B */  lui        $v0, %hi(D_803AE450)
/* 1ABAB4 80399A34 2442E450 */  addiu      $v0, $v0, %lo(D_803AE450)
/* 1ABAB8 80399A38 AC620014 */  sw         $v0, 0x14($v1)
/* 1ABABC 80399A3C 3C02E800 */  lui        $v0, (0xE8000000 >> 16)
/* 1ABAC0 80399A40 AC620018 */  sw         $v0, 0x18($v1)
/* 1ABAC4 80399A44 3C020700 */  lui        $v0, (0x7000000 >> 16)
/* 1ABAC8 80399A48 AC620024 */  sw         $v0, 0x24($v1)
/* 1ABACC 80399A4C 3C02F000 */  lui        $v0, (0xF0000000 >> 16)
/* 1ABAD0 80399A50 AC650000 */  sw         $a1, 0x0($v1)
/* 1ABAD4 80399A54 AC600004 */  sw         $zero, 0x4($v1)
/* 1ABAD8 80399A58 AC60001C */  sw         $zero, 0x1C($v1)
/* 1ABADC 80399A5C AC640020 */  sw         $a0, 0x20($v1)
/* 1ABAE0 80399A60 AC660028 */  sw         $a2, 0x28($v1)
/* 1ABAE4 80399A64 AC60002C */  sw         $zero, 0x2C($v1)
/* 1ABAE8 80399A68 AC620030 */  sw         $v0, 0x30($v1)
/* 1ABAEC 80399A6C AC670034 */  sw         $a3, 0x34($v1)
/* 1ABAF0 80399A70 AC650038 */  sw         $a1, 0x38($v1)
/* 1ABAF4 80399A74 AC60003C */  sw         $zero, 0x3C($v1)
/* 1ABAF8 80399A78 C60000A0 */  lwc1       $f0, 0xA0($s0)
/* 1ABAFC 80399A7C 356BC0FC */  ori        $t3, $t3, (0xFC0FC & 0xFFFF)
/* 1ABB00 80399A80 24620008 */  addiu      $v0, $v1, 0x8
/* 1ABB04 80399A84 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB08 80399A88 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB0C 80399A8C 24620010 */  addiu      $v0, $v1, 0x10
/* 1ABB10 80399A90 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB14 80399A94 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB18 80399A98 24620018 */  addiu      $v0, $v1, 0x18
/* 1ABB1C 80399A9C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB20 80399AA0 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB24 80399AA4 24620020 */  addiu      $v0, $v1, 0x20
/* 1ABB28 80399AA8 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB2C 80399AAC AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB30 80399AB0 24620028 */  addiu      $v0, $v1, 0x28
/* 1ABB34 80399AB4 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB38 80399AB8 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB3C 80399ABC 24620030 */  addiu      $v0, $v1, 0x30
/* 1ABB40 80399AC0 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB44 80399AC4 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB48 80399AC8 24620038 */  addiu      $v0, $v1, 0x38
/* 1ABB4C 80399ACC 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB50 80399AD0 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB54 80399AD4 24620040 */  addiu      $v0, $v1, 0x40
/* 1ABB58 80399AD8 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB5C 80399ADC AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB60 80399AE0 24620048 */  addiu      $v0, $v1, 0x48
/* 1ABB64 80399AE4 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB68 80399AE8 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB6C 80399AEC 3C02FD50 */  lui        $v0, (0xFD500000 >> 16)
/* 1ABB70 80399AF0 AC620040 */  sw         $v0, 0x40($v1)
/* 1ABB74 80399AF4 24620050 */  addiu      $v0, $v1, 0x50
/* 1ABB78 80399AF8 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB7C 80399AFC AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB80 80399B00 3C02F550 */  lui        $v0, (0xF5500000 >> 16)
/* 1ABB84 80399B04 AC620048 */  sw         $v0, 0x48($v1)
/* 1ABB88 80399B08 24620058 */  addiu      $v0, $v1, 0x58
/* 1ABB8C 80399B0C AC68004C */  sw         $t0, 0x4C($v1)
/* 1ABB90 80399B10 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABB94 80399B14 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABB98 80399B18 4600008D */  trunc.w.s  $f2, $f0
/* 1ABB9C 80399B1C 44041000 */  mfc1       $a0, $f2
/* 1ABBA0 80399B20 00000000 */  nop
/* 1ABBA4 80399B24 000411C0 */  sll        $v0, $a0, 7
/* 1ABBA8 80399B28 00441021 */  addu       $v0, $v0, $a0
/* 1ABBAC 80399B2C 00021100 */  sll        $v0, $v0, 4
/* 1ABBB0 80399B30 3C04803B */  lui        $a0, %hi(D_803AE480)
/* 1ABBB4 80399B34 2484E480 */  addiu      $a0, $a0, %lo(D_803AE480)
/* 1ABBB8 80399B38 00441021 */  addu       $v0, $v0, $a0
/* 1ABBBC 80399B3C AC620044 */  sw         $v0, 0x44($v1)
/* 1ABBC0 80399B40 3C02F300 */  lui        $v0, (0xF3000000 >> 16)
/* 1ABBC4 80399B44 AC660050 */  sw         $a2, 0x50($v1)
/* 1ABBC8 80399B48 AC620058 */  sw         $v0, 0x58($v1)
/* 1ABBCC 80399B4C 3C02F200 */  lui        $v0, (0xF2000000 >> 16)
/* 1ABBD0 80399B50 AC600054 */  sw         $zero, 0x54($v1)
/* 1ABBD4 80399B54 AC69005C */  sw         $t1, 0x5C($v1)
/* 1ABBD8 80399B58 AC650060 */  sw         $a1, 0x60($v1)
/* 1ABBDC 80399B5C AC600064 */  sw         $zero, 0x64($v1)
/* 1ABBE0 80399B60 AC6C0068 */  sw         $t4, 0x68($v1)
/* 1ABBE4 80399B64 AC6A006C */  sw         $t2, 0x6C($v1)
/* 1ABBE8 80399B68 AC620070 */  sw         $v0, 0x70($v1)
/* 1ABBEC 80399B6C AC6B0074 */  sw         $t3, 0x74($v1)
/* 1ABBF0 80399B70 C6000098 */  lwc1       $f0, 0x98($s0)
/* 1ABBF4 80399B74 3C058015 */  lui        $a1, %hi(D_8014A07C)
/* 1ABBF8 80399B78 8CA5A07C */  lw         $a1, %lo(D_8014A07C)($a1)
/* 1ABBFC 80399B7C 3C068015 */  lui        $a2, %hi(D_8014A080)
/* 1ABC00 80399B80 8CC6A080 */  lw         $a2, %lo(D_8014A080)($a2)
/* 1ABC04 80399B84 3C078015 */  lui        $a3, %hi(D_8014A084)
/* 1ABC08 80399B88 8CE7A084 */  lw         $a3, %lo(D_8014A084)($a3)
/* 1ABC0C 80399B8C E7A00010 */  swc1       $f0, 0x10($sp)
/* 1ABC10 80399B90 C6000080 */  lwc1       $f0, 0x80($s0)
/* 1ABC14 80399B94 E7A00014 */  swc1       $f0, 0x14($sp)
/* 1ABC18 80399B98 C6000084 */  lwc1       $f0, 0x84($s0)
/* 1ABC1C 80399B9C 24620060 */  addiu      $v0, $v1, 0x60
/* 1ABC20 80399BA0 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABC24 80399BA4 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABC28 80399BA8 24620068 */  addiu      $v0, $v1, 0x68
/* 1ABC2C 80399BAC 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABC30 80399BB0 AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABC34 80399BB4 24620070 */  addiu      $v0, $v1, 0x70
/* 1ABC38 80399BB8 E7A00018 */  swc1       $f0, 0x18($sp)
/* 1ABC3C 80399BBC C6000088 */  lwc1       $f0, 0x88($s0)
/* 1ABC40 80399BC0 24630078 */  addiu      $v1, $v1, 0x78
/* 1ABC44 80399BC4 02002021 */  addu       $a0, $s0, $zero
/* 1ABC48 80399BC8 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABC4C 80399BCC AC229F94 */  sw         $v0, %lo(gDisplayListHead)($at)
/* 1ABC50 80399BD0 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABC54 80399BD4 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1ABC58 80399BD8 0C02FD0E */  jal        guPosition
/* 1ABC5C 80399BDC E7A0001C */   swc1      $f0, 0x1C($sp)
/* 1ABC60 80399BE0 3C03DA38 */  lui        $v1, (0xDA380003 >> 16)
/* 1ABC64 80399BE4 34630003 */  ori        $v1, $v1, (0xDA380003 & 0xFFFF)
/* 1ABC68 80399BE8 3C048015 */  lui        $a0, %hi(gDisplayListHead)
/* 1ABC6C 80399BEC 8C849F94 */  lw         $a0, %lo(gDisplayListHead)($a0)
/* 1ABC70 80399BF0 3C01803B */  lui        $at, %hi(D_803B3E58)
/* 1ABC74 80399BF4 C4203E58 */  lwc1       $f0, %lo(D_803B3E58)($at)
/* 1ABC78 80399BF8 3C05DA38 */  lui        $a1, (0xDA380001 >> 16)
/* 1ABC7C 80399BFC 34A50001 */  ori        $a1, $a1, (0xDA380001 & 0xFFFF)
/* 1ABC80 80399C00 AC830000 */  sw         $v1, 0x0($a0)
/* 1ABC84 80399C04 26030040 */  addiu      $v1, $s0, 0x40
/* 1ABC88 80399C08 AC83000C */  sw         $v1, 0xC($a0)
/* 1ABC8C 80399C0C 3C03DE00 */  lui        $v1, (0xDE000000 >> 16)
/* 1ABC90 80399C10 AC830010 */  sw         $v1, 0x10($a0)
/* 1ABC94 80399C14 3C03803A */  lui        $v1, %hi(D_803A2020)
/* 1ABC98 80399C18 24632020 */  addiu      $v1, $v1, %lo(D_803A2020)
/* 1ABC9C 80399C1C AC900004 */  sw         $s0, 0x4($a0)
/* 1ABCA0 80399C20 AC850008 */  sw         $a1, 0x8($a0)
/* 1ABCA4 80399C24 AC830014 */  sw         $v1, 0x14($a0)
/* 1ABCA8 80399C28 C6040080 */  lwc1       $f4, 0x80($s0)
/* 1ABCAC 80399C2C 00001021 */  addu       $v0, $zero, $zero
/* 1ABCB0 80399C30 C60A0084 */  lwc1       $f10, 0x84($s0)
/* 1ABCB4 80399C34 46002100 */  add.s      $f4, $f4, $f0
/* 1ABCB8 80399C38 C6020090 */  lwc1       $f2, 0x90($s0)
/* 1ABCBC 80399C3C C6080088 */  lwc1       $f8, 0x88($s0)
/* 1ABCC0 80399C40 C6060098 */  lwc1       $f6, 0x98($s0)
/* 1ABCC4 80399C44 46025280 */  add.s      $f10, $f10, $f2
/* 1ABCC8 80399C48 C6000094 */  lwc1       $f0, 0x94($s0)
/* 1ABCCC 80399C4C C60C008C */  lwc1       $f12, 0x8C($s0)
/* 1ABCD0 80399C50 C602009C */  lwc1       $f2, 0x9C($s0)
/* 1ABCD4 80399C54 46004200 */  add.s      $f8, $f8, $f0
/* 1ABCD8 80399C58 24830008 */  addiu      $v1, $a0, 0x8
/* 1ABCDC 80399C5C 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABCE0 80399C60 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1ABCE4 80399C64 C60000A0 */  lwc1       $f0, 0xA0($s0)
/* 1ABCE8 80399C68 46023180 */  add.s      $f6, $f6, $f2
/* 1ABCEC 80399C6C C60200A4 */  lwc1       $f2, 0xA4($s0)
/* 1ABCF0 80399C70 24830010 */  addiu      $v1, $a0, 0x10
/* 1ABCF4 80399C74 24840018 */  addiu      $a0, $a0, 0x18
/* 1ABCF8 80399C78 E6040080 */  swc1       $f4, 0x80($s0)
/* 1ABCFC 80399C7C 460C2100 */  add.s      $f4, $f4, $f12
/* 1ABD00 80399C80 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABD04 80399C84 AC239F94 */  sw         $v1, %lo(gDisplayListHead)($at)
/* 1ABD08 80399C88 3C018015 */  lui        $at, %hi(gDisplayListHead)
/* 1ABD0C 80399C8C AC249F94 */  sw         $a0, %lo(gDisplayListHead)($at)
/* 1ABD10 80399C90 E60A0084 */  swc1       $f10, 0x84($s0)
/* 1ABD14 80399C94 46020000 */  add.s      $f0, $f0, $f2
/* 1ABD18 80399C98 E6080088 */  swc1       $f8, 0x88($s0)
/* 1ABD1C 80399C9C E6060098 */  swc1       $f6, 0x98($s0)
/* 1ABD20 80399CA0 E6040080 */  swc1       $f4, 0x80($s0)
/* 1ABD24 80399CA4 080E672C */  j          .L80399CB0_ovl8
/* 1ABD28 80399CA8 E60000A0 */   swc1      $f0, 0xA0($s0)
.L80399CAC_ovl8:
/* 1ABD2C 80399CAC 24020001 */  addiu      $v0, $zero, 0x1
.L80399CB0_ovl8:
/* 1ABD30 80399CB0 8FBF002C */  lw         $ra, 0x2C($sp)
/* 1ABD34 80399CB4 8FB00028 */  lw         $s0, 0x28($sp)
/* 1ABD38 80399CB8 27BD0030 */  addiu      $sp, $sp, 0x30
/* 1ABD3C 80399CBC 03E00008 */  jr         $ra
/* 1ABD40 80399CC0 00000000 */   nop
.size func_80399824, . - func_80399824

glabel func_80399CC4
/* 1ABD44 80399CC4 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 1ABD48 80399CC8 00042400 */  sll        $a0, $a0, 16
/* 1ABD4C 80399CCC 00042403 */  sra        $a0, $a0, 16
/* 1ABD50 80399CD0 00052C00 */  sll        $a1, $a1, 16
/* 1ABD54 80399CD4 00052C03 */  sra        $a1, $a1, 16
/* 1ABD58 80399CD8 00063400 */  sll        $a2, $a2, 16
/* 1ABD5C 80399CDC 00063403 */  sra        $a2, $a2, 16
/* 1ABD60 80399CE0 3C01803B */  lui        $at, %hi(D_803B3EA8)
/* 1ABD64 80399CE4 AC243EA8 */  sw         $a0, %lo(D_803B3EA8)($at)
/* 1ABD68 80399CE8 3C04803A */  lui        $a0, %hi(D_80399408)
/* 1ABD6C 80399CEC 24849408 */  addiu      $a0, $a0, %lo(D_80399408)
/* 1ABD70 80399CF0 3C01803B */  lui        $at, %hi(D_803B3E20)
/* 1ABD74 80399CF4 AC253E20 */  sw         $a1, %lo(D_803B3E20)($at)
/* 1ABD78 80399CF8 24050001 */  addiu      $a1, $zero, 0x1
/* 1ABD7C 80399CFC 3C01803B */  lui        $at, %hi(D_803B3E5C)
/* 1ABD80 80399D00 AC263E5C */  sw         $a2, %lo(D_803B3E5C)($at)
/* 1ABD84 80399D04 24060136 */  addiu      $a2, $zero, 0x136
/* 1ABD88 80399D08 AFBF0010 */  sw         $ra, 0x10($sp)
/* 1ABD8C 80399D0C 0C025D06 */  jal        func_80097418
/* 1ABD90 80399D10 24070001 */   addiu     $a3, $zero, 0x1
/* 1ABD94 80399D14 8FBF0010 */  lw         $ra, 0x10($sp)
/* 1ABD98 80399D18 27BD0018 */  addiu      $sp, $sp, 0x18
/* 1ABD9C 80399D1C 03E00008 */  jr         $ra
/* 1ABDA0 80399D20 00000000 */   nop
/* 1ABDA4 80399D24 00000000 */  nop
/* 1ABDA8 80399D28 00000000 */  nop
/* 1ABDAC 80399D2C 00000000 */  nop
.size func_80399CC4, . - func_80399CC4
