.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.18.0 */

glabel func_80029E10
/* 11BC10 80029E10 3C028005 */  lui        $v0, %hi(func_800519E8 + 0x8)
/* 11BC14 80029E14 904219F0 */  lbu        $v0, %lo(func_800519E8 + 0x8)($v0)
/* 11BC18 80029E18 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 11BC1C 80029E1C AFB00018 */  sw         $s0, 0x18($sp)
glabel func_80029E20
/* 11BC20 80029E20 00808021 */  addu       $s0, $a0, $zero
/* 11BC24 80029E24 1040003B */  beqz       $v0, .L80029F14
.L80029E28:
/* 11BC28 80029E28 AFBF001C */   sw        $ra, 0x1C($sp)
/* 11BC2C 80029E2C 0C02A5D2 */  jal        func_800A9748
/* 11BC30 80029E30 24040001 */   addiu     $a0, $zero, 0x1
glabel func_80029E34
/* 11BC34 80029E34 0C02725C */  jal        func_8009C970
glabel .L80029E38
/* 11BC38 80029E38 00000000 */   nop
.L80029E3C:
/* 11BC3C 80029E3C 24040053 */  addiu      $a0, $zero, 0x53
.L80029E40:
/* 11BC40 80029E40 3C014080 */  lui        $at, (0x40800000 >> 16)
.L80029E44:
/* 11BC44 80029E44 44810000 */  mtc1       $at, $f0
/* 11BC48 80029E48 3C014120 */  lui        $at, (0x41200000 >> 16)
.L80029E4C:
/* 11BC4C 80029E4C 44811000 */  mtc1       $at, $f2
/* 11BC50 80029E50 3C01C248 */  lui        $at, (0xC2480000 >> 16)
/* 11BC54 80029E54 44812000 */  mtc1       $at, $f4
/* 11BC58 80029E58 24050048 */  addiu      $a1, $zero, 0x48
.L80029E5C:
/* 11BC5C 80029E5C 240200E6 */  addiu      $v0, $zero, 0xE6
.L80029E60:
/* 11BC60 80029E60 AFA20010 */  sw         $v0, 0x10($sp)
.L80029E64:
/* 11BC64 80029E64 240200DC */  addiu      $v0, $zero, 0xDC
/* 11BC68 80029E68 24060053 */  addiu      $a2, $zero, 0x53
/* 11BC6C 80029E6C AFA20014 */  sw         $v0, 0x14($sp)
glabel func_80029E70
/* 11BC70 80029E70 3C018015 */  lui        $at, %hi(D_8014A064)
/* 11BC74 80029E74 E420A064 */  swc1       $f0, %lo(D_8014A064)($at)
/* 11BC78 80029E78 3C018015 */  lui        $at, %hi(D_8014A068)
/* 11BC7C 80029E7C E422A068 */  swc1       $f2, %lo(D_8014A068)($at)
/* 11BC80 80029E80 3C018015 */  lui        $at, %hi(D_8014A088)
/* 11BC84 80029E84 E424A088 */  swc1       $f4, %lo(D_8014A088)($at)
/* 11BC88 80029E88 0C027101 */  jal        func_8009C404
/* 11BC8C 80029E8C 240700FF */   addiu     $a3, $zero, 0xFF
/* 11BC90 80029E90 3C014170 */  lui        $at, (0x41700000 >> 16)
/* 11BC94 80029E94 44810000 */  mtc1       $at, $f0
/* 11BC98 80029E98 3C014180 */  lui        $at, (0x41800000 >> 16)
/* 11BC9C 80029E9C 44811000 */  mtc1       $at, $f2
/* 11BCA0 80029EA0 3C01C1C0 */  lui        $at, (0xC1C00000 >> 16)
/* 11BCA4 80029EA4 44812000 */  mtc1       $at, $f4
/* 11BCA8 80029EA8 3C014130 */  lui        $at, (0x41300000 >> 16)
.L80029EAC:
/* 11BCAC 80029EAC 44813000 */  mtc1       $at, $f6
/* 11BCB0 80029EB0 3C0140A0 */  lui        $at, (0x40A00000 >> 16)
.L80029EB4:
/* 11BCB4 80029EB4 44814000 */  mtc1       $at, $f8
/* 11BCB8 80029EB8 3C01C190 */  lui        $at, (0xC1900000 >> 16)
glabel func_80029EBC
/* 11BCBC 80029EBC 44815000 */  mtc1       $at, $f10
/* 11BCC0 80029EC0 3C018017 */  lui        $at, %hi(D_8016E568)
glabel func_80029EC4
/* 11BCC4 80029EC4 E420E568 */  swc1       $f0, %lo(D_8016E568)($at)
/* 11BCC8 80029EC8 3C018017 */  lui        $at, %hi(D_8016D0D0)
/* 11BCCC 80029ECC E422D0D0 */  swc1       $f2, %lo(D_8016D0D0)($at)
/* 11BCD0 80029ED0 3C018017 */  lui        $at, %hi(D_8016D0D4)
/* 11BCD4 80029ED4 E424D0D4 */  swc1       $f4, %lo(D_8016D0D4)($at)
glabel .L80029ED8
/* 11BCD8 80029ED8 3C018015 */  lui        $at, %hi(D_8014A054)
/* 11BCDC 80029EDC E426A054 */  swc1       $f6, %lo(D_8014A054)($at)
/* 11BCE0 80029EE0 3C018015 */  lui        $at, %hi(D_8014A050)
.L80029EE4:
/* 11BCE4 80029EE4 E428A050 */  swc1       $f8, %lo(D_8014A050)($at)
/* 11BCE8 80029EE8 3C018017 */  lui        $at, %hi(D_8016D1A8)
/* 11BCEC 80029EEC 0C00A7E8 */  jal        func_80029FA0
/* 11BCF0 80029EF0 E42AD1A8 */   swc1      $f10, %lo(D_8016D1A8)($at)
/* 11BCF4 80029EF4 3C048008 */  lui        $a0, %hi(D_80080750)
.L80029EF8:
/* 11BCF8 80029EF8 24840750 */  addiu      $a0, $a0, %lo(D_80080750)
.L80029EFC:
/* 11BCFC 80029EFC 3C018006 */  lui        $at, %hi(D_8005DC40)
.L80029F00:
/* 11BD00 80029F00 AC22DC40 */  sw         $v0, %lo(D_8005DC40)($at)
/* 11BD04 80029F04 0C00A157 */  jal        func_8002855C
/* 11BD08 80029F08 24050002 */   addiu     $a1, $zero, 0x2
/* 11BD0C 80029F0C 3C018005 */  lui        $at, %hi(func_800519E8 + 0x8)
/* 11BD10 80029F10 A02019F0 */  sb         $zero, %lo(func_800519E8 + 0x8)($at)
.L80029F14:
/* 11BD14 80029F14 16000003 */  bnez       $s0, .L80029F24
/* 11BD18 80029F18 24020001 */   addiu     $v0, $zero, 0x1
/* 11BD1C 80029F1C 3C018005 */  lui        $at, %hi(func_800519E8 + 0xC)
.L80029F20:
/* 11BD20 80029F20 AC2219F4 */  sw         $v0, %lo(func_800519E8 + 0xC)($at)
.L80029F24:
/* 11BD24 80029F24 3C028005 */  lui        $v0, %hi(func_800519E8 + 0xC)
.L80029F28:
/* 11BD28 80029F28 8C4219F4 */  lw         $v0, %lo(func_800519E8 + 0xC)($v0)
/* 11BD2C 80029F2C 1440000C */  bnez       $v0, .L80029F60
/* 11BD30 80029F30 00000000 */   nop
/* 11BD34 80029F34 3C048006 */  lui        $a0, %hi(D_8005DC40)
.L80029F38:
/* 11BD38 80029F38 0C00A82A */  jal        func_8002A0A8
/* 11BD3C 80029F3C 8C84DC40 */   lw        $a0, %lo(D_8005DC40)($a0)
/* 11BD40 80029F40 3C018005 */  lui        $at, %hi(func_800519E8 + 0xC)
/* 11BD44 80029F44 0C009767 */  jal        func_80025D9C
.L80029F48:
/* 11BD48 80029F48 AC2219F4 */   sw        $v0, %lo(func_800519E8 + 0xC)($at)
.L80029F4C:
/* 11BD4C 80029F4C 3C048008 */  lui        $a0, %hi(D_80080750)
/* 11BD50 80029F50 0C00A1B0 */  jal        func_800286C0
/* 11BD54 80029F54 24840750 */   addiu     $a0, $a0, %lo(D_80080750)
.L80029F58:
/* 11BD58 80029F58 0800A7E4 */  j          .L80029F90
/* 11BD5C 80029F5C 00001021 */   addu      $v0, $zero, $zero
.L80029F60:
/* 11BD60 80029F60 3C048008 */  lui        $a0, %hi(D_80080750)
/* 11BD64 80029F64 0C00A16B */  jal        func_800285AC
/* 11BD68 80029F68 24840750 */   addiu     $a0, $a0, %lo(D_80080750)
/* 11BD6C 80029F6C 3C048006 */  lui        $a0, %hi(D_8005DC40)
/* 11BD70 80029F70 0C00A9A2 */  jal        func_8002A688
/* 11BD74 80029F74 2484DC40 */   addiu     $a0, $a0, %lo(D_8005DC40)
/* 11BD78 80029F78 24020001 */  addiu      $v0, $zero, 0x1
/* 11BD7C 80029F7C 24030001 */  addiu      $v1, $zero, 0x1
/* 11BD80 80029F80 3C018005 */  lui        $at, %hi(func_800519E8 + 0xC)
/* 11BD84 80029F84 AC2019F4 */  sw         $zero, %lo(func_800519E8 + 0xC)($at)
.L80029F88:
/* 11BD88 80029F88 3C018005 */  lui        $at, %hi(func_800519E8 + 0x8)
/* 11BD8C 80029F8C A02319F0 */  sb         $v1, %lo(func_800519E8 + 0x8)($at)
.L80029F90:
/* 11BD90 80029F90 8FBF001C */  lw         $ra, 0x1C($sp)
/* 11BD94 80029F94 8FB00018 */  lw         $s0, 0x18($sp)
/* 11BD98 80029F98 03E00008 */  jr         $ra
.L80029F9C:
/* 11BD9C 80029F9C 27BD0020 */   addiu     $sp, $sp, 0x20
.size func_80029E10, . - func_80029E10

glabel func_80029FA0
/* 11BDA0 80029FA0 27BDFFE0 */  addiu      $sp, $sp, -0x20
.L80029FA4:
/* 11BDA4 80029FA4 24040078 */  addiu      $a0, $zero, 0x78
.L80029FA8:
/* 11BDA8 80029FA8 AFBF0018 */  sw         $ra, 0x18($sp)
.L80029FAC:
/* 11BDAC 80029FAC AFB10014 */  sw         $s1, 0x14($sp)
.L80029FB0:
/* 11BDB0 80029FB0 0C032663 */  jal        func_800C998C
/* 11BDB4 80029FB4 AFB00010 */   sw        $s0, 0x10($sp)
/* 11BDB8 80029FB8 00408021 */  addu       $s0, $v0, $zero
/* 11BDBC 80029FBC 02002021 */  addu       $a0, $s0, $zero
.L80029FC0:
/* 11BDC0 80029FC0 0C030134 */  jal        bzero
/* 11BDC4 80029FC4 24050078 */   addiu     $a1, $zero, 0x78
/* 11BDC8 80029FC8 2402000A */  addiu      $v0, $zero, 0xA
/* 11BDCC 80029FCC AE02003C */  sw         $v0, 0x3C($s0)
/* 11BDD0 80029FD0 0C00AEC4 */  jal        func_8002BB10
/* 11BDD4 80029FD4 AE000040 */   sw        $zero, 0x40($s0)
/* 11BDD8 80029FD8 3C0142B4 */  lui        $at, (0x42B40000 >> 16)
/* 11BDDC 80029FDC 44810000 */  mtc1       $at, $f0
/* 11BDE0 80029FE0 24110007 */  addiu      $s1, $zero, 0x7
/* 11BDE4 80029FE4 2403008D */  addiu      $v1, $zero, 0x8D
/* 11BDE8 80029FE8 AE020000 */  sw         $v0, 0x0($s0)
/* 11BDEC 80029FEC AC430004 */  sw         $v1, 0x4($v0)
/* 11BDF0 80029FF0 240300AA */  addiu      $v1, $zero, 0xAA
/* 11BDF4 80029FF4 AC430008 */  sw         $v1, 0x8($v0)
/* 11BDF8 80029FF8 24030002 */  addiu      $v1, $zero, 0x2
.L80029FFC:
/* 11BDFC 80029FFC AC51001C */  sw         $s1, 0x1C($v0)
.L8002A000:
/* 11BE00 8002A000 AC400044 */  sw         $zero, 0x44($v0)
/* 11BE04 8002A004 AC43000C */  sw         $v1, 0xC($v0)
glabel func_8002A008
/* 11BE08 8002A008 AC400010 */  sw         $zero, 0x10($v0)
.L8002A00C:
/* 11BE0C 8002A00C 0C00AEC4 */  jal        func_8002BB10
/* 11BE10 8002A010 E4400054 */   swc1      $f0, 0x54($v0)
/* 11BE14 8002A014 24030058 */  addiu      $v1, $zero, 0x58
/* 11BE18 8002A018 AE020004 */  sw         $v0, 0x4($s0)
/* 11BE1C 8002A01C AC51001C */  sw         $s1, 0x1C($v0)
/* 11BE20 8002A020 0C00AEC4 */  jal        func_8002BB10
glabel func_8002A024
/* 11BE24 8002A024 AC430004 */   sw        $v1, 0x4($v0)
/* 11BE28 8002A028 2403005A */  addiu      $v1, $zero, 0x5A
/* 11BE2C 8002A02C AE020008 */  sw         $v0, 0x8($s0)
.L8002A030:
/* 11BE30 8002A030 AC51001C */  sw         $s1, 0x1C($v0)
/* 11BE34 8002A034 AC430004 */  sw         $v1, 0x4($v0)
/* 11BE38 8002A038 0C00AF3F */  jal        func_8002BCFC
/* 11BE3C 8002A03C 8E040000 */   lw        $a0, 0x0($s0)
/* 11BE40 8002A040 0C00AF3F */  jal        func_8002BCFC
/* 11BE44 8002A044 8E040004 */   lw        $a0, 0x4($s0)
.L8002A048:
/* 11BE48 8002A048 0C00AF3F */  jal        func_8002BCFC
/* 11BE4C 8002A04C 8E040008 */   lw        $a0, 0x8($s0)
/* 11BE50 8002A050 8E020000 */  lw         $v0, 0x0($s0)
glabel .L8002A054
/* 11BE54 8002A054 8E030004 */  lw         $v1, 0x4($s0)
.L8002A058:
/* 11BE58 8002A058 8C440034 */  lw         $a0, 0x34($v0)
/* 11BE5C 8002A05C 8C660034 */  lw         $a2, 0x34($v1)
/* 11BE60 8002A060 3C058006 */  lui        $a1, %hi(D_8005AA24)
/* 11BE64 8002A064 24A5AA24 */  addiu      $a1, $a1, %lo(D_8005AA24)
/* 11BE68 8002A068 0C02864D */  jal        func_800A1934
/* 11BE6C 8002A06C 00A03821 */   addu      $a3, $a1, $zero
/* 11BE70 8002A070 8E020000 */  lw         $v0, 0x0($s0)
/* 11BE74 8002A074 8E030008 */  lw         $v1, 0x8($s0)
/* 11BE78 8002A078 8C440034 */  lw         $a0, 0x34($v0)
/* 11BE7C 8002A07C 8C660034 */  lw         $a2, 0x34($v1)
/* 11BE80 8002A080 3C058006 */  lui        $a1, %hi(D_8005AA2C)
/* 11BE84 8002A084 24A5AA2C */  addiu      $a1, $a1, %lo(D_8005AA2C)
.L8002A088:
/* 11BE88 8002A088 0C02864D */  jal        func_800A1934
/* 11BE8C 8002A08C 00A03821 */   addu      $a3, $a1, $zero
/* 11BE90 8002A090 02001021 */  addu       $v0, $s0, $zero
/* 11BE94 8002A094 8FBF0018 */  lw         $ra, 0x18($sp)
/* 11BE98 8002A098 8FB10014 */  lw         $s1, 0x14($sp)
/* 11BE9C 8002A09C 8FB00010 */  lw         $s0, 0x10($sp)
glabel .L8002A0A0
/* 11BEA0 8002A0A0 03E00008 */  jr         $ra
glabel .L8002A0A4
/* 11BEA4 8002A0A4 27BD0020 */   addiu     $sp, $sp, 0x20
.size func_80029FA0, . - func_80029FA0

glabel func_8002A0A8
/* 11BEA8 8002A0A8 27BDFFC0 */  addiu      $sp, $sp, -0x40
/* 11BEAC 8002A0AC AFB1001C */  sw         $s1, 0x1C($sp)
glabel .L8002A0B0
/* 11BEB0 8002A0B0 00808821 */  addu       $s1, $a0, $zero
/* 11BEB4 8002A0B4 AFBF0024 */  sw         $ra, 0x24($sp)
/* 11BEB8 8002A0B8 AFB20020 */  sw         $s2, 0x20($sp)
/* 11BEBC 8002A0BC AFB00018 */  sw         $s0, 0x18($sp)
glabel .L8002A0C0
/* 11BEC0 8002A0C0 F7B80038 */  sdc1       $f24, 0x38($sp)
/* 11BEC4 8002A0C4 F7B60030 */  sdc1       $f22, 0x30($sp)
/* 11BEC8 8002A0C8 F7B40028 */  sdc1       $f20, 0x28($sp)
/* 11BECC 8002A0CC 8E230040 */  lw         $v1, 0x40($s1)
glabel .L8002A0D0
/* 11BED0 8002A0D0 24120001 */  addiu      $s2, $zero, 0x1
glabel func_8002A0D4
/* 11BED4 8002A0D4 10720088 */  beq        $v1, $s2, func_8002A2F8
/* 11BED8 8002A0D8 28620002 */   slti      $v0, $v1, 0x2
/* 11BEDC 8002A0DC 50400005 */  beql       $v0, $zero, func_8002A0F4
glabel .L8002A0E0
/* 11BEE0 8002A0E0 24020002 */   addiu     $v0, $zero, 0x2
.L8002A0E4:
/* 11BEE4 8002A0E4 10600009 */  beqz       $v1, .L8002A10C
/* 11BEE8 8002A0E8 00000000 */   nop
/* 11BEEC 8002A0EC 0800A941 */  j          .L8002A504
glabel .L8002A0F0
/* 11BEF0 8002A0F0 00000000 */   nop
glabel func_8002A0F4
/* 11BEF4 8002A0F4 106200F9 */  beq        $v1, $v0, .L8002A4DC
/* 11BEF8 8002A0F8 24020003 */   addiu     $v0, $zero, 0x3
/* 11BEFC 8002A0FC 106200FD */  beq        $v1, $v0, .L8002A4F4
glabel .L8002A100
/* 11BF00 8002A100 00000000 */   nop
/* 11BF04 8002A104 0800A941 */  j          .L8002A504
.L8002A108:
/* 11BF08 8002A108 00000000 */   nop
.L8002A10C:
/* 11BF0C 8002A10C 3C053F80 */  lui        $a1, (0x3F800000 >> 16)
/* 11BF10 8002A110 4480C000 */  mtc1       $zero, $f24
/* 11BF14 8002A114 00000000 */  nop
glabel .L8002A118
/* 11BF18 8002A118 4406C000 */  mfc1       $a2, $f24
/* 11BF1C 8002A11C 4407C000 */  mfc1       $a3, $f24
/* 11BF20 8002A120 3C048008 */  lui        $a0, %hi(D_80080750)
glabel func_8002A124
/* 11BF24 8002A124 0C00A18C */  jal        func_80028630
/* 11BF28 8002A128 24840750 */   addiu     $a0, $a0, %lo(D_80080750)
glabel func_8002A12C
/* 11BF2C 8002A12C 8E220000 */  lw         $v0, 0x0($s1)
/* 11BF30 8002A130 8C430010 */  lw         $v1, 0x10($v0)
/* 11BF34 8002A134 24020004 */  addiu      $v0, $zero, 0x4
/* 11BF38 8002A138 14620007 */  bne        $v1, $v0, .L8002A158
/* 11BF3C 8002A13C 00000000 */   nop
/* 11BF40 8002A140 0C026DD5 */  jal        func_8009B754
/* 11BF44 8002A144 2404000C */   addiu     $a0, $zero, 0xC
/* 11BF48 8002A148 00002021 */  addu       $a0, $zero, $zero
/* 11BF4C 8002A14C 24050080 */  addiu      $a1, $zero, 0x80
.L8002A150:
/* 11BF50 8002A150 0C026B15 */  jal        func_8009AC54
/* 11BF54 8002A154 240603E7 */   addiu     $a2, $zero, 0x3E7
.L8002A158:
/* 11BF58 8002A158 8E220000 */  lw         $v0, 0x0($s1)
/* 11BF5C 8002A15C 8C420010 */  lw         $v0, 0x10($v0)
/* 11BF60 8002A160 28420005 */  slti       $v0, $v0, 0x5
/* 11BF64 8002A164 1440005A */  bnez       $v0, .L8002A2D0
/* 11BF68 8002A168 24040032 */   addiu     $a0, $zero, 0x32
/* 11BF6C 8002A16C 0C02591A */  jal        func_80096468
/* 11BF70 8002A170 E638000C */   swc1      $f24, 0xC($s1)
glabel .L8002A174
/* 11BF74 8002A174 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 11BF78 8002A178 4481A000 */  mtc1       $at, $f20
/* 11BF7C 8002A17C 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 11BF80 8002A180 44820000 */  mtc1       $v0, $f0
.L8002A184:
/* 11BF84 8002A184 00000000 */  nop
.L8002A188:
/* 11BF88 8002A188 46800020 */  cvt.s.w    $f0, $f0
/* 11BF8C 8002A18C 46140003 */  div.s      $f0, $f0, $f20
/* 11BF90 8002A190 3C014040 */  lui        $at, (0x40400000 >> 16)
/* 11BF94 8002A194 44811000 */  mtc1       $at, $f2
.L8002A198:
/* 11BF98 8002A198 00000000 */  nop
/* 11BF9C 8002A19C 46020000 */  add.s      $f0, $f0, $f2
/* 11BFA0 8002A1A0 2404012C */  addiu      $a0, $zero, 0x12C
/* 11BFA4 8002A1A4 0C02591A */  jal        func_80096468
.L8002A1A8:
/* 11BFA8 8002A1A8 E6200010 */   swc1      $f0, 0x10($s1)
/* 11BFAC 8002A1AC 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 11BFB0 8002A1B0 44820000 */  mtc1       $v0, $f0
.L8002A1B4:
/* 11BFB4 8002A1B4 00000000 */  nop
/* 11BFB8 8002A1B8 46800020 */  cvt.s.w    $f0, $f0
.L8002A1BC:
/* 11BFBC 8002A1BC 46140003 */  div.s      $f0, $f0, $f20
glabel func_8002A1C0
/* 11BFC0 8002A1C0 3C048003 */  lui        $a0, %hi(func_80034A30)
/* 11BFC4 8002A1C4 24844A30 */  addiu      $a0, $a0, %lo(func_80034A30)
/* 11BFC8 8002A1C8 2630000C */  addiu      $s0, $s1, 0xC
/* 11BFCC 8002A1CC 02002821 */  addu       $a1, $s0, $zero
glabel .L8002A1D0
/* 11BFD0 8002A1D0 3C014170 */  lui        $at, (0x41700000 >> 16)
/* 11BFD4 8002A1D4 44814000 */  mtc1       $at, $f8
/* 11BFD8 8002A1D8 3C014000 */  lui        $at, (0x40000000 >> 16)
/* 11BFDC 8002A1DC 4481B000 */  mtc1       $at, $f22
/* 11BFE0 8002A1E0 3C013F00 */  lui        $at, (0x3F000000 >> 16)
.L8002A1E4:
/* 11BFE4 8002A1E4 44811000 */  mtc1       $at, $f2
/* 11BFE8 8002A1E8 3C013B80 */  lui        $at, (0x3B800000 >> 16)
/* 11BFEC 8002A1EC 44812000 */  mtc1       $at, $f4
.L8002A1F0:
/* 11BFF0 8002A1F0 3C013A03 */  lui        $at, (0x3A03126F >> 16)
/* 11BFF4 8002A1F4 3421126F */  ori        $at, $at, (0x3A03126F & 0xFFFF)
/* 11BFF8 8002A1F8 44813000 */  mtc1       $at, $f6
/* 11BFFC 8002A1FC 2406012C */  addiu      $a2, $zero, 0x12C
/* 11C000 8002A200 24070001 */  addiu      $a3, $zero, 0x1
/* 11C004 8002A204 E6380020 */  swc1       $f24, 0x20($s1)
/* 11C008 8002A208 E6360018 */  swc1       $f22, 0x18($s1)
/* 11C00C 8002A20C 46080001 */  sub.s      $f0, $f0, $f8
.L8002A210:
/* 11C010 8002A210 E622001C */  swc1       $f2, 0x1C($s1)
/* 11C014 8002A214 E6240024 */  swc1       $f4, 0x24($s1)
/* 11C018 8002A218 E6260028 */  swc1       $f6, 0x28($s1)
/* 11C01C 8002A21C 0C025D06 */  jal        func_80097418
.L8002A220:
/* 11C020 8002A220 E6200014 */   swc1      $f0, 0x14($s1)
/* 11C024 8002A224 24040028 */  addiu      $a0, $zero, 0x28
.L8002A228:
/* 11C028 8002A228 E638000C */  swc1       $f24, 0xC($s1)
/* 11C02C 8002A22C E6340010 */  swc1       $f20, 0x10($s1)
/* 11C030 8002A230 0C02591A */  jal        func_80096468
glabel .L8002A234
/* 11C034 8002A234 E6380014 */   swc1      $f24, 0x14($s1)
/* 11C038 8002A238 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 11C03C 8002A23C 44820000 */  mtc1       $v0, $f0
.L8002A240:
/* 11C040 8002A240 00000000 */  nop
.L8002A244:
/* 11C044 8002A244 46800020 */  cvt.s.w    $f0, $f0
.L8002A248:
/* 11C048 8002A248 46140003 */  div.s      $f0, $f0, $f20
/* 11C04C 8002A24C 46160001 */  sub.s      $f0, $f0, $f22
/* 11C050 8002A250 24040014 */  addiu      $a0, $zero, 0x14
glabel func_8002A254
/* 11C054 8002A254 0C02591A */  jal        func_80096468
/* 11C058 8002A258 E6200018 */   swc1      $f0, 0x18($s1)
/* 11C05C 8002A25C 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 11C060 8002A260 44820000 */  mtc1       $v0, $f0
/* 11C064 8002A264 00000000 */  nop
/* 11C068 8002A268 46800020 */  cvt.s.w    $f0, $f0
/* 11C06C 8002A26C 46140003 */  div.s      $f0, $f0, $f20
/* 11C070 8002A270 24040028 */  addiu      $a0, $zero, 0x28
/* 11C074 8002A274 0C02591A */  jal        func_80096468
/* 11C078 8002A278 E620001C */   swc1      $f0, 0x1C($s1)
/* 11C07C 8002A27C 3042FFFF */  andi       $v0, $v0, 0xFFFF
.L8002A280:
/* 11C080 8002A280 44820000 */  mtc1       $v0, $f0
/* 11C084 8002A284 00000000 */  nop
/* 11C088 8002A288 46800020 */  cvt.s.w    $f0, $f0
.L8002A28C:
/* 11C08C 8002A28C 46140003 */  div.s      $f0, $f0, $f20
/* 11C090 8002A290 46160001 */  sub.s      $f0, $f0, $f22
.L8002A294:
/* 11C094 8002A294 24040002 */  addiu      $a0, $zero, 0x2
glabel .L8002A298
/* 11C098 8002A298 0C02591A */  jal        func_80096468
/* 11C09C 8002A29C E6200020 */   swc1      $f0, 0x20($s1)
.L8002A2A0:
/* 11C0A0 8002A2A0 3C048003 */  lui        $a0, %hi(func_80034E30)
/* 11C0A4 8002A2A4 24844E30 */  addiu      $a0, $a0, %lo(func_80034E30)
/* 11C0A8 8002A2A8 02002821 */  addu       $a1, $s0, $zero
.L8002A2AC:
/* 11C0AC 8002A2AC 2406012C */  addiu      $a2, $zero, 0x12C
/* 11C0B0 8002A2B0 24070001 */  addiu      $a3, $zero, 0x1
.L8002A2B4:
/* 11C0B4 8002A2B4 30420001 */  andi       $v0, $v0, 0x1
/* 11C0B8 8002A2B8 2C420001 */  sltiu      $v0, $v0, 0x1
/* 11C0BC 8002A2BC 00021023 */  negu       $v0, $v0
/* 11C0C0 8002A2C0 30420083 */  andi       $v0, $v0, 0x83
.L8002A2C4:
/* 11C0C4 8002A2C4 34420082 */  ori        $v0, $v0, 0x82
.L8002A2C8:
/* 11C0C8 8002A2C8 0C025D06 */  jal        func_80097418
/* 11C0CC 8002A2CC AE22002C */   sw        $v0, 0x2C($s1)
.L8002A2D0:
/* 11C0D0 8002A2D0 8E240000 */  lw         $a0, 0x0($s1)
.L8002A2D4:
/* 11C0D4 8002A2D4 8C830010 */  lw         $v1, 0x10($a0)
glabel func_8002A2D8
/* 11C0D8 8002A2D8 28620016 */  slti       $v0, $v1, 0x16
/* 11C0DC 8002A2DC 10400003 */  beqz       $v0, .L8002A2EC
/* 11C0E0 8002A2E0 24620001 */   addiu     $v0, $v1, 0x1
/* 11C0E4 8002A2E4 0800A8BC */  j          .L8002A2F0
/* 11C0E8 8002A2E8 AC820010 */   sw        $v0, 0x10($a0)
.L8002A2EC:
/* 11C0EC 8002A2EC AE320040 */  sw         $s2, 0x40($s1)
.L8002A2F0:
/* 11C0F0 8002A2F0 0800A941 */  j          .L8002A504
/* 11C0F4 8002A2F4 AE200044 */   sw        $zero, 0x44($s1)
glabel func_8002A2F8
/* 11C0F8 8002A2F8 3C053F80 */  lui        $a1, (0x3F800000 >> 16)
/* 11C0FC 8002A2FC 4480A000 */  mtc1       $zero, $f20
/* 11C100 8002A300 00000000 */  nop
.L8002A304:
/* 11C104 8002A304 4406A000 */  mfc1       $a2, $f20
/* 11C108 8002A308 4407A000 */  mfc1       $a3, $f20
/* 11C10C 8002A30C 3C048008 */  lui        $a0, %hi(D_80080750)
/* 11C110 8002A310 24840750 */  addiu      $a0, $a0, %lo(D_80080750)
.L8002A314:
/* 11C114 8002A314 0C00A18C */  jal        func_80028630
.L8002A318:
/* 11C118 8002A318 2630000C */   addiu     $s0, $s1, 0xC
glabel .L8002A31C
/* 11C11C 8002A31C 24040032 */  addiu      $a0, $zero, 0x32
/* 11C120 8002A320 0C02591A */  jal        func_80096468
/* 11C124 8002A324 E634000C */   swc1      $f20, 0xC($s1)
/* 11C128 8002A328 3C014120 */  lui        $at, (0x41200000 >> 16)
.L8002A32C:
/* 11C12C 8002A32C 4481B000 */  mtc1       $at, $f22
.L8002A330:
/* 11C130 8002A330 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 11C134 8002A334 44820000 */  mtc1       $v0, $f0
/* 11C138 8002A338 00000000 */  nop
.L8002A33C:
/* 11C13C 8002A33C 46800020 */  cvt.s.w    $f0, $f0
/* 11C140 8002A340 46160003 */  div.s      $f0, $f0, $f22
/* 11C144 8002A344 3C014040 */  lui        $at, (0x40400000 >> 16)
/* 11C148 8002A348 44811000 */  mtc1       $at, $f2
/* 11C14C 8002A34C 00000000 */  nop
/* 11C150 8002A350 46020000 */  add.s      $f0, $f0, $f2
/* 11C154 8002A354 2404012C */  addiu      $a0, $zero, 0x12C
/* 11C158 8002A358 0C02591A */  jal        func_80096468
/* 11C15C 8002A35C E6200010 */   swc1      $f0, 0x10($s1)
glabel .L8002A360
/* 11C160 8002A360 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 11C164 8002A364 44820000 */  mtc1       $v0, $f0
/* 11C168 8002A368 00000000 */  nop
/* 11C16C 8002A36C 46800020 */  cvt.s.w    $f0, $f0
/* 11C170 8002A370 46160003 */  div.s      $f0, $f0, $f22
.L8002A374:
/* 11C174 8002A374 3C048003 */  lui        $a0, %hi(func_80034A30)
/* 11C178 8002A378 24844A30 */  addiu      $a0, $a0, %lo(func_80034A30)
.L8002A37C:
/* 11C17C 8002A37C 02002821 */  addu       $a1, $s0, $zero
/* 11C180 8002A380 3C014170 */  lui        $at, (0x41700000 >> 16)
/* 11C184 8002A384 44814000 */  mtc1       $at, $f8
/* 11C188 8002A388 3C014000 */  lui        $at, (0x40000000 >> 16)
/* 11C18C 8002A38C 4481C000 */  mtc1       $at, $f24
/* 11C190 8002A390 3C013F00 */  lui        $at, (0x3F000000 >> 16)
/* 11C194 8002A394 44811000 */  mtc1       $at, $f2
/* 11C198 8002A398 3C013B80 */  lui        $at, (0x3B800000 >> 16)
/* 11C19C 8002A39C 44812000 */  mtc1       $at, $f4
/* 11C1A0 8002A3A0 3C013A03 */  lui        $at, (0x3A03126F >> 16)
glabel .L8002A3A4
/* 11C1A4 8002A3A4 3421126F */  ori        $at, $at, (0x3A03126F & 0xFFFF)
/* 11C1A8 8002A3A8 44813000 */  mtc1       $at, $f6
.L8002A3AC:
/* 11C1AC 8002A3AC 2406012C */  addiu      $a2, $zero, 0x12C
glabel func_8002A3B0
/* 11C1B0 8002A3B0 24070001 */  addiu      $a3, $zero, 0x1
/* 11C1B4 8002A3B4 E6340020 */  swc1       $f20, 0x20($s1)
glabel func_8002A3B8
/* 11C1B8 8002A3B8 E6380018 */  swc1       $f24, 0x18($s1)
/* 11C1BC 8002A3BC 46080001 */  sub.s      $f0, $f0, $f8
glabel func_8002A3C0
/* 11C1C0 8002A3C0 E622001C */  swc1       $f2, 0x1C($s1)
glabel func_8002A3C4
/* 11C1C4 8002A3C4 E6240024 */  swc1       $f4, 0x24($s1)
/* 11C1C8 8002A3C8 E6260028 */  swc1       $f6, 0x28($s1)
/* 11C1CC 8002A3CC 0C025D06 */  jal        func_80097418
/* 11C1D0 8002A3D0 E6200014 */   swc1      $f0, 0x14($s1)
/* 11C1D4 8002A3D4 24040028 */  addiu      $a0, $zero, 0x28
/* 11C1D8 8002A3D8 E634000C */  swc1       $f20, 0xC($s1)
/* 11C1DC 8002A3DC E6360010 */  swc1       $f22, 0x10($s1)
/* 11C1E0 8002A3E0 0C02591A */  jal        func_80096468
.L8002A3E4:
/* 11C1E4 8002A3E4 E6340014 */   swc1      $f20, 0x14($s1)
glabel .L8002A3E8
/* 11C1E8 8002A3E8 3042FFFF */  andi       $v0, $v0, 0xFFFF
.L8002A3EC:
/* 11C1EC 8002A3EC 44820000 */  mtc1       $v0, $f0
/* 11C1F0 8002A3F0 00000000 */  nop
/* 11C1F4 8002A3F4 46800020 */  cvt.s.w    $f0, $f0
.L8002A3F8:
/* 11C1F8 8002A3F8 46160003 */  div.s      $f0, $f0, $f22
.L8002A3FC:
/* 11C1FC 8002A3FC 46180001 */  sub.s      $f0, $f0, $f24
/* 11C200 8002A400 24040014 */  addiu      $a0, $zero, 0x14
/* 11C204 8002A404 0C02591A */  jal        func_80096468
/* 11C208 8002A408 E6200018 */   swc1      $f0, 0x18($s1)
/* 11C20C 8002A40C 3042FFFF */  andi       $v0, $v0, 0xFFFF
/* 11C210 8002A410 44820000 */  mtc1       $v0, $f0
/* 11C214 8002A414 00000000 */  nop
glabel .L8002A418
/* 11C218 8002A418 46800020 */  cvt.s.w    $f0, $f0
.L8002A41C:
/* 11C21C 8002A41C 46160003 */  div.s      $f0, $f0, $f22
/* 11C220 8002A420 24040028 */  addiu      $a0, $zero, 0x28
/* 11C224 8002A424 0C02591A */  jal        func_80096468
glabel .L8002A428
/* 11C228 8002A428 E620001C */   swc1      $f0, 0x1C($s1)
/* 11C22C 8002A42C 3042FFFF */  andi       $v0, $v0, 0xFFFF
.L8002A430:
/* 11C230 8002A430 44820000 */  mtc1       $v0, $f0
/* 11C234 8002A434 00000000 */  nop
glabel .L8002A438
/* 11C238 8002A438 46800020 */  cvt.s.w    $f0, $f0
.L8002A43C:
/* 11C23C 8002A43C 46160003 */  div.s      $f0, $f0, $f22
/* 11C240 8002A440 46180001 */  sub.s      $f0, $f0, $f24
/* 11C244 8002A444 24040002 */  addiu      $a0, $zero, 0x2
glabel .L8002A448
/* 11C248 8002A448 0C02591A */  jal        func_80096468
/* 11C24C 8002A44C E6200020 */   swc1      $f0, 0x20($s1)
/* 11C250 8002A450 3C048003 */  lui        $a0, %hi(func_80034E30)
glabel func_8002A454
/* 11C254 8002A454 24844E30 */  addiu      $a0, $a0, %lo(func_80034E30)
/* 11C258 8002A458 02002821 */  addu       $a1, $s0, $zero
glabel .L8002A45C
/* 11C25C 8002A45C 2406012C */  addiu      $a2, $zero, 0x12C
/* 11C260 8002A460 24070001 */  addiu      $a3, $zero, 0x1
/* 11C264 8002A464 30420001 */  andi       $v0, $v0, 0x1
/* 11C268 8002A468 2C420001 */  sltiu      $v0, $v0, 0x1
/* 11C26C 8002A46C 00021023 */  negu       $v0, $v0
glabel .L8002A470
/* 11C270 8002A470 30420083 */  andi       $v0, $v0, 0x83
/* 11C274 8002A474 34420082 */  ori        $v0, $v0, 0x82
/* 11C278 8002A478 0C025D06 */  jal        func_80097418
/* 11C27C 8002A47C AE22002C */   sw        $v0, 0x2C($s1)
/* 11C280 8002A480 8E220044 */  lw         $v0, 0x44($s1)
glabel .L8002A484
/* 11C284 8002A484 30420001 */  andi       $v0, $v0, 0x1
/* 11C288 8002A488 10400005 */  beqz       $v0, .L8002A4A0
/* 11C28C 8002A48C 00000000 */   nop
glabel .L8002A490
/* 11C290 8002A490 8E230000 */  lw         $v1, 0x0($s1)
.L8002A494:
/* 11C294 8002A494 8C620010 */  lw         $v0, 0x10($v1)
glabel .L8002A498
/* 11C298 8002A498 0800A92B */  j          .L8002A4AC
/* 11C29C 8002A49C 2442FFFF */   addiu     $v0, $v0, -0x1
.L8002A4A0:
/* 11C2A0 8002A4A0 8E230000 */  lw         $v1, 0x0($s1)
/* 11C2A4 8002A4A4 8C620010 */  lw         $v0, 0x10($v1)
/* 11C2A8 8002A4A8 24420001 */  addiu      $v0, $v0, 0x1
glabel .L8002A4AC
/* 11C2AC 8002A4AC AC620010 */  sw         $v0, 0x10($v1)
/* 11C2B0 8002A4B0 8E220044 */  lw         $v0, 0x44($s1)
glabel .L8002A4B4
/* 11C2B4 8002A4B4 2842003D */  slti       $v0, $v0, 0x3D
/* 11C2B8 8002A4B8 14400004 */  bnez       $v0, .L8002A4CC
.L8002A4BC:
/* 11C2BC 8002A4BC 24020002 */   addiu     $v0, $zero, 0x2
/* 11C2C0 8002A4C0 AE220040 */  sw         $v0, 0x40($s1)
.L8002A4C4:
/* 11C2C4 8002A4C4 0C026DD5 */  jal        func_8009B754
/* 11C2C8 8002A4C8 2404000D */   addiu     $a0, $zero, 0xD
.L8002A4CC:
/* 11C2CC 8002A4CC 8E220044 */  lw         $v0, 0x44($s1)
/* 11C2D0 8002A4D0 24420001 */  addiu      $v0, $v0, 0x1
/* 11C2D4 8002A4D4 0800A941 */  j          .L8002A504
glabel .L8002A4D8
/* 11C2D8 8002A4D8 AE220044 */   sw        $v0, 0x44($s1)
.L8002A4DC:
/* 11C2DC 8002A4DC 0C026B46 */  jal        func_8009AD18
.L8002A4E0:
/* 11C2E0 8002A4E0 00000000 */   nop
/* 11C2E4 8002A4E4 0C026DD5 */  jal        func_8009B754
/* 11C2E8 8002A4E8 24040022 */   addiu     $a0, $zero, 0x22
/* 11C2EC 8002A4EC 24020003 */  addiu      $v0, $zero, 0x3
/* 11C2F0 8002A4F0 AE220040 */  sw         $v0, 0x40($s1)
.L8002A4F4:
/* 11C2F4 8002A4F4 8E230000 */  lw         $v1, 0x0($s1)
/* 11C2F8 8002A4F8 8C620010 */  lw         $v0, 0x10($v1)
glabel .L8002A4FC
/* 11C2FC 8002A4FC 24420001 */  addiu      $v0, $v0, 0x1
/* 11C300 8002A500 AC620010 */  sw         $v0, 0x10($v1)
.L8002A504:
/* 11C304 8002A504 8E220000 */  lw         $v0, 0x0($s1)
/* 11C308 8002A508 8C420038 */  lw         $v0, 0x38($v0)
/* 11C30C 8002A50C 84420024 */  lh         $v0, 0x24($v0)
/* 11C310 8002A510 2842000A */  slti       $v0, $v0, 0xA
/* 11C314 8002A514 14400013 */  bnez       $v0, .L8002A564
/* 11C318 8002A518 00000000 */   nop
/* 11C31C 8002A51C 8E220040 */  lw         $v0, 0x40($s1)
glabel .L8002A520
/* 11C320 8002A520 28420002 */  slti       $v0, $v0, 0x2
.L8002A524:
/* 11C324 8002A524 1040000F */  beqz       $v0, .L8002A564
/* 11C328 8002A528 00000000 */   nop
/* 11C32C 8002A52C 3C053E00 */  lui        $a1, (0x3E000000 >> 16)
/* 11C330 8002A530 3C048008 */  lui        $a0, %hi(D_80080750)
/* 11C334 8002A534 24840750 */  addiu      $a0, $a0, %lo(D_80080750)
/* 11C338 8002A538 0C00A055 */  jal        func_80028154
.L8002A53C:
/* 11C33C 8002A53C 00003021 */   addu      $a2, $zero, $zero
/* 11C340 8002A540 3C028015 */  lui        $v0, %hi(D_8014A064)
/* 11C344 8002A544 2442A064 */  addiu      $v0, $v0, %lo(D_8014A064)
/* 11C348 8002A548 C4400000 */  lwc1       $f0, 0x0($v0)
glabel func_8002A54C
/* 11C34C 8002A54C 3C013E4C */  lui        $at, (0x3E4CCCCD >> 16)
/* 11C350 8002A550 3421CCCD */  ori        $at, $at, (0x3E4CCCCD & 0xFFFF)
/* 11C354 8002A554 44811000 */  mtc1       $at, $f2
/* 11C358 8002A558 00000000 */  nop
/* 11C35C 8002A55C 46020000 */  add.s      $f0, $f0, $f2
/* 11C360 8002A560 E4400000 */  swc1       $f0, 0x0($v0)
.L8002A564:
/* 11C364 8002A564 0C00AF3F */  jal        func_8002BCFC
/* 11C368 8002A568 8E240000 */   lw        $a0, 0x0($s1)
.L8002A56C:
/* 11C36C 8002A56C 8E220000 */  lw         $v0, 0x0($s1)
/* 11C370 8002A570 8C420038 */  lw         $v0, 0x38($v0)
.L8002A574:
/* 11C374 8002A574 84430024 */  lh         $v1, 0x24($v0)
/* 11C378 8002A578 2402000A */  addiu      $v0, $zero, 0xA
.L8002A57C:
/* 11C37C 8002A57C 14620036 */  bne        $v1, $v0, .L8002A658
/* 11C380 8002A580 24040053 */   addiu     $a0, $zero, 0x53
/* 11C384 8002A584 24050048 */  addiu      $a1, $zero, 0x48
/* 11C388 8002A588 24060053 */  addiu      $a2, $zero, 0x53
glabel .L8002A58C
/* 11C38C 8002A58C 3C01C27C */  lui        $at, (0xC27C0000 >> 16)
.L8002A590:
/* 11C390 8002A590 44810000 */  mtc1       $at, $f0
/* 11C394 8002A594 3C014000 */  lui        $at, (0x40000000 >> 16)
.L8002A598:
/* 11C398 8002A598 44811000 */  mtc1       $at, $f2
/* 11C39C 8002A59C 3C0141F0 */  lui        $at, (0x41F00000 >> 16)
/* 11C3A0 8002A5A0 44812000 */  mtc1       $at, $f4
/* 11C3A4 8002A5A4 3C0143A2 */  lui        $at, (0x43A28000 >> 16)
/* 11C3A8 8002A5A8 34218000 */  ori        $at, $at, (0x43A28000 & 0xFFFF)
/* 11C3AC 8002A5AC 44813000 */  mtc1       $at, $f6
/* 11C3B0 8002A5B0 3C01C140 */  lui        $at, (0xC1400000 >> 16)
glabel .L8002A5B4
/* 11C3B4 8002A5B4 44814000 */  mtc1       $at, $f8
/* 11C3B8 8002A5B8 240200E6 */  addiu      $v0, $zero, 0xE6
/* 11C3BC 8002A5BC AFA20010 */  sw         $v0, 0x10($sp)
/* 11C3C0 8002A5C0 240200DC */  addiu      $v0, $zero, 0xDC
/* 11C3C4 8002A5C4 AFA20014 */  sw         $v0, 0x14($sp)
/* 11C3C8 8002A5C8 3C018015 */  lui        $at, %hi(D_8014A088)
/* 11C3CC 8002A5CC E420A088 */  swc1       $f0, %lo(D_8014A088)($at)
.L8002A5D0:
/* 11C3D0 8002A5D0 3C018015 */  lui        $at, %hi(D_8014A064)
/* 11C3D4 8002A5D4 E422A064 */  swc1       $f2, %lo(D_8014A064)($at)
/* 11C3D8 8002A5D8 3C018015 */  lui        $at, %hi(D_8014A068)
glabel .L8002A5DC
/* 11C3DC 8002A5DC E424A068 */  swc1       $f4, %lo(D_8014A068)($at)
/* 11C3E0 8002A5E0 3C018015 */  lui        $at, %hi(D_8014A080)
/* 11C3E4 8002A5E4 E426A080 */  swc1       $f6, %lo(D_8014A080)($at)
/* 11C3E8 8002A5E8 3C018015 */  lui        $at, %hi(D_8014A07C)
/* 11C3EC 8002A5EC E428A07C */  swc1       $f8, %lo(D_8014A07C)($at)
/* 11C3F0 8002A5F0 0C027101 */  jal        func_8009C404
/* 11C3F4 8002A5F4 240700FF */   addiu     $a3, $zero, 0xFF
.L8002A5F8:
/* 11C3F8 8002A5F8 3C014120 */  lui        $at, (0x41200000 >> 16)
/* 11C3FC 8002A5FC 44810000 */  mtc1       $at, $f0
/* 11C400 8002A600 3C01428A */  lui        $at, (0x428A0000 >> 16)
glabel .L8002A604
/* 11C404 8002A604 44811000 */  mtc1       $at, $f2
/* 11C408 8002A608 3C014254 */  lui        $at, (0x42540000 >> 16)
/* 11C40C 8002A60C 44812000 */  mtc1       $at, $f4
/* 11C410 8002A610 3C01C1C0 */  lui        $at, (0xC1C00000 >> 16)
/* 11C414 8002A614 44813000 */  mtc1       $at, $f6
/* 11C418 8002A618 3C014150 */  lui        $at, (0x41500000 >> 16)
/* 11C41C 8002A61C 44814000 */  mtc1       $at, $f8
/* 11C420 8002A620 3C014264 */  lui        $at, (0x42640000 >> 16)
.L8002A624:
/* 11C424 8002A624 44815000 */  mtc1       $at, $f10
/* 11C428 8002A628 3C018017 */  lui        $at, %hi(D_8016E568)
/* 11C42C 8002A62C E420E568 */  swc1       $f0, %lo(D_8016E568)($at)
glabel D_8002A630
/* 11C430 8002A630 3C018017 */  lui        $at, %hi(D_8016D0D0)
glabel .L8002A634
/* 11C434 8002A634 E422D0D0 */  swc1       $f2, %lo(D_8016D0D0)($at)
/* 11C438 8002A638 3C018017 */  lui        $at, %hi(D_8016D0D4)
glabel .L8002A63C
/* 11C43C 8002A63C E424D0D4 */  swc1       $f4, %lo(D_8016D0D4)($at)
glabel func_8002A640
/* 11C440 8002A640 3C018015 */  lui        $at, %hi(D_8014A054)
/* 11C444 8002A644 E426A054 */  swc1       $f6, %lo(D_8014A054)($at)
/* 11C448 8002A648 3C018015 */  lui        $at, %hi(D_8014A050)
/* 11C44C 8002A64C E428A050 */  swc1       $f8, %lo(D_8014A050)($at)
.L8002A650:
/* 11C450 8002A650 3C018017 */  lui        $at, %hi(D_8016D1A8)
/* 11C454 8002A654 E42AD1A8 */  swc1       $f10, %lo(D_8016D1A8)($at)
.L8002A658:
/* 11C458 8002A658 0C00AFA5 */  jal        func_8002BE94
.L8002A65C:
/* 11C45C 8002A65C 8E240000 */   lw        $a0, 0x0($s1)
/* 11C460 8002A660 00001021 */  addu       $v0, $zero, $zero
/* 11C464 8002A664 8FBF0024 */  lw         $ra, 0x24($sp)
/* 11C468 8002A668 8FB20020 */  lw         $s2, 0x20($sp)
glabel func_8002A66C
/* 11C46C 8002A66C 8FB1001C */  lw         $s1, 0x1C($sp)
glabel func_8002A670
/* 11C470 8002A670 8FB00018 */  lw         $s0, 0x18($sp)
/* 11C474 8002A674 D7B80038 */  ldc1       $f24, 0x38($sp)
/* 11C478 8002A678 D7B60030 */  ldc1       $f22, 0x30($sp)
/* 11C47C 8002A67C D7B40028 */  ldc1       $f20, 0x28($sp)
/* 11C480 8002A680 03E00008 */  jr         $ra
/* 11C484 8002A684 27BD0040 */   addiu     $sp, $sp, 0x40
.size func_8002A0A8, . - func_8002A0A8

glabel func_8002A688
/* 11C488 8002A688 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 11C48C 8002A68C AFB00010 */  sw         $s0, 0x10($sp)
/* 11C490 8002A690 00808021 */  addu       $s0, $a0, $zero
/* 11C494 8002A694 12000010 */  beqz       $s0, .L8002A6D8
.L8002A698:
/* 11C498 8002A698 AFBF0014 */   sw        $ra, 0x14($sp)
glabel .L8002A69C
/* 11C49C 8002A69C 8E040000 */  lw         $a0, 0x0($s0)
/* 11C4A0 8002A6A0 1080000D */  beqz       $a0, .L8002A6D8
/* 11C4A4 8002A6A4 00000000 */   nop
/* 11C4A8 8002A6A8 0C00AF04 */  jal        func_8002BC10
glabel .L8002A6AC
/* 11C4AC 8002A6AC 00000000 */   nop
/* 11C4B0 8002A6B0 8E040000 */  lw         $a0, 0x0($s0)
/* 11C4B4 8002A6B4 0C00AF04 */  jal        func_8002BC10
/* 11C4B8 8002A6B8 24840004 */   addiu     $a0, $a0, 0x4
/* 11C4BC 8002A6BC 8E040000 */  lw         $a0, 0x0($s0)
/* 11C4C0 8002A6C0 0C00AF04 */  jal        func_8002BC10
/* 11C4C4 8002A6C4 24840008 */   addiu     $a0, $a0, 0x8
/* 11C4C8 8002A6C8 8E040000 */  lw         $a0, 0x0($s0)
/* 11C4CC 8002A6CC 0C0326A1 */  jal        func_800C9A84
glabel .L8002A6D0
/* 11C4D0 8002A6D0 00000000 */   nop
.L8002A6D4:
/* 11C4D4 8002A6D4 AE000000 */  sw         $zero, 0x0($s0)
.L8002A6D8:
/* 11C4D8 8002A6D8 8FBF0014 */  lw         $ra, 0x14($sp)
/* 11C4DC 8002A6DC 8FB00010 */  lw         $s0, 0x10($sp)
/* 11C4E0 8002A6E0 03E00008 */  jr         $ra
/* 11C4E4 8002A6E4 27BD0018 */   addiu     $sp, $sp, 0x18
/* 11C4E8 8002A6E8 00000000 */  nop
/* 11C4EC 8002A6EC 00000000 */  nop
.size func_8002A688, . - func_8002A688
