.include "macro.inc"

.section .data

/* Generated by spimdisasm 1.18.0 */

glabel D_800294B0_ovl4
/* 1173C0 800294B0 */ .word D_800298DC_ovl4
/* 1173C4 800294B4 */ .word func_8009E040
/* 1173C8 800294B8 */ .word func_80025DA0_ovl4
/* 1173CC 800294BC */ .word D_800298D0_ovl4
/* 1173D0 800294C0 */ .word func_8009E040
/* 1173D4 800294C4 */ .word func_80026420_ovl4
/* 1173D8 800294C8 */ .word D_800298C4_ovl4
/* 1173DC 800294CC */ .word func_8009E040
/* 1173E0 800294D0 */ .word func_80025F98_ovl4
/* 1173E4 800294D4 */ .word D_800298B8_ovl4
/* 1173E8 800294D8 */ .word func_8009E040
/* 1173EC 800294DC */ .word func_80026490_ovl4
/* 1173F0 800294E0 */ .word D_800298AC_ovl4
/* 1173F4 800294E4 */ .word func_8009E040
/* 1173F8 800294E8 */ .word func_800266F8_ovl4
/* 1173FC 800294EC */ .word D_800298A0_ovl4
/* 117400 800294F0 */ .word func_8009E040
/* 117404 800294F4 */ .word func_80026BA4_ovl4
/* 117408 800294F8 */ .word D_80029894_ovl4
/* 11740C 800294FC */ .word func_8009E040
/* 117410 80029500 */ .word func_8002722C_ovl4
/* 117414 80029504 */ .word D_80029888_ovl4
/* 117418 80029508 */ .word func_8009E040
/* 11741C 8002950C */ .word func_800278C0_ovl4
/* 117420 80029510 */ .word D_8002987C_ovl4
/* 117424 80029514 */ .word func_8009E040
/* 117428 80029518 */ .word func_80028020_ovl4
/* 11742C 8002951C */ .word D_80029870_ovl4
/* 117430 80029520 */ .word func_8009E040
/* 117434 80029524 */ .word func_80028410_ovl4
/* 117438 80029528 */ .word D_80029864_ovl4
/* 11743C 8002952C */ .word func_8009E040
/* 117440 80029530 */ .word func_800285FC_ovl4
/* 117444 80029534 */ .word D_80029858_ovl4
/* 117448 80029538 */ .word func_8009E040
/* 11744C 8002953C */ .word func_800288A0_ovl4
/* 117450 80029540 */ .word D_8002984C_ovl4
/* 117454 80029544 */ .word func_8009E040
/* 117458 80029548 */ .word func_80028A2C_ovl4
/* 11745C 8002954C */ .word D_80029840_ovl4
/* 117460 80029550 */ .word func_8009E040
/* 117464 80029554 */ .word func_80028DB8_ovl4
.size D_800294B0_ovl4, . - D_800294B0_ovl4

glabel D_80029558_ovl4
/* 117468 80029558 */ .word D_800298E8_ovl4
/* 11746C 8002955C */ .word 0x0000000F
/* 117470 80029560 */ .word 0x00000008
/* 117474 80029564 */ .word D_800294B0_ovl4
/* 117478 80029568 */ .word 0x0000000E
/* 11747C 8002956C */ .word 0x0000000E
/* 117480 80029570 */ .word 0x0000000A
/* 117484 80029574 */ .word 0x00000000
/* 117488 80029578 */ .word 0x00000000
.size D_80029558_ovl4, . - D_80029558_ovl4

glabel D_8002957C_ovl4
/* 11748C 8002957C */ .word 0x00000000
.size D_8002957C_ovl4, . - D_8002957C_ovl4

glabel D_80029580_ovl4
/* 117490 80029580 */ .word 0x00000000
.size D_80029580_ovl4, . - D_80029580_ovl4

glabel D_80029584_ovl4
/* 117494 80029584 */ .word 0x00000000
.size D_80029584_ovl4, . - D_80029584_ovl4

glabel D_80029588_ovl4
/* 117498 80029588 */ .word 0x00000000
.size D_80029588_ovl4, . - D_80029588_ovl4

glabel D_8002958C_ovl4
/* 11749C 8002958C */ .word 0x00000000
.size D_8002958C_ovl4, . - D_8002958C_ovl4

glabel D_80029590_ovl4
/* 1174A0 80029590 */ .word 0x00000000
.size D_80029590_ovl4, . - D_80029590_ovl4

glabel D_80029594_ovl4
/* 1174A4 80029594 */ .word D_1
.size D_80029594_ovl4, . - D_80029594_ovl4

glabel D_80029598_ovl4
/* 1174A8 80029598 */ .word 0x01000000
.size D_80029598_ovl4, . - D_80029598_ovl4

glabel D_8002959C_ovl4
/* 1174AC 8002959C */ .short 0x0000
.size D_8002959C_ovl4, . - D_8002959C_ovl4

glabel D_8002959E_ovl4
/* 1174AE 8002959E */ .short 0x0064
.size D_8002959E_ovl4, . - D_8002959E_ovl4

glabel D_800295A0_ovl4
/* 1174B0 800295A0 */ .short 0x0000
.size D_800295A0_ovl4, . - D_800295A0_ovl4

glabel D_800295A2_ovl4
/* 1174B2 800295A2 */ .short 0x0064
.size D_800295A2_ovl4, . - D_800295A2_ovl4

glabel D_800295A4_ovl4
/* 1174B4 800295A4 */ .word D_1
.size D_800295A4_ovl4, . - D_800295A4_ovl4

glabel D_800295A8_ovl4
/* 1174B8 800295A8 */ .word D_1
.size D_800295A8_ovl4, . - D_800295A8_ovl4

glabel D_800295AC_ovl4
/* 1174BC 800295AC */ .word D_80029978_ovl4
/* 1174C0 800295B0 */ .word D_8002B110_ovl4
/* 1174C4 800295B4 */ .word 0x00000000
/* 1174C8 800295B8 */ .word 0xFFFFFF9C
/* 1174CC 800295BC */ .word 0x00000064
/* 1174D0 800295C0 */ .word 0x00000000
/* 1174D4 800295C4 */ .word D_80029970_ovl4
/* 1174D8 800295C8 */ .word D_8002B114_ovl4
/* 1174DC 800295CC */ .word 0x00000000
/* 1174E0 800295D0 */ .word 0xFFFFFF9C
/* 1174E4 800295D4 */ .word 0x00000064
/* 1174E8 800295D8 */ .word 0x00000000
/* 1174EC 800295DC */ .word D_80029968_ovl4
/* 1174F0 800295E0 */ .word D_8002B118_ovl4
/* 1174F4 800295E4 */ .word 0x00000000
/* 1174F8 800295E8 */ .word 0xFFFFFF9C
/* 1174FC 800295EC */ .word 0x00000064
/* 117500 800295F0 */ .word 0x00000000
/* 117504 800295F4 */ .word D_80029960_ovl4
/* 117508 800295F8 */ .word D_8002B11C_ovl4
/* 11750C 800295FC */ .word 0x00000000
/* 117510 80029600 */ .word 0x00000000
/* 117514 80029604 */ .word D_1
/* 117518 80029608 */ .word 0x00000000
/* 11751C 8002960C */ .word D_80029958_ovl4
/* 117520 80029610 */ .word D_8002B120_ovl4
/* 117524 80029614 */ .word 0x00000000
/* 117528 80029618 */ .word 0xFFFFFF9C
/* 11752C 8002961C */ .word 0x00000064
/* 117530 80029620 */ .word 0x00000000
/* 117534 80029624 */ .word D_80029950_ovl4
/* 117538 80029628 */ .word D_8002B124_ovl4
/* 11753C 8002962C */ .word 0x00000000
/* 117540 80029630 */ .word 0xFFFFFF9C
/* 117544 80029634 */ .word 0x00000064
/* 117548 80029638 */ .word 0x00000000
/* 11754C 8002963C */ .word D_80029948_ovl4
/* 117550 80029640 */ .word D_8002B128_ovl4
/* 117554 80029644 */ .word 0x00000000
/* 117558 80029648 */ .word 0xFFFFFF9C
/* 11755C 8002964C */ .word 0x00000064
/* 117560 80029650 */ .word 0x00000000
.size D_800295AC_ovl4, . - D_800295AC_ovl4

glabel D_80029654_ovl4
/* 117564 80029654 */ .word D_80029980_ovl4
/* 117568 80029658 */ .word 0x00000002
/* 11756C 8002965C */ .word 0x00000004
/* 117570 80029660 */ .word D_800295AC_ovl4
/* 117574 80029664 */ .word 0x00000007
/* 117578 80029668 */ .word 0x00000007
/* 11757C 8002966C */ .word 0x00000005
/* 117580 80029670 */ .word 0x00000004
/* 117584 80029674 */ .word 0x00000000
/* 117588 80029678 */ .word 0x00000000
.size D_80029654_ovl4, . - D_80029654_ovl4

glabel D_8002967C_ovl4
/* 11758C 8002967C */ .word 0x01010000
.size D_8002967C_ovl4, . - D_8002967C_ovl4

glabel D_80029680_ovl4
/* 117590 80029680 */ .word 0x000A000A
/* 117594 80029684 */ .word 0x00000000
/* 117598 80029688 */ .word 0x00000000
/* 11759C 8002968C */ .word 0xFFFFFFFF
/* 1175A0 80029690 */ .word 0xFFF6000A
/* 1175A4 80029694 */ .word 0x00000000
/* 1175A8 80029698 */ .word 0x00000000
/* 1175AC 8002969C */ .word 0xFFFFFFFF
/* 1175B0 800296A0 */ .word 0x000AFFF6
/* 1175B4 800296A4 */ .word 0x00000000
/* 1175B8 800296A8 */ .word 0x00000000
/* 1175BC 800296AC */ .word 0xFFFFFFFF
/* 1175C0 800296B0 */ .word 0xFFF6FFF6
/* 1175C4 800296B4 */ .word 0x00000000
/* 1175C8 800296B8 */ .word 0x00000000
/* 1175CC 800296BC */ .word 0xFFFFFFFF
/* 1175D0 800296C0 */ .word 0x01004008
/* 1175D4 800296C4 */ .word D_80029680_ovl4
/* 1175D8 800296C8 */ .word 0x06000204
/* 1175DC 800296CC */ .word 0x00020604
/* 1175E0 800296D0 */ .word 0xDF000000
/* 1175E4 800296D4 */ .word 0x00000000
.size D_80029680_ovl4, . - D_80029680_ovl4

glabel D_800296D8_ovl4
/* 1175E8 800296D8 */ .word 0x01010000
.size D_800296D8_ovl4, . - D_800296D8_ovl4

glabel D_800296DC_ovl4
/* 1175EC 800296DC */ .word 0x00000000
.size D_800296DC_ovl4, . - D_800296DC_ovl4

glabel D_800296E0_ovl4
/* 1175F0 800296E0 */ .word 0x00000000
.size D_800296E0_ovl4, . - D_800296E0_ovl4

glabel D_800296E4_ovl4
/* 1175F4 800296E4 */ .word 0x00000000
.size D_800296E4_ovl4, . - D_800296E4_ovl4

glabel D_800296E8_ovl4
/* 1175F8 800296E8 */ .word 0x00000000
.size D_800296E8_ovl4, . - D_800296E8_ovl4

glabel D_800296EC_ovl4
/* 1175FC 800296EC */ .short 0x0000
.size D_800296EC_ovl4, . - D_800296EC_ovl4

glabel D_800296EE_ovl4
/* 1175FE 800296EE */ .short 0x0000
.size D_800296EE_ovl4, . - D_800296EE_ovl4

glabel D_800296F0_ovl4
/* 117600 800296F0 */ .short 0x0000
.size D_800296F0_ovl4, . - D_800296F0_ovl4

glabel D_800296F2_ovl4
/* 117602 800296F2 */ .short 0x0003
.size D_800296F2_ovl4, . - D_800296F2_ovl4

glabel D_800296F4_ovl4
/* 117604 800296F4 */ .word D_1010101
.size D_800296F4_ovl4, . - D_800296F4_ovl4

glabel D_800296F8_ovl4
/* 117608 800296F8 */ .word 0x01000000
.size D_800296F8_ovl4, . - D_800296F8_ovl4

glabel D_800296FC_ovl4
/* 11760C 800296FC */ .short 0x0000
.size D_800296FC_ovl4, . - D_800296FC_ovl4

glabel D_800296FE_ovl4
/* 11760E 800296FE */ .short 0x004A
.size D_800296FE_ovl4, . - D_800296FE_ovl4

glabel D_80029700_ovl4
/* 117610 80029700 */ .short 0x0000
.size D_80029700_ovl4, . - D_80029700_ovl4

glabel D_80029702_ovl4
/* 117612 80029702 */ .short 0x0014
.size D_80029702_ovl4, . - D_80029702_ovl4

glabel D_80029704_ovl4
/* 117614 80029704 */ .short 0x0000
.size D_80029704_ovl4, . - D_80029704_ovl4

glabel D_80029706_ovl4
/* 117616 80029706 */ .short 0x000A
.size D_80029706_ovl4, . - D_80029706_ovl4

glabel D_80029708_ovl4
/* 117618 80029708 */ .short 0x0000
.size D_80029708_ovl4, . - D_80029708_ovl4

glabel D_8002970A_ovl4
/* 11761A 8002970A */ .short 0x0014
.size D_8002970A_ovl4, . - D_8002970A_ovl4

glabel D_8002970C_ovl4
/* 11761C 8002970C */ .short 0x0000
.size D_8002970C_ovl4, . - D_8002970C_ovl4

glabel D_8002970E_ovl4
/* 11761E 8002970E */ .short 0x0000
.size D_8002970E_ovl4, . - D_8002970E_ovl4

glabel D_80029710_ovl4
/* 117620 80029710 */ .short 0x0000
.size D_80029710_ovl4, . - D_80029710_ovl4

glabel D_80029712_ovl4
/* 117622 80029712 */ .short 0x0080
.size D_80029712_ovl4, . - D_80029712_ovl4

glabel D_80029714_ovl4
/* 117624 80029714 */ .short 0x0000
.size D_80029714_ovl4, . - D_80029714_ovl4

glabel D_80029716_ovl4
/* 117626 80029716 */ .short 0x0000
.size D_80029716_ovl4, . - D_80029716_ovl4

glabel D_80029718_ovl4
/* 117628 80029718 */ .short 0x0000
.size D_80029718_ovl4, . - D_80029718_ovl4

glabel D_8002971A_ovl4
/* 11762A 8002971A */ .short 0x0000
.size D_8002971A_ovl4, . - D_8002971A_ovl4

glabel D_8002971C_ovl4
/* 11762C 8002971C */ .short 0x0000
.size D_8002971C_ovl4, . - D_8002971C_ovl4

glabel D_8002971E_ovl4
/* 11762E 8002971E */ .short 0x0080
.size D_8002971E_ovl4, . - D_8002971E_ovl4

glabel D_80029720_ovl4
/* 117630 80029720 */ .short 0x0000
.size D_80029720_ovl4, . - D_80029720_ovl4

glabel D_80029722_ovl4
/* 117632 80029722 */ .short 0x00FF
.size D_80029722_ovl4, . - D_80029722_ovl4

glabel D_80029724_ovl4
/* 117634 80029724 */ .word D_80029AB0_ovl4
/* 117638 80029728 */ .word D_800296FC_ovl4
/* 11763C 8002972C */ .word 0x00000000
/* 117640 80029730 */ .word 0x00000000
/* 117644 80029734 */ .word 0x000001F0
/* 117648 80029738 */ .word 0x00000000
/* 11764C 8002973C */ .word D_80029AA4_ovl4
/* 117650 80029740 */ .word D_80029700_ovl4
/* 117654 80029744 */ .word 0x00000000
/* 117658 80029748 */ .word D_1
/* 11765C 8002974C */ .word 0x000003E7
/* 117660 80029750 */ .word 0x00000000
/* 117664 80029754 */ .word D_80029A98_ovl4
/* 117668 80029758 */ .word D_80029704_ovl4
/* 11766C 8002975C */ .word 0x00000000
/* 117670 80029760 */ .word D_1
/* 117674 80029764 */ .word 0x000003E7
/* 117678 80029768 */ .word 0x00000000
/* 11767C 8002976C */ .word D_80029A8C_ovl4
/* 117680 80029770 */ .word D_80029708_ovl4
/* 117684 80029774 */ .word 0x00000000
/* 117688 80029778 */ .word D_1
/* 11768C 8002977C */ .word 0x000003E7
/* 117690 80029780 */ .word 0x00000000
/* 117694 80029784 */ .word D_80029A80_ovl4
/* 117698 80029788 */ .word D_8002970C_ovl4
/* 11769C 8002978C */ .word 0x00000000
/* 1176A0 80029790 */ .word 0x00000000
/* 1176A4 80029794 */ .word 0x000000FF
/* 1176A8 80029798 */ .word 0x00000000
/* 1176AC 8002979C */ .word D_80029A74_ovl4
/* 1176B0 800297A0 */ .word D_80029710_ovl4
/* 1176B4 800297A4 */ .word 0x00000000
/* 1176B8 800297A8 */ .word 0x00000000
/* 1176BC 800297AC */ .word 0x000000FF
/* 1176C0 800297B0 */ .word 0x00000000
/* 1176C4 800297B4 */ .word D_80029A68_ovl4
/* 1176C8 800297B8 */ .word D_80029714_ovl4
/* 1176CC 800297BC */ .word 0x00000000
/* 1176D0 800297C0 */ .word 0x00000000
/* 1176D4 800297C4 */ .word 0x000000FF
/* 1176D8 800297C8 */ .word 0x00000000
/* 1176DC 800297CC */ .word D_80029A5C_ovl4
/* 1176E0 800297D0 */ .word D_80029718_ovl4
/* 1176E4 800297D4 */ .word 0x00000000
/* 1176E8 800297D8 */ .word 0x00000000
/* 1176EC 800297DC */ .word 0x000000FF
/* 1176F0 800297E0 */ .word 0x00000000
/* 1176F4 800297E4 */ .word D_80029A50_ovl4
/* 1176F8 800297E8 */ .word D_8002971C_ovl4
/* 1176FC 800297EC */ .word 0x00000000
/* 117700 800297F0 */ .word 0x00000000
/* 117704 800297F4 */ .word 0x000000FF
/* 117708 800297F8 */ .word 0x00000000
/* 11770C 800297FC */ .word D_80029A44_ovl4
/* 117710 80029800 */ .word D_80029720_ovl4
/* 117714 80029804 */ .word 0x00000000
/* 117718 80029808 */ .word 0x00000000
/* 11771C 8002980C */ .word 0x000000FF
/* 117720 80029810 */ .word 0x00000000
.size D_80029724_ovl4, . - D_80029724_ovl4

glabel D_80029814_ovl4
/* 117724 80029814 */ .word D_80029980_ovl4
/* 117728 80029818 */ .word 0x00000002
/* 11772C 8002981C */ .word 0x00000004
/* 117730 80029820 */ .word D_80029724_ovl4
/* 117734 80029824 */ .word 0x0000000A
/* 117738 80029828 */ .word 0x0000000A
/* 11773C 8002982C */ .word 0x00000008
/* 117740 80029830 */ .word 0x00000004
/* 117744 80029834 */ .word 0x00000000
/* 117748 80029838 */ .word 0x00000000
.size D_80029814_ovl4, . - D_80029814_ovl4

glabel D_8002983C_ovl4
/* 11774C 8002983C */ .word 0x01000000
.size D_8002983C_ovl4, . - D_8002983C_ovl4

.align 2
glabel D_80029840_ovl4
/* 117750 80029840 */ .asciz "SndCont "
.align 2
.size D_80029840_ovl4, . - D_80029840_ovl4

.align 2
glabel D_8002984C_ovl4
/* 11775C 8002984C */ .asciz "TexScrll"
.align 2
.size D_8002984C_ovl4, . - D_8002984C_ovl4

.align 2
glabel D_80029858_ovl4
/* 117768 80029858 */ .asciz "Level   "
.align 2
.size D_80029858_ovl4, . - D_80029858_ovl4

.align 2
glabel D_80029864_ovl4
/* 117774 80029864 */ .asciz "Pol     "
.align 2
.size D_80029864_ovl4, . - D_80029864_ovl4

.align 2
glabel D_80029870_ovl4
/* 117780 80029870 */ .asciz "Beat    "
.align 2
.size D_80029870_ovl4, . - D_80029870_ovl4

.align 2
glabel D_8002987C_ovl4
/* 11778C 8002987C */ .asciz "Bomb    "
.align 2
.size D_8002987C_ovl4, . - D_8002987C_ovl4

.align 2
glabel D_80029888_ovl4
/* 117798 80029888 */ .asciz "Mtx     "
.align 2
.size D_80029888_ovl4, . - D_80029888_ovl4

.align 2
glabel D_80029894_ovl4
/* 1177A4 80029894 */ .asciz "Model   "
.align 2
.size D_80029894_ovl4, . - D_80029894_ovl4

.align 2
glabel D_800298A0_ovl4
/* 1177B0 800298A0 */ .asciz "Chain   "
.align 2
.size D_800298A0_ovl4, . - D_800298A0_ovl4

.align 2
glabel D_800298AC_ovl4
/* 1177BC 800298AC */ .asciz "Raster  "
.align 2
.size D_800298AC_ovl4, . - D_800298AC_ovl4

.align 2
glabel D_800298B8_ovl4
/* 1177C8 800298B8 */ .asciz "Line    "
.align 2
.size D_800298B8_ovl4, . - D_800298B8_ovl4

.align 2
glabel D_800298C4_ovl4
/* 1177D4 800298C4 */ .asciz "OBJECT  "
.align 2
.size D_800298C4_ovl4, . - D_800298C4_ovl4

.align 2
glabel D_800298D0_ovl4
/* 1177E0 800298D0 */ .asciz "SORT    "
.align 2
.size D_800298D0_ovl4, . - D_800298D0_ovl4

.align 2
glabel D_800298DC_ovl4
/* 1177EC 800298DC */ .asciz "IMAGE   "
.align 2
.size D_800298DC_ovl4, . - D_800298DC_ovl4

.align 2
glabel D_800298E8_ovl4
/* 1177F8 800298E8 */ .asciz "NA3 TEST"
.align 2
.align 2
/* 117804 800298F4 */ .asciz ""
.align 2
.size D_800298E8_ovl4, . - D_800298E8_ovl4

glabel jtbl_800298F8_ovl4
/* 117808 800298F8 */ .word .L80025C30_ovl4
/* 11780C 800298FC */ .word .L80025C5C_ovl4
/* 117810 80029900 */ .word .L80025CA8_ovl4
/* 117814 80029904 */ .word .L80025D14_ovl4
/* 117818 80029908 */ .word .L80025D38_ovl4
/* 11781C 8002990C */ .word 0x00000000
.size jtbl_800298F8_ovl4, . - jtbl_800298F8_ovl4

.align 2
glabel D_80029910_ovl4
/* 117820 80029910 */ .asciz "IMG_NO:%3d"
.align 2
.size D_80029910_ovl4, . - D_80029910_ovl4

.align 2
glabel D_8002991C_ovl4
/* 11782C 8002991C */ .asciz "%6d"
.align 2
.size D_8002991C_ovl4, . - D_8002991C_ovl4

.align 2
glabel D_80029920_ovl4
/* 117830 80029920 */ .asciz "%3d"
.align 2
.size D_80029920_ovl4, . - D_80029920_ovl4

.align 2
glabel D_80029924_ovl4
/* 117834 80029924 */ .asciz "X=%3d, Y=%3d, SIZ_X=%3d, SIZ_Y=%3d"
.align 2
.size D_80029924_ovl4, . - D_80029924_ovl4

.align 2
glabel D_80029948_ovl4
/* 117858 80029948 */ .asciz "HRZ2:"
.align 2
.size D_80029948_ovl4, . - D_80029948_ovl4

.align 2
glabel D_80029950_ovl4
/* 117860 80029950 */ .asciz "AMP2:"
.align 2
.size D_80029950_ovl4, . - D_80029950_ovl4

.align 2
glabel D_80029958_ovl4
/* 117868 80029958 */ .asciz "SPD2:"
.align 2
.size D_80029958_ovl4, . - D_80029958_ovl4

.align 2
glabel D_80029960_ovl4
/* 117870 80029960 */ .asciz "DWN :"
.align 2
.size D_80029960_ovl4, . - D_80029960_ovl4

.align 2
glabel D_80029968_ovl4
/* 117878 80029968 */ .asciz "HRZ :"
.align 2
.size D_80029968_ovl4, . - D_80029968_ovl4

.align 2
glabel D_80029970_ovl4
/* 117880 80029970 */ .asciz "AMP :"
.align 2
.size D_80029970_ovl4, . - D_80029970_ovl4

.align 2
glabel D_80029978_ovl4
/* 117888 80029978 */ .asciz "SPD :"
.align 2
.size D_80029978_ovl4, . - D_80029978_ovl4

glabel D_80029980_ovl4
/* 117890 80029980 */ .word 0x00000000
.size D_80029980_ovl4, . - D_80029980_ovl4

.align 2
glabel D_80029984_ovl4
/* 117894 80029984 */ .asciz "%10d"
.align 2
.size D_80029984_ovl4, . - D_80029984_ovl4

.align 2
glabel D_8002998C_ovl4
/* 11789C 8002998C */ .asciz "MOV:%4d"
.align 2
.size D_8002998C_ovl4, . - D_8002998C_ovl4

.align 2
glabel D_80029994_ovl4
/* 1178A4 80029994 */ .asciz "AGL:%4d"
.align 2
.align 2
/* 1178AC 8002999C */ .asciz ""
.align 2
.size D_80029994_ovl4, . - D_80029994_ovl4

glabel D_800299A0_ovl4
/* 1178B0 800299A0 3F91DF46A2529D39 */ .double 0.0174532925199432955
.size D_800299A0_ovl4, . - D_800299A0_ovl4

glabel D_800299A8_ovl4
/* 1178B8 800299A8 404CA5DC1A63C1F8 */ .double 57.2957795130823229
.size D_800299A8_ovl4, . - D_800299A8_ovl4

glabel D_800299B0_ovl4
/* 1178C0 800299B0 3F91DF46A2529D39 */ .double 0.0174532925199432955
.size D_800299B0_ovl4, . - D_800299B0_ovl4

glabel D_800299B8_ovl4
/* 1178C8 800299B8 404CA5DC1A63C1F8 */ .double 57.2957795130823229
.size D_800299B8_ovl4, . - D_800299B8_ovl4

glabel D_800299C0_ovl4
/* 1178D0 800299C0 3F91DF46A2529D39 */ .double 0.0174532925199432955
.size D_800299C0_ovl4, . - D_800299C0_ovl4

glabel D_800299C8_ovl4
/* 1178D8 800299C8 404CA5DC1A63C1F8 */ .double 57.2957795130823229
.size D_800299C8_ovl4, . - D_800299C8_ovl4

glabel D_800299D0_ovl4
/* 1178E0 800299D0 3F91DF46A2529D39 */ .double 0.0174532925199432955
.size D_800299D0_ovl4, . - D_800299D0_ovl4

glabel D_800299D8_ovl4
/* 1178E8 800299D8 404CA5DC1A63C1F8 */ .double 57.2957795130823229
.size D_800299D8_ovl4, . - D_800299D8_ovl4

.align 2
glabel D_800299E0_ovl4
/* 1178F0 800299E0 */ .asciz "%5d,%5d,%5d"
.align 2
.size D_800299E0_ovl4, . - D_800299E0_ovl4

.align 2
glabel D_800299EC_ovl4
/* 1178FC 800299EC */ .asciz "SCL:%3d"
.align 2
.size D_800299EC_ovl4, . - D_800299EC_ovl4

.align 2
glabel D_800299F4_ovl4
/* 117904 800299F4 */ .asciz "DIF:%3d/SPD:%3d"
.align 2
.size D_800299F4_ovl4, . - D_800299F4_ovl4

.align 2
glabel D_80029A04_ovl4
/* 117914 80029A04 */ .asciz " "
.align 2
.size D_80029A04_ovl4, . - D_80029A04_ovl4

.align 2
glabel D_80029A08_ovl4
/* 117918 80029A08 */ .asciz "%2d:"
.align 2
.size D_80029A08_ovl4, . - D_80029A08_ovl4

.align 2
glabel D_80029A10_ovl4
/* 117920 80029A10 */ .asciz "O"
.align 2
.size D_80029A10_ovl4, . - D_80029A10_ovl4

.align 2
glabel D_80029A14_ovl4
/* 117924 80029A14 */ .asciz "LEV:%d/DAT:%2d/RET:%5.2f"
.align 2
.size D_80029A14_ovl4, . - D_80029A14_ovl4

.align 2
glabel D_80029A30_ovl4
/* 117940 80029A30 */ .asciz "bg00"
.align 2
.size D_80029A30_ovl4, . - D_80029A30_ovl4

.align 2
glabel D_80029A38_ovl4
/* 117948 80029A38 */ .asciz "%4X"
.align 2
.size D_80029A38_ovl4, . - D_80029A38_ovl4

.align 2
glabel D_80029A3C_ovl4
/* 11794C 80029A3C */ .asciz "/%4X"
.align 2
.size D_80029A3C_ovl4, . - D_80029A3C_ovl4

.align 2
glabel D_80029A44_ovl4
/* 117954 80029A44 */ .asciz "OUT PAN:"
.align 2
.size D_80029A44_ovl4, . - D_80029A44_ovl4

.align 2
glabel D_80029A50_ovl4
/* 117960 80029A50 */ .asciz "PLY PAN:"
.align 2
.size D_80029A50_ovl4, . - D_80029A50_ovl4

.align 2
glabel D_80029A5C_ovl4
/* 11796C 80029A5C */ .asciz "IN  PAN:"
.align 2
.size D_80029A5C_ovl4, . - D_80029A5C_ovl4

.align 2
glabel D_80029A68_ovl4
/* 117978 80029A68 */ .asciz "OUT VOL:"
.align 2
.size D_80029A68_ovl4, . - D_80029A68_ovl4

.align 2
glabel D_80029A74_ovl4
/* 117984 80029A74 */ .asciz "PLY VOL:"
.align 2
.size D_80029A74_ovl4, . - D_80029A74_ovl4

.align 2
glabel D_80029A80_ovl4
/* 117990 80029A80 */ .asciz "IN  VOL:"
.align 2
.size D_80029A80_ovl4, . - D_80029A80_ovl4

.align 2
glabel D_80029A8C_ovl4
/* 11799C 80029A8C */ .asciz "OUT TIM:"
.align 2
.size D_80029A8C_ovl4, . - D_80029A8C_ovl4

.align 2
glabel D_80029A98_ovl4
/* 1179A8 80029A98 */ .asciz "PLY TIM:"
.align 2
.size D_80029A98_ovl4, . - D_80029A98_ovl4

.align 2
glabel D_80029AA4_ovl4
/* 1179B4 80029AA4 */ .asciz "IN  TIM:"
.align 2
.size D_80029AA4_ovl4, . - D_80029AA4_ovl4

.align 2
glabel D_80029AB0_ovl4
/* 1179C0 80029AB0 */ .asciz "SND COD:"
.align 2
.align 2
/* 1179CC 80029ABC */ .asciz ""
.align 2
.size D_80029AB0_ovl4, . - D_80029AB0_ovl4

glabel D_80029AC0_ovl4
/* 1179D0 80029AC0 3F91DF46A2529D39 */ .double 0.0174532925199432955
.size D_80029AC0_ovl4, . - D_80029AC0_ovl4

.align 2
glabel D_80029AC8_ovl4
/* 1179D8 80029AC8 */ .asciz "MOV:%4d"
.align 2
.size D_80029AC8_ovl4, . - D_80029AC8_ovl4

.align 2
glabel D_80029AD0_ovl4
/* 1179E0 80029AD0 */ .asciz "AGL:%4d"
.align 2
.size D_80029AD0_ovl4, . - D_80029AD0_ovl4

glabel D_80029AD8_ovl4
/* 1179E8 80029AD8 404CA5DC1A63C1F8 */ .double 57.2957795130823229
.size D_80029AD8_ovl4, . - D_80029AD8_ovl4

glabel D_80029AE0_ovl4
/* 1179F0 80029AE0 3F91DF46A2529D39 */ .double 0.0174532925199432955
.size D_80029AE0_ovl4, . - D_80029AE0_ovl4

glabel D_80029AE8_ovl4
/* 1179F8 80029AE8 404CA5DC1A63C1F8 */ .double 57.2957795130823229
.size D_80029AE8_ovl4, . - D_80029AE8_ovl4
